guacamole-common-js/src/main/webapp/modules/AudioPlayer.js
guacamole-common-js/src/main/webapp/modules/AudioRecorder.js
guacamole-common-js/src/main/webapp/modules/Client.js
guacamole-common-js/src/main/webapp/modules/RawAudioFormat.js
guacamole/src/main/webapp/app/client/types/ManagedClient.js

This change adds a new `Guacamole.AudioRecorder` interface and `Guacamole.RawAudioRecorder` implementation, analogous to the existing `Guacamole.AudioPlayer` and `Guacamole.RawAudioPlayer`, providing support for audio input within the Guacamole JavaScript API.
The raw audio recorder uses the Web Audio API to read raw audio data from the user's microphone, if permission to do so is granted. The attempt to read data will only be made once the outbound stream has been acknowledged, so the user will not be prompted to provide permission if audio input is disabled on the connection or unsupported by the server.
As both `Guacamole.RawAudioPlayer` and `Guacamole.RawAudioRecorder` deal with the same mimetypes and format objects, I have also refactored the previously-private …

GUAC-1511: Add client-side support for audio input.

---

guacamole-common-js/src/main/webapp/modules/AudioContextFactory.js
guacamole-common-js/src/main/webapp/modules/AudioPlayer.js
guacamole-common-js/src/main/webapp/modules/AudioRecorder.js

A page only ever needs one instance of `AudioContext`. If too many `AudioContext` instances are created, the browser will deny further creation, resulting in errors when Guacamole assumes such creation must succeed.
This change adds a new `Guacamole.AudioContextFactory` namespace which contains a lazily-created singleton instance of `AudioContext`. The instance is maintained and returned by `getAudioContext()`, and can be overridden be manually assigning the `singleton` property (if you already have your own `AudioContext`, for example).

GUAC-1517: Maintain singleton instance of AudioContext.

---

guacamole-common-js/src/main/webapp/modules/ArrayBufferWriter.js
guacamole-common-js/src/main/webapp/modules/AudioRecorder.js

This change addresses the following issues discovered during continued development of GUAC-1511:
1. The blob size used by `Guacamole.ArrayBufferWriter` was too large, and could easily exceed the per-instruction maximum of 8192 bytes enforced by guacd.
2. The buffer size used by `Guacamole.RawAudioRecorder` is actually in sample-frames, not in bytes. There is no need to increase the buffer size with respect to the number of bytes per sample.
3. The `SampleArray` is not in sample-frames, but in samples. Its size must take the number of channels into account.
4. There is no guarantee that the browser will magically use the sample rate desired. We need resample as necessary to force the audio to the correct format. I've added rather naiive, simple resampling. We should look into a better …

GUAC-1511: Fix audio input bugs in initial client implementation.

---

guacamole-common-js/src/main/webapp/modules/AudioRecorder.js

This change fixes issues in recorded audio quality due to:
1. Overly-naive resampling
2. Underflow/overflow due to rounding error (again related to resampling)
3. Insufficient buffering
Lacking these improvements, recorded audio is full of clicks and gradually falls out of sync.

GUACAMOLE-25: Address quality issues with audio input

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/webapp/translations/en.json

The significantly-simpler sibling of apache/incubator-guacamole-server#12.

GUACAMOLE-25: Add "enable-audio-input" parameter for RDP.

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js
guacamole-common/src/main/java/org/apache/guacamole/net/GuacamoleTunnel.java
guacamole-common/src/main/java/org/apache/guacamole/websocket/GuacamoleWebSocketTunnelEndpoint.java
guacamole/src/main/java/org/apache/guacamole/GuacamoleSession.java
guacamole/src/main/java/org/apache/guacamole/rest/RESTServiceModule.java
guacamole/src/main/java/org/apache/guacamole/rest/tunnel/TunnelRESTService.java
guacamole/src/main/java/org/apache/guacamole/tunnel/StreamInterceptingTunnel.java
guacamole/src/main/java/org/apache/guacamole/tunnel/TunnelRequestService.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty8/GuacamoleWebSocketTunnelServlet.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty9/GuacamoleWebSocketTunnelListener.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/tomcat/GuacamoleWebSocketTunnelServlet.java
guacamole/src/main/webapp/app/rest/services/tunnelService.js

This change implements a new REST endpoint which allows the streams within a Guacamole connection to be intercepted and handled as normal HTTP transfers. This is necessary to avoid requiring assembly of the downloaded file within browser memory, the underlying cause of [GUACAMOLE-44](https://issues.apache.org/jira/browse/GUACAMOLE-44).
For the REST endpoint to work, tunnels need to have their own unique identifiers. Thankfully, each instance of `GuacamoleTunnel` already has its own UUID. This change thus also:
1. Adds a new `uuid` property to implementations of `Guacamole.Tunnel`.
2. Reserves the empty opcode for transport of arbitrary tunnel-specific data (as there is no way to communicate the UUID over WebSocket otherwise).
The empty opcode was already used in this manner by the HTTP …

GUACAMOLE-44: Implement tunnel REST endpoint

---

guacamole-common-js/src/main/webapp/modules/ArrayBufferWriter.js
guacamole-common-js/src/main/webapp/modules/FileWriter.js
guacamole/src/main/webapp/app/client/types/ManagedFileUpload.js

The old file upload code was inherently flawed as it required reading the entire file into memory. Besides being a poor user experience (long delay before upload begins), this could even crash the browser if the file was large enough.
This change adds a new writer-style object, `Guacamole.FileWriter`, whose `sendFile()` efficiently streams a provided `File` over an underlying `Guacamole.OutputStream`. The implementation streams the `File` properly via `slice()`; it is not read in its entirety into memory.
As this required wrapping a `Guacamole.ArrayBufferWriter` and being aware of the Guacamole protocol's instruction size restrictions, this change replaces the old magic 6048 with a well-documented constant, `Guacamole.ArrayBufferWriter.DEFAULT_BLOB_LENGTH`, and exposes the blob length …

GUACAMOLE-44: Slice uploaded files into chunks (DO NOT slurp entire file into memory)

---

guacamole/src/main/webapp/app/client/types/ManagedFileUpload.js

As `ManagedFileUpload.getInstance()` is sometimes invoked within `$apply()`, invoking `$apply()` again directly results in a `$digest` loop and error.

GUACAMOLE-44: ManagedFileUpload.getInstance() must not directly invoke $apply()

---

guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleStatus.java
guacamole/src/main/java/org/apache/guacamole/rest/APIError.java
guacamole/src/main/java/org/apache/guacamole/rest/APIException.java
guacamole/src/main/java/org/apache/guacamole/rest/RESTExceptionWrapper.java
guacamole/src/main/java/org/apache/guacamole/rest/tunnel/TunnelRESTService.java
guacamole/src/main/java/org/apache/guacamole/tunnel/GuacamoleStreamException.java
guacamole/src/main/java/org/apache/guacamole/tunnel/InputStreamInterceptingFilter.java
guacamole/src/main/java/org/apache/guacamole/tunnel/InterceptedStream.java
guacamole/src/main/java/org/apache/guacamole/tunnel/InterceptedStreamMap.java
guacamole/src/main/java/org/apache/guacamole/tunnel/OutputStreamInterceptingFilter.java
guacamole/src/main/java/org/apache/guacamole/tunnel/StreamInterceptingFilter.java
guacamole/src/main/java/org/apache/guacamole/tunnel/StreamInterceptingTunnel.java
guacamole/src/main/webapp/app/rest/services/tunnelService.js
guacamole/src/main/webapp/app/rest/types/Error.js

Similar to apache/incubator-guacamole-client#13, this change implements the upload half of the tunnel REST endpoint. While it is possible to upload using JavaScript alone via the new `Guacamole.FileWriter` added via apache/incubator-guacamole-client#14, doing so instead via native HTTP is **much faster**.
To facilitate translation of Guacamole protocol status codes (received via "ack" instructions along the stream) to HTTP errors and `APIError` entities, this change also:
1. Adds a new `fromGuacamoleStatusCode()` to the `GuacamoleStatus` enum, allowing the integer status codes to be directly translated to typesafe `GuacamoleStatus` values.
2. Adds a new `statusCode` property to `APIError` (and it's JavaScript sibling `Error`), along with a new error type, `STREAM_ERROR`, for the sake of …

GUACAMOLE-44: Implement uploads within tunnel REST endpoint

---

guacamole/src/main/webapp/app/login/styles/dialog.css
guacamole/src/main/webapp/app/login/templates/login.html
guacamole/src/main/webapp/translations/de.json
guacamole/src/main/webapp/translations/en.json
guacamole/src/main/webapp/translations/fr.json
guacamole/src/main/webapp/translations/it.json
guacamole/src/main/webapp/translations/nl.json
guacamole/src/main/webapp/translations/ru.json

This change updates the application name from "Guacamole" to "Apache Guacamole" via the translation strings. As the version number is now quite long, I've also separated the old `APP.NAME` into `APP.NAME` and `APP.VERSION`, and reorganized the login screen to keep things clean:
> ![apache-guac-login](https://cloud.githubusercontent.com/assets/4632905/15949590/97a385ee-2e5d-11e6-8d97-7df3217665da.png)

GUACAMOLE-1: Interface should say "Apache Guacamole", not "Guacamole".

---

guacamole-docker/Dockerfile

I've tested this with the MySQL auth against and RDP EC2 instance, seems to work fine.
I've also been running Guacamole in production on Java 8 for over 6 months with no known issues.

GUACAMOLE-50: Update Docker container to use Java 8

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.10.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.10.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml

From [GUACAMOLE-52](https://issues.apache.org/jira/browse/GUACAMOLE-52):
> The connection history records currently stored within the Guacamole database schema are always deleted when an associated user or connection is deleted (due to "ON DELETE CASCADE"). This maintains consistency, but has a number of problems:
> 
> 1. Historical records become permanently unavailable if the corresponding user account or connection are deleted.
> 2. Table replication for the sake of providing a centralized log across multiple instances is impossible as foreign keys will not necessarily be consistent across the databases.
> 
> This could be resolved by removing the dependencies on ID for context. While foreign keys should still be maintained, the table could be augmented to include connection name and …

GUACAMOLE-52: Ensure history records remain when users/connections are deleted.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ModeledConnectionGroup.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/AuthenticatedUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.10.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.10.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupMapper.xml

This change adds a new connection group attribute which, if enabled, causes balancing groups to consistently route the same users to the same connections until those users log out.

GUACAMOLE-53: Implement session affinity for balancing groups

---

guacamole-common-js/src/main/webapp/modules/BlobWriter.js

The `Guacamole.FileWriter` object introduced recently (see commit 998eff9 from pull request #14) really should have instead been `Guacamole.BlobWriter`. We already have a corresponding `Guacamole.BlobReader`, and a JavaScript `File` is actually a `Blob` anyway.
This change allows the previously-written writer to be used for *both* `File` and `Blob` objects without violating its documentation.

GUACAMOLE-55: Refactor FileWriter to BlobWriter.

---

guacamole/src/main/java/org/apache/guacamole/rest/RESTExceptionWrapper.java
guacamole/src/main/java/org/apache/guacamole/rest/activeconnection/ActiveConnectionDirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/activeconnection/ActiveConnectionModule.java
guacamole/src/main/java/org/apache/guacamole/rest/connection/ConnectionDirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/connection/ConnectionModule.java
guacamole/src/main/java/org/apache/guacamole/rest/directory/DirectoryObjectResource.java
guacamole/src/main/java/org/apache/guacamole/rest/directory/DirectoryResource.java

The recent refactor caused issues where actual type-specific implementations were not provided for the REST resources. All REST resources **MUST** be non-generic, thus `DirectoryResource` and `DirectoryObjectResource` **MUST NOT** be used directly. Type parameters of generic classes will otherwise be handled by Jersey as `Object` due to type erasure, resulting in class cast exceptions due to received JSON being deserialized as a `Map` instead of the intended type.
This change also updates the logging and error handling within `RESTExceptionWrapper` such that this sort of thing will be easier to notice going forward. Internal errors were not being properly logged, especially those which were not subclasses of `GuacamoleException`.

GUACAMOLE-5: Fix regression introduced by recent refactor of the REST API

---

guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractActiveConnection.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractAuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractConnection.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractConnectionGroup.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractIdentifiable.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractUser.java

To make developers lives easier, including my own, this change moves the common `equals()` and `hashCode()` of the `Identifiable` implementations used throughout the Guacamole API to a common base class: `AbstractIdentifiable`.
The logic is identical to all past version of Guacamole. The code in question is simply no longer duplicated.

GUACAMOLE-5: Move common equals() / hashCode() of Identifiable implementations to base class

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/TrackedActiveConnection.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/ConnectionSharingService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/HashSharedConnectionMap.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SecureRandomShareKeyGenerator.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/ShareKeyGenerator.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnection.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnectionDefinition.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnectionMap.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnectionUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnectionUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/ActiveConnectionRecord.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/GuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/RestrictedGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/AuthenticatedUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/AuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/RemoteAuthenticatedUser.java

This change adds support for generation of temporary user credentials for shared connections.
The implementation produces sets of credentials which define only a single query parameter (`key`), which is accepted by the `AuthenticationProvider` and tied to a new `SharedConnectionUserContext`. The user context provides access only to a single connection which transparently joins the underlying existing connection, with the whole tree of data residing only in memory.

GUACAMOLE-5: Implement connection sharing within database auth

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/TrackedActiveConnection.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/ConnectionSharingService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/HashSharedConnectionMap.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnection.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnectionDefinition.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnectionMap.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedObjectManager.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/ActiveConnectionRecord.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/GuacamoleTunnelService.java

This change alters the behavior of connections shared via the JDBC auth backend such that:
1. The share keys generated for an active connection are invalidated once that connection closes.
2. Share keys created for a closed connection are immediately invalidated.
3. The tunnels created by users of a share key are closed once the share key is invalidated.
4. Tunnels created by users of a share key are immediately closed if the share key is already invalid.
From the user's perspective, the effect of all this is that shared connections automatically close when the original connection is closed, and cannot be reestablished. Reconnecting after a disconnect is only possible for a shared connection if the original connection is still running.
It is particularly important that this is guaranteed …

GUACAMOLE-5: Invalidate share keys and close associated tunnels when the shared connection is closed

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/ActiveConnectionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.xml
guacamole/src/main/java/org/apache/guacamole/rest/tunnel/TunnelResource.java

This change fixes the following issues discovered after testing sharing profiles in a production environment against non-admin users:
1. The tunnel beneath an active connection was only being exposed to admin users, thus breaking the `.../api/session/tunnels/[UUID]/activeConnection` resource for non-admins. Users should be able to see the data associated with their own active connections.
2. As the above resource was written under the faulty assumption that the active connection can always be retrieved (what if the extension does not implement active connection tracking), a hard HTTP 500 was thrown when this assumption failed. The resource should instead throw a nice HTTP 404.
3. The permission-restricted query for retrieving the sharing profile identifiers associated with a particular …

GUACAMOLE-5: Fix non-admin access to sharing profiles.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql

We need to fix this to restore the mysql schema create script to working order.

GUACAMOLE-5 Fix syntax error in mysql create script by adding missing comma.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedConnectionUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLAuthenticationProvider.java

This change removes the need to inject `AuthenticationProvider` within the database auth backend. In contrast to my other PRs lately, it's mostly deletions.
To allow multiple connection share keys to be used within a single session (producing a `UserContext` which contains the union of all shared connections provided by those keys), I need to move the sharing bits to their own `AuthenticationProvider` within the same extension.
This is possible, but will require that a common Guice injector is shared between those two auth providers. That is *also* possible, but will require that a common and reliable set of dependencies exist, ideally the *same* dependencies.
It turns out that the only dependency that would be different between the two is the `AuthenticationProvider` itself, which is …

GUACAMOLE-5: Remove need to bind/inject AuthenticationProvider

---

guacamole/pom.xml
guacamole/src/main/java/org/apache/guacamole/rest/auth/SecureRandomAuthTokenGenerator.java

We already have a standard way of converting a byte array to a hex string, so let's just use that instead.

GUACAMOLE-66: Remove Apache Commons Codec dependency.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ObjectModel.java

Lacking such validation, attempts to go to invalid client URLs (such as stale URLs from a past shared connection) result in hard SQL errors if the backend database is PostgreSQL.

GUACAMOLE-5: Properly validate identifiers before attempting to query.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/AuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/InjectedAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCInjectorProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SharedAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLInjectorProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLSharedAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLInjectorProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLSharedAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json

The database authentication backend currently implements support for unique "share keys", which can be used as an alternative and temporary method of authentication for accessing shared connections. Prior to this change, it was the duty of the `AuthenticationProvider` to handle both username/password authentication *and* share key authentication.
This change splits the PostgreSQL/MySQL `AuthenticationProvider` implementations into two: one which is specific to username/password auth against the database, and the other which is specific to share key authentication against in-memory shared connections. Both share a common Guice `Injector` and, thus, a common set of core services. Collaborative management of shared connections between the two is achieved through a common service which …

GUACAMOLE-5: Separate sharing semantics from database-backed AuthenticationProvider

---

guacamole-common/src/main/java/org/apache/guacamole/websocket/GuacamoleWebSocketTunnelEndpoint.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty8/GuacamoleWebSocketTunnelServlet.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty9/GuacamoleWebSocketTunnelListener.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/tomcat/GuacamoleWebSocketTunnelServlet.java

From [GUACAMOLE-67](https://issues.apache.org/jira/browse/GUACAMOLE-67):
> If Tomcat (or another servlet container) encounters a hard, internal I/O error while handling a WebSocket connection, the resulting `IOException` will cause the connection thread to die:
> 
> ```
> 15:39:50.882 [Thread-19] DEBUG o.a.g.w.GuacamoleWebSocketTunnelEndpoint - I/O error prevents further reads.
> java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Key must be cancelled
> 	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:228) ~[tomcat-websocket.jar:8.0.14]
> 	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:172) ~[tomcat-websocket.jar:8.0.14]
> 	at …
```

GUACAMOLE-67: Always clean up the connection upon WebSocket error.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ObjectModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java

Pull request #38 introduced a regression which made it impossible to retrieve specific users. This is because the assumption driving #38 (that all identifiers within the JDBC auth are numeric strings) is incorrect. `User` objects within the JDBC auth have pure string identifiers which are not derived from internal numeric IDs and need not be numeric.
This change moves the validity checking from the base `ObjectModel` class into the object-specific `ModeledDirectoryObjectService` class, such that the `Directory` implementation itself can override the default numeric-only behavior if the objects truly do not require numeric identifiers.

GUACAMOLE-5: Fix identifier validity regression.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/InjectedAuthenticationProvider.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPAuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleAuthenticationProvider.java
guacamole/src/main/java/org/apache/guacamole/extension/AuthenticationProviderFacade.java
guacamole/src/main/java/org/apache/guacamole/rest/auth/AuthenticationService.java

The `updateUserContext()` function of `AuthenticationProvider` has existed for a while, but it was written under the assumption that `AuthenticatedUser` will always receive an updated set of credentials, thus the possibly-updated `UserContext` will be able to access this information.
This is false. The `AuthenticatedUser` will only be updated if `updateAuthenticatedUser()` does so, and relying on that is bad. There's not much for `updateUserContext()` to update with if it can't be guaranteed access to fresh information.
Updating `UserContext` may require peeking at the most recent HTTP request / credentials, so the most recent `Credentials` object should be passed to `updateUserContext()` as well.

GUACAMOLE-5: Provide most recent Credentials to updateUserContext()

---

guacamole/src/main/java/org/apache/guacamole/rest/connection/APIConnection.java
guacamole/src/main/java/org/apache/guacamole/rest/connectiongroup/ConnectionGroupTree.java
guacamole/src/main/webapp/app/groupList/directives/guacGroupList.js
guacamole/src/main/webapp/app/groupList/templates/guacGroupList.html
guacamole/src/main/webapp/app/groupList/types/GroupListItem.js
guacamole/src/main/webapp/app/home/templates/connection.html
guacamole/src/main/webapp/app/index/styles/lists.css
guacamole/src/main/webapp/app/index/styles/ui.css
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/manage/templates/connectionGroupPermission.html
guacamole/src/main/webapp/app/manage/templates/connectionPermission.html
guacamole/src/main/webapp/app/manage/templates/manageUser.html
guacamole/src/main/webapp/app/manage/templates/sharingProfilePermission.html
guacamole/src/main/webapp/app/rest/services/permissionService.js
guacamole/src/main/webapp/app/rest/types/Connection.js
guacamole/src/main/webapp/app/rest/types/PermissionFlagSet.js
guacamole/src/main/webapp/app/rest/types/PermissionSet.js
guacamole/src/main/webapp/app/settings/templates/connection.html
guacamole/src/main/webapp/translations/en.json

Though previous changes did add support within the REST API for management of sharing profile permissions, such support remained absent in the admin interface.
This change adds support for managing sharing profile permissions on a per-user basis, as well as granting/revoking the system-level permission for creating sharing profiles. Management of sharing profile permissions is handled within the same hierarchical tree previously used only for connections and connection groups, handling the sharing profiles associated with a connection as if they were the connections within a group:
To make the tree more readable, I altered the rendering of the tree lines such that they have the traditional right-angle bends and terminate at the rough midpoint of each list item. This style is inherited by …

GUACAMOLE-5: Add support for managing sharing profile permissions.

---

guacamole/src/main/webapp/app/groupList/directives/guacGroupList.js
guacamole/src/main/webapp/app/groupList/templates/guacGroupList.html
guacamole/src/main/webapp/app/groupList/types/GroupListItem.js
guacamole/src/main/webapp/app/home/controllers/homeController.js
guacamole/src/main/webapp/app/home/templates/connectionGroup.html
guacamole/src/main/webapp/app/home/templates/home.html
guacamole/src/main/webapp/app/index/styles/lists.css
guacamole/src/main/webapp/app/index/styles/ui.css
guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js
guacamole/src/main/webapp/app/manage/templates/locationChooser.html
guacamole/src/main/webapp/app/manage/templates/manageUser.html
guacamole/src/main/webapp/app/settings/directives/guacSettingsConnections.js
guacamole/src/main/webapp/app/settings/styles/connection-list.css
guacamole/src/main/webapp/app/settings/templates/newConnection.html
guacamole/src/main/webapp/app/settings/templates/newConnectionGroup.html
guacamole/src/main/webapp/app/settings/templates/settingsConnections.html

This change adds special "New Connection" and "New Connection Group" options within expanded connection groups in the connection administration interface, allowing connections and groups to be created directly therein:
This is accomplished through two main changes:
1. Adding a new `decorator` attribute to `guacGroupList`, which allows arbitrary modifications to be made to the `GroupListItem[]` which is rendered by the directive.
2. Adding a new `weight` property to `GroupListItem` such that sorting order can be manipulated independently of item name.
3. Migrating from `connectionTemplate`, `connectionGroupTemplate`, etc. attributes to a single, generic `template` attribute, which defines all templates via a map of type to template URL.
With the above, arbitrary new `GroupListItem` types …

GUACAMOLE-5: Add contextual options for creating connections and groups.

---

guacamole/src/main/java/org/apache/guacamole/rest/schema/SchemaResource.java
guacamole/src/main/webapp/app/rest/services/schemaService.js
guacamole/src/main/webapp/app/rest/services/sharingProfileService.js

This changes adds the missing REST resource for sharing profile attributes, and implements JavaScript services/functions for accessing all sharing-profile-related REST resources.

GUACAMOLE-5: Add missing sharing profile REST services.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/html/shared-connection.html
guacamole/src/main/webapp/app/home/templates/connection.html
guacamole/src/main/webapp/app/home/templates/connectionGroup.html

Recent changes to the HTML structure of connections displayed by `guacGroupList` within the home screen broke the nifty new share tag (the CSS selector within the patch no longer matched).
This change switches to more predictable and specific CSS classes within the home screen's `guacGroupList`, and simplifies the selector in question.

GUACAMOLE-5: Fix targeting of share tag HTML patch.

---

guacamole/src/main/webapp/app/manage/templates/manageSharingProfile.html

The old `forms` property was split into `connectionForms` and `sharingProfileForms` recently, but this line somehow remains unchanged, resulting in a total lack of parameters when editing a sharing profile.

GUACAMOLE-72: Sharing profile parameters are stored under "sharingProfileForms", not "forms".

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionGroupPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/SharingProfilePermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/SystemPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserPermissionMapper.xml

While the MySQL permission inserts use `INSERT IGNORE` to ignore any violations of the table-wide unique constraint, the corresponding PostgreSQL inserts do not. PostgreSQL actually does not have such an option, at least not until recently via `ON CONFLICT UPDATE`.
This change rewrites the permission inserts for PostgreSQL such that only non-duplicate tuples are inserted.

GUACAMOLE-75: Do not insert duplicate permissions.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/SecureRandomShareKeyGenerator.java

This change switches from problematic base64 share keys to URL-safe ("base64url", as defined in [RFC 4648, Section 5](https://tools.ietf.org/html/rfc4648#section-5)) share keys. Effective key length remains the same (264-bit).

GUACAMOLE-74: Migrate to URL-safe share keys.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/user/SharedAuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AuthenticatedUser.java
guacamole/src/main/webapp/app/auth/service/authenticationService.js
guacamole/src/main/webapp/app/auth/types/AuthenticationResult.js
guacamole/src/main/webapp/app/index/config/indexRouteConfig.js
guacamole/src/main/webapp/app/list/directives/guacUserItem.js
guacamole/src/main/webapp/app/list/styles/user-item.css
guacamole/src/main/webapp/app/list/templates/guacUserItem.html
guacamole/src/main/webapp/app/manage/templates/manageConnection.html
guacamole/src/main/webapp/app/navigation/directives/guacUserMenu.js
guacamole/src/main/webapp/app/navigation/templates/guacUserMenu.html
guacamole/src/main/webapp/app/settings/templates/settingsConnectionHistory.html
guacamole/src/main/webapp/app/settings/templates/settingsSessions.html
guacamole/src/main/webapp/translations/en.json

There has historically been no way to properly represent an anonymous user within the Guacamole extension API. All users are required to have unique identifiers, and the user interface renders a user-specific menu with logout button at all times.
This change defines a reserved identifier (`AuthenticatedUser.ANONYMOUS_IDENTIFIER` in Java, `AuthenticationResult.ANONYMOUS_USERNAME` in JavaScript, in both cases simply the empty string) which implicitly declares the user as anonymous, but must not be used for any other purpose. The JDBC authentication has been modified to return this username when a user authenticated via a share key (and thus has no associated user account).
Unlike a traditionally-authenticated user, an anonymous user is not presented the "user menu" which  typically contains …

GUACAMOLE-78: Handle anonymous users distinctly.

---

guacamole/src/main/webapp/app/rest/services/connectionGroupService.js
guacamole/src/main/webapp/app/rest/services/connectionService.js
guacamole/src/main/webapp/app/rest/services/sharingProfileService.js

The permissions live in the user cache, so clearing the user cache upon save/update of connections or connection groups solves this issue.

GUACAMOLE-73: Clear permission cache when saving or updating to force permission reload.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ModeledConnection.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ModeledConnectionGroup.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.xml

Speed of the connection group tree REST resource fell dramatically with the addition of sharing profiles. This is because the `getSharingProfileIdentifiers()` function of `Connection` issues a new query for every call, and is not affected by retrieval of connections in batches via `getAll()` on the `Directory<Connection>`.
This change addresses this by retrieving child object identifiers when the parents are retrieved. If multiple parents are retrieved, the identifiers of each of their children is retrieved with *one query* (rather than *N queries*). This is accomplished through issuing multiple `SELECT` statements within the same logical query defined in the MyBatis mapping. Beware that while PostgreSQL will handle multiple statements within a single query by default, the MySQL JDBC …

GUACAMOLE-76: Fix N+1 problem when querying connection group tree.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/user/SharedUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json
guacamole/src/main/java/org/apache/guacamole/rest/session/UserContextResource.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserDirectoryResource.java
guacamole/src/main/webapp/app/rest/services/permissionService.js

This change establishes the distinction within the REST API between the user object *representing* the current user (`.../self`) and the user object representing an *existing* user (`.../users/{username}`).
This distinction has existed within `UserContext` for some time, but was never exposed within the REST API. It's an important distinction, as just because a backend agrees on a user's identity does not mean the user actually exists within the backend.
By implementing the above change (b23dcf8), and by not listing pseudo-accounts within the user directory of the sharing auth provider (36dc375), the non-relevant pseudo-accounts are no longer displayed as options in the admin interface. In case they ever *do* get displayed somewhere unexpectedly, they will at least be readable, as I've …

GUACAMOLE-77: Ensure non-existent user accounts are not displayed.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ChildObjectModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledChildDirectoryObject.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledChildDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ModeledConnection.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ModeledConnectionGroup.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharingprofile/ModeledSharingProfile.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileMapper.xml

This change generalizes the connection group / connection permission logic such that it can be applied to any parent/child relationship, and reapplies that logic against sharing profiles and their primary (parent) connections.

GUACAMOLE-81: Verify primary connection permissions when modifying sharing profiles.

---

guacamole/src/main/webapp/app/clipboard/directives/guacClipboard.js
guacamole/src/main/webapp/app/clipboard/styles/clipboard.css
guacamole/src/main/webapp/app/clipboard/templates/guacClipboard.html

This change partially reverts [GUACAMOLE-55](https://issues.apache.org/jira/browse/GUACAMOLE-55), restoring the original `<textarea>` clipboard field while keeping the nice `guacClipboard` directive and data abstraction.
The original change is still worth doing, but not at the expense of 0.9.10-incubating. More time is needed to iron out all the browser quirks related to content-editable divs.

GUACAMOLE-82: Move back to textarea for clipboard for sake of stability.

---

doc/guacamole-example/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/pom.xml
extensions/guacamole-auth-ldap/pom.xml
extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json
extensions/guacamole-auth-noauth/pom.xml
extensions/guacamole-auth-noauth/src/main/resources/guac-manifest.json
guacamole-common-js/pom.xml
guacamole-common-js/src/main/webapp/modules/Version.js
guacamole-common/pom.xml
guacamole-ext/pom.xml
guacamole/pom.xml
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionModule.java
pom.xml

The Dockerfile is untouched because it needs more work before the release; simply bumping the version numbers in it would be insufficient.

GUACAMOLE-87: Bump guacamole-client version numbers to 0.9.10-incubating

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql

The colum sharing_profile_name in guacamole_connection_history was set to NOT NULL. Regular sessions do not have a sharing_profile_name so this caused an exception when guacamole tried to save them. Changed it to DEFAULT NULL (like in the mysql schema) to solve to problem.

GUACAMOLE-95: Minor change to postgresql schema. Fixes saving sessions to history. 

---

guacamole/src/main/webapp/app/rest/services/tunnelService.js

To make tomcat happy, we can just replace slashes with something else - in this case underscores.

GUACAMOLE-104: Sanitize filenames before upload or download.

---

guacamole-docker/README.md

Beware that this does contain references to Docker images which do not yet exist (as well as the non-existent "0.9.10-incubating" tag). Those things will exist post-release.

GUACAMOLE-97: Update Guacamole Docker README.md with respect to Apache.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/UserService.java

This is a humble contribution for large Ldap directory (over 1000 accounts).

GUACAMOLE-79: Adding an option to allow the default LDAP result size limit (1000) to be overridden

---

.gitignore
doc/guacamole-example/.gitignore
doc/guacamole-example/pom.xml
doc/guacamole-example/src/main/webapp/META-INF/context.xml
doc/guacamole-example/src/main/webapp/index.html
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-dist/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-dist/project-assembly.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml
extensions/guacamole-auth-jdbc/pom.xml
extensions/guacamole-auth-ldap/doc/examples/exampleConfigGroup.ldif
extensions/guacamole-auth-ldap/pom.xml
extensions/guacamole-auth-ldap/schema/guacConfigGroup.ldif
extensions/guacamole-auth-ldap/schema/guacConfigGroup.schema
extensions/guacamole-auth-ldap/src/main/assembly/dist.xml
extensions/guacamole-auth-noauth/doc/example/noauth-config.xml
extensions/guacamole-auth-noauth/pom.xml
extensions/guacamole-auth-noauth/src/main/assembly/dist.xml
guacamole-common-js/pom.xml
guacamole-common-js/static.xml
guacamole-common/pom.xml
guacamole-ext/pom.xml
guacamole/.gitignore
guacamole/doc/example/user-mapping.xml
guacamole/pom.xml
pom.xml
project-assembly.xml

From [GUACAMOLE-119]():
> As revealed by [Apache RAT](https://creadur.apache.org/rat/), several files within the guacamole-client source tree are missing the required headers. The files are too numerous to list here, but suffice to say this should be fixed and RAT should be included as [part of the build](https://creadur.apache.org/rat/apache-rat-plugin/index.html) going forward.
These changes add RAT to the `pom.xml` of all projects within guacamole-client, excluding the following files from checking:
* AngularJS templates (would result in tons of duplicated license comments within the DOM tree)
* JavaScript libraries included in the Guacamole web application (RAT does not recognize their license boilerplate, but `LICENSE` files are included with each, and those *are* recognized)
* JSON …

GUACAMOLE-119: Address RAT build issues

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml

SLF4J is provided within the classpath by the Guacamole webapp. There's no need for it to be bundled within extension .jars.

GUACAMOLE-133: Remove unnecessary bundled SLF4J from JDBC auth.

---

guacamole/pom.xml

Java 6 ships with a reference implementation of StAX. There's no need for it to be transitively bundled.

GUACAMOLE-133: Exclude StAX dependency, which is part of Java 6.

---

guacamole/pom.xml
guacamole/src/licenses/DISCLAIMER
guacamole/src/licenses/LICENSE
guacamole/src/licenses/NOTICE
guacamole/src/licenses/dependencies/activation-1.1/CDDLv1.0.text
guacamole/src/licenses/dependencies/angular-1.3.16/LICENSE
guacamole/src/licenses/dependencies/angular-module-shim-0.0.4/LICENSE
guacamole/src/licenses/dependencies/angular-translate-2.8.0/LICENSE
guacamole/src/licenses/dependencies/aopalliance-1.0/LICENSE
guacamole/src/licenses/dependencies/asm-3.1/LICENSE
guacamole/src/licenses/dependencies/blob-polyfill-1.0.20150320/LICENSE.md
guacamole/src/licenses/dependencies/carlito/LICENSE
guacamole/src/licenses/dependencies/filesaver-1.3.3/LICENSE.md
guacamole/src/licenses/dependencies/guice-3.0/COPYING
guacamole/src/licenses/dependencies/jackson-1.9.2/LICENSE-2.0.txt
guacamole/src/licenses/dependencies/javax.inject-1/LICENSE-2.0.txt
guacamole/src/licenses/dependencies/jaxb-api-2.2.2/License.txt
guacamole/src/licenses/dependencies/jaxb-impl-2.2.3-1/License.txt
guacamole/src/licenses/dependencies/jersey-1.17.1/LICENSE.txt
guacamole/src/licenses/dependencies/jersey-1.17.1/license.html
guacamole/src/licenses/dependencies/jettison-1.1/LICENSE-2.0.txt
guacamole/src/licenses/dependencies/jquery-2.1.3/MIT-LICENSE.txt
guacamole/src/licenses/dependencies/jsr250-api-1.0/CDDLv1.0.txt
guacamole/src/licenses/dependencies/lodash-2.4.1/LICENSE.txt
guacamole/src/licenses/dependencies/logback-1.1.2/LICENSE.txt
guacamole/src/licenses/dependencies/messageformat-1.0.2/LICENSE
guacamole/src/licenses/dependencies/slf4j-api-1.7.7/LICENSE.txt
guacamole/src/licenses/dependencies/webjars-servlet-2.x-1.1/LICENSE

Note that there are **two versions of `LICENSE`**:
1. `LICENSE` (in the top-level directory) which covers the source, and thus describes only the dependencies bundled with the source.
2. `guacamole/src/licenses/LICENSE` which is added to the Guacamole .war file during the build, and describes all dependencies which are bundled with the .war ... of which there are a fair few.
Within each of the above `LICENSE` files, *bundled* dependencies and their licenses are listed is in alphabetical order using the following rough format:
Some Dependency (http://url.for.project/if/known/)
--------------------------------------------------
Version: A.B.C
From: 'Carl P. Wrightholder' (http://url.for.author/if/known)
License(s):
LICENSE1 (guacamole/src/dependencies/some-dependency-A.B.C/License1.txt) …

GUACAMOLE-133: Document all dependencies of Guacamole within LICENSE.

---

project-assembly.xml

Some `.gitignore` files are missing from the source archive, thus the RAT portion of the build is still failing for anything but a git checkout. Without these changes, only the top-level `.gitignore` is present.

GUACAMOLE-132: Include ALL .gitignore in source .tar.gz, not just top-level.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java

The JDBC auth handles resetting of expired passwords within `authenticateUser()`, which doesn't play nicely with secondary authentication factors. The process ends up being:
1. User logs in
2. User is prompted to reset their password
3. User is verified with secondary authentication factors
Which is bad. Presumably the user's identity should be verified *before* allowing them to change their password. By moving the reset process to `getUserContext()`, the ordering of the process is fixed:
1. User logs in
2. User is verified with secondary authentication factors
3. User is prompted to reset their password

GUACAMOLE-136: Handle expired password reset within getUserContext()

---

guacamole/src/main/webapp/app/form/directives/formField.js
guacamole/src/main/webapp/app/form/services/formService.js

Lacking these changes, custom field type controllers cannot rely on their templates being present in the DOM, and things which would normally work for Angular directives fail to work with custom field types.

GUACAMOLE-136: Ensure field template is in DOM prior to invoking controller.

---

guacamole-ext/src/main/java/org/apache/guacamole/language/Translatable.java
guacamole-ext/src/main/java/org/apache/guacamole/language/TranslatableMessage.java
guacamole/src/main/java/org/apache/guacamole/rest/APIError.java
guacamole/src/main/java/org/apache/guacamole/rest/APIException.java
guacamole/src/main/java/org/apache/guacamole/rest/RESTExceptionWrapper.java
guacamole/src/main/java/org/apache/guacamole/rest/history/APIConnectionRecordSortPredicate.java
guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/index/controllers/indexController.js
guacamole/src/main/webapp/app/login/directives/login.js
guacamole/src/main/webapp/app/login/templates/login.html
guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js
guacamole/src/main/webapp/app/manage/controllers/manageSharingProfileController.js
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/notification/services/guacNotification.js
guacamole/src/main/webapp/app/notification/templates/guacNotification.html
guacamole/src/main/webapp/app/notification/types/Notification.js
guacamole/src/main/webapp/app/rest/types/Error.js
guacamole/src/main/webapp/app/rest/types/TranslatableMessage.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsPreferences.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsSessions.js

Extensions are already capable of throwing error messages which are translatable (the error message can be a translation key), but there is no way for substitution/pluralization to occur, and thus no way to include dynamic values within such messages.
This change defines a JSON format and mechanism for throwing translatable error messages from extensions, allowing for substitution of arbitrary values and pluralization within the JavaScript side of the web application.

GUACAMOLE-36: Support fully translatable messages

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledChildDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordContainsUsernameException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordMinimumLengthException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordPolicyException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordPolicyService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordRequiresDigitException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordRequiresMultipleCaseException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordRequiresSymbolException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharingprofile/SharingProfileService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLPasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLPasswordPolicy.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserDirectoryResource.java

This change adds support to the database authentication backend for password policies defined within `guacamole.properties` which control the complexity of passwords allowed for database user accounts.
The restrictions allow for controlling:
1. Minimum password length
2. Required character classes (uppercase/lowercase, digits, symbols, etc.)
3. Whether the password can contain the username
The properties take the form:
```ini
postgresql-user-password-min-length: 8
postgresql-user-password-prohibit-username: true
postgresql-user-password-require-multiple-case: true
postgresql-user-password-require-digit: true
postgresql-user-password-require-symbol: true
mysql-user-password-min-length: 8
mysql-user-password-prohibit-username: true
mysql-user-password-require-multiple-case: true …
```

GUACAMOLE-36: Add support for password policies

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordPolicyService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordTooYoungException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.11.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLPasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.11.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLPasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml

This change adds support for password policies driven by password age, allowing passwords to automatically expire and preventing passwords from being changed too frequently, if desired.

GUACAMOLE-36: Add support for password aging

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordPolicyService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/security/PasswordReusedException.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/PasswordRecordMapper.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/PasswordRecordModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.11.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLPasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/user/PasswordRecordMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.11.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLPasswordPolicy.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/user/PasswordRecordMapper.xml

This change adds optional tracking and past passwords (hashes+salts only), and adds policy options which prevent password reuse.

GUACAMOLE-36: Add support for tracking password history

---

extensions/guacamole-auth-duo/pom.xml
extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-dist/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/pom.xml
extensions/guacamole-auth-ldap/pom.xml
extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json
extensions/guacamole-auth-noauth/pom.xml
extensions/guacamole-auth-noauth/src/main/resources/guac-manifest.json
guacamole-ext/pom.xml
guacamole/pom.xml
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionModule.java
pom.xml

`guacamole-common` and `guacamole-common-js` are unmodified.

GUACAMOLE-154: Bump version numbers to 0.9.11-incubating for modified components.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/002-create-admin-user.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.11.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/002-create-admin-user.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.11.sql

Specifying `DEFAULT CURRENT_TIMESTAMP` for a `DATETIME` column is not supported for MySQL 5.5 and older, breaking compatibility. This change removes `DEFAULT CURRENT_TIMESTAMP` entirely, as it's there purely for convenience. The database auth extension itself always specifies a non-`NULL` value when setting the password.

GUACAMOLE-163: Remove DEFAULT CURRENT_TIMESTAMP from password_date.

---

guacamole-common-js/src/main/webapp/modules/Client.js

This change alters the keep-alive ping of `Guacamole.Client` such that it sends a `nop` instruction rather than a `sync`. If the keep-alive ping occurs prior to receipt of the first frame (no `sync` has been received), then sending the `sync` is a protocol violation. The fact that `currentTimestamp` would be 0 in that case only makes matters worse.

GUACAMOLE-172: Do not send potentially-invalid "sync" as a keep-alive.

---

guacamole-ext/src/main/java/org/apache/guacamole/token/StandardTokens.java
guacamole/src/main/java/org/apache/guacamole/rest/APIRequest.java

These changes allow for the client IP (and/or hostname) to be passed through as parameters to connections, similar to username and password.
I haven't updated any documentation, but it may be necessary given that some configuration changes might be necessary in Tomcat and any proxy servers in front of Tomcat in order to make this work properly.

GUACAMOLE-47: Get client hostname for use in guac RDP session

---

guacamole/src/main/java/org/apache/guacamole/rest/tunnel/StreamResource.java
guacamole/src/main/java/org/apache/guacamole/rest/tunnel/TunnelResource.java

Lacking the `Content-Disposition: attachment` header, IE will attempt mimetype detection for the downloaded file (bad), and will possibly rename the file with the wrong extension (even worse).

GUACAMOLE-129: Set "Content-Disposition: attachment" for "application/octet-stream".

---

guacamole-ext/src/main/java/org/apache/guacamole/net/auth/Credentials.java
guacamole-ext/src/main/java/org/apache/guacamole/token/StandardTokens.java
guacamole/src/main/java/org/apache/guacamole/rest/auth/TokenRESTService.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserResource.java

While documenting the changes made by @necouchman via #109 for [GUACAMOLE-47](https://issues.apache.org/jira/browse/GUACAMOLE-47), I noticed that we are pulling the hostname and address directly from the `HttpServletRequest` each time token substitution takes place. This is bad because servlet containers will often reuse the `HttpServletRequest` object. When pulled from a `Credentials` object, its contents cannot be relied upon outside the scope of the authentication request which produced those `Credentials`.
If these values are to be accessible when users connect via Guacamole, they will need to be stored within `Credentials` just like the username and password.

GUACAMOLE-47: Store remote address/hostname within credentials.

---

guacamole-common-js/src/main/webapp/modules/Layer.js

This change reduces the overall cost of resizing a layer by:
1. Resizing only in 64-pixel increments, relying on the containing `<div>` to clip to the requested size.
2. Performing the full save/restore of image state only if there actually *is* image state to save (resizing a brand new layer is expensive otherwise).

GUACAMOLE-187: Reduce cost of layer resize.

---

guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/client/types/ManagedClient.js
guacamole/src/main/webapp/app/client/types/ManagedClientThumbnail.js
guacamole/src/main/webapp/app/index/services/iconService.js

This change updates the existing client thumbnail roughly every 5 seconds (rather than only upon disconnect), and adds a new `iconService` which facilitates changing the icon of the current tab or restoring the icon back to its default value. Changes to the tab icon are automatically reverted upon navigation.

GUACAMOLE-190: Use client thumbnail for tab icon.

---

guacamole-common-js/src/main/webapp/modules/Display.js
guacamole-common-js/src/main/webapp/modules/Layer.js

Guacamole implements its layers using a `canvas` wrapped in a `div`, with that outer `div` providing the clipping area. There is thus no internal requirement that the `canvas` itself be the same dimensions as the layer it belongs to, and recent changes ([GUACAMOLE-187](https://issues.apache.org/jira/browse/GUACAMOLE-187) via #113) leveraged this to reduce the number of expensive resize operations attempted when a layer is being continuously resized.
Unfortunately, as described in [GUACAMOLE-230](https://issues.apache.org/jira/browse/GUACAMOLE-230):
> The mouse cursor renders extremely small when set via CSS, at least on Chrome. This seems to be due to layer dimensions now rounding up to the nearest multiple of 64. On high-resolution devices, Chrome assumes that 64x64 cursor image must …

GUACAMOLE-230: Provide oncursor event handler with canvas having exact dimensions

---

guacamole-common-js/src/main/webapp/modules/Client.js

This change adds client support for the "mouse" instruction added via apache/incubator-guacamole-server#76.

GUACAMOLE-231: Update software cursor location when a "mouse" instruction is received.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/DereferenceAliases.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/DereferenceAliasesMode.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/DereferenceAliasesProperty.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/UserService.java

This adds the necessary code to allow the user to configure how the LDAP extension behaves with regard to dereferencing aliases.

GUACAMOLE-244: Support configuration of alias dereferencing

---

guacamole/src/main/webapp/app/client/styles/display.css

It seems MS Edge does not always stretch `display: table-cell` elements to fit the vertical space of their `display: table` parents. This seems like a layout bug to me, but I can't find any confirmation from standards one way or the other.
In any case, explicitly specifying `height: 100%` makes things work as expected across the board.

GUACAMOLE-252: Ensure display container is explicitly sized to cover the vertical area of its container.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/UserService.java

Took a stab at implementing two LDAP filter configuration properties for user and connection searches.
This was a very quick stab at implementing it - there are a couple of things that might be worth adding:
- Error checking on the LDAP query - not sure if there's an easy way to parse out the filters to make sure that they're valid before actually running the searches??  The LDAPException should handle this - there are specific messages for filter errors.
- The JIRA issue mentions implementing multiple search bases - this does not do anything with that.

GUACAMOLE-101: Allow Filtering of LDAP Users

---

guacamole/src/main/webapp/app/form/directives/formField.js
guacamole/src/main/webapp/app/form/templates/formField.html

As necessary for clean implementation of #121, as well anything else requiring an SSO-style field which does not render, this change ensures that `<guac-field>` will not actually display if the associated field has no content.

GUACAMOLE-204: Do not display field headers, etc. if the field itself has no content.

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

Part of the body of changes intended to make up [GUACAMOLE-250](https://issues.apache.org/jira/browse/GUACAMOLE-250) (in-browser support for playback of recordings), this change adds a new `Guacamole.Tunnel` implementation, `Guacamole.StaticHTTPTunnel`, which downloads static files via HTTP, parsing the instructions therein as if received over a normal Guacamole connection.
`Guacamole.StaticHTTPTunnel` does not enforce any delay on how quickly those instructions stream through. If code needs the original framerate to be preserved, it is up to that code to enforce such a delay through its own buffering mechanism.

GUACAMOLE-250: Add tunnel implementation which reads static files via HTTP.

---

guacamole-common-js/src/main/webapp/modules/Client.js

The changes merged via #139 contain a bug in that a PNG image is attempted to be generated even for images with zero width or height. Such images contain no associated image data, and cannot be encoded as PNG.

GUACAMOLE-250: Store image URL in client state only if such an image can be generated (non-zero width/height).

---

guacamole-common-js/src/main/webapp/modules/Display.js

Currently, Guacamole will permanently block the display from all further updates if image decoding fails (bad PNG, unsupported image format, etc.). This is potentially bad, as it would cause the connection to become visibly unresponsive.
This shouldn't happen in practice unless something is going horribly wrong within guacd, but it can easily happen when playing back screen recordings if those recordings contain images not supported by the browser handling playback (playing back a recording containing WebP images on Firefox, for example).

GUACAMOLE-250: Unblock image rendering tasks if image decode fails.

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

If a static download of Guacamole protocol data is initiated using `Guacamole.StaticHTTPTunnel`, the web server may always not respond with a proper `Content-Type` header, in which case the browser will assume the content is XML and attempt to parse it as such.
Setting `responseType` to "text" forces the browser to only interpret the response as text, regardless of `Content-Type`, preventing unnecessary XML parsing attempts.

GUACAMOLE-250: Ensure static downloads of Guacamole protocol data are handled as text.

---

guacamole-common-js/src/main/webapp/modules/Client.js

Guacamole's protocol state and display state are asynchronous with respect to each other. A layer or buffer may have been deleted using a ["dispose" instruction](http://guacamole.incubator.apache.org/doc/gug/protocol-reference.html#dispose-instruction), for example, and thus cannot be referenced as far as the protocol is concerned, yet still exist within the display because the display has not yet flushed (it can be blocked by image decoding). This means that the current implementation of `exportState()` will not always function correctly, especially if the browser is decoding images slowly.
This change modifies `exportState()` such that it only returns the state object asynchronously (through invoking a callback), and populates the protocol and display portions of that state when they …

GUACAMOLE-250: Export client state asynchronously

---

guacamole-common/src/main/java/org/apache/guacamole/GuacamoleResourceClosedException.java
guacamole-common/src/main/java/org/apache/guacamole/GuacamoleSessionClosedException.java
guacamole-common/src/main/java/org/apache/guacamole/GuacamoleSessionConflictException.java
guacamole-common/src/main/java/org/apache/guacamole/GuacamoleSessionTimeoutException.java
guacamole-common/src/main/java/org/apache/guacamole/GuacamoleUpstreamNotFoundException.java
guacamole-common/src/main/java/org/apache/guacamole/GuacamoleUpstreamUnavailableException.java

The newly-defined `UPSTREAM_NOT_FOUND`, `UPSTREAM_UNAVAILABLE`, `SESSION_CLOSED`, `SESSION_CONFLICT`, and `SESSION_TIMEOUT` (from #123) are missing corresponding `GuacamoleException` classes. This change defines those.
This change also adds an exception for the old `RESOURCE_CLOSED` status code, which has existed for some time but had no corresponding `GuacamoleException` class.

GUACAMOLE-208: Add exception classes for newly-defined status codes.

---

guacamole-common-js/src/main/webapp/modules/SessionRecording.js

This change adds a new `Guacamole.SessionRecording` object to guacamole-common-js which can be used to play back recordings of Guacamole sessions directly (without requiring that they be translated into video using the guacenc utility). `Guacamole.SessionRecording` is similar in interface to `Guacamole.Client` except that it is read-only and provides support for pausing and seeking within the stream.
Transfer of data is started by calling `connect()` and aborted by calling `disconnect()`. Playback of received frames is initially paused, but can be started by calling `play()` and paused again by calling `pause()`. Current playback position can be changed by calling `seek()`.
As frames are received over the tunnel, an `onprogress` event is fired. Current playback position is reported …

GUACAMOLE-250: Add guacamole-common-js support for in-browser playback of recordings.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/ActiveConnectionRecord.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/FailoverGuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleInstruction.java

This change adds a new object to guacamole-common, `FailoverGuacamoleSocket`, which watches for "error" instructions related to the upstream remote desktop while the Guacamole connection process occurs, and modifies the balancing group behavior of the database auth to use this class where applicable.
If an error is encountered, `FailoverGuacamoleSocket` intercepts that error, rethrowing it as a `GuacamoleUpstreamException` (or subclass). In the case of the database auth, this results in the connection transparently failing over to the next available connection in the group. From the user's perspective, everything just magically works.

GUACAMOLE-267: Take remote desktop errors into account for balancing groups.

---

doc/guacamole-playback-example/.gitignore
doc/guacamole-playback-example/pom.xml
doc/guacamole-playback-example/src/main/webapp/WEB-INF/web.xml
doc/guacamole-playback-example/src/main/webapp/index.html
doc/guacamole-playback-example/src/main/webapp/playback.css
doc/guacamole-playback-example/src/main/webapp/playback.js
pom.xml

This change adds a barebones example project demonstrating use of the new `Guacamole.SessionRecording` and `Guacamole.StaticHTTPTunnel` objects for in-browser playback of recorded sessions.

GUACAMOLE-250: Add example project demonstrating in-browser recording playback.

---

guacamole-common-js/src/main/webapp/modules/Parser.js

I spotted this check of a number against `NaN` that don't seem to be correct. In JavaScript `NaN` is not equal to anything, not even itself. I've fixed this check to use the built in `isNaN` function instead which should correctly check if the variable is `NaN`.
---
I found this issue through [lgtm.com](https://lgtm.com/projects/g/apache/incubator-guacamole-client/alerts/), a service that analyzes open-source code to look for potential problems. (Full disclosure: I work for the company that operates it.)

GUACAMOLE-295: Fix an incorrect comparison with NaN.

---

guacamole/src/main/webapp/app/touch/directives/guacTouchDrag.js

I spotted this line where `deltaY` is strictly compared against false, which should never be true because `deltaY` is a number. I believe the correct behavior is the one expressed on line 153, where the result of the `guacTouchDrag` function is compared against false.
---
I found this issue through [lgtm.com](https://lgtm.com/projects/g/apache/incubator-guacamole-client/alerts/), a service that analyzes open-source code to look for potential problems. (Full disclosure: I work for the company that operates it.)

GUACAMOLE-294: Fix an incorrectly positioned bracket.

---

extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/DuoAuthenticationProvider.java
extensions/guacamole-auth-header/src/main/java/org/apache/guacamole/auth/header/HTTPHeaderAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/InjectedAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/user/SharedUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUserContext.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPAuthenticationProvider.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/UserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/UserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleAuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleUserContext.java
guacamole/src/main/java/org/apache/guacamole/extension/AuthenticationProviderFacade.java
guacamole/src/main/java/org/apache/guacamole/rest/RESTServiceModule.java
guacamole/src/main/java/org/apache/guacamole/rest/extension/ExtensionRESTService.java
guacamole/src/main/java/org/apache/guacamole/rest/extension/package-info.java
guacamole/src/main/java/org/apache/guacamole/rest/session/SessionResource.java
guacamole/src/main/java/org/apache/guacamole/rest/session/UserContextResource.java

This changes adds a `getResource()` function to both `AuthenticationProvider` and `UserContext` which can return an arbitrary REST service annotated with JSR-311 annotations (JAX-RS). The resource returned by `AuthenticationProvider` is available without authenticating with the extension, while the resource returned by `UserContext` implicitly requires authentication (there would be no `UserContext` instance to return it otherwise).

GUACAMOLE-289: Allow extensions to provide their own REST services.

---

guacamole-docker/bin/start.sh

The sanity check which verifies whether a Guacamole Docker container has at least one configured authentication mechanism shouldn't fail if a custom `GUACAMOLE_HOME` is being used.

GUACAMOLE-281: Consider template GUACAMOLE_HOME in Docker image configuration sanity checks.

---

guacamole/src/main/webapp/app/index/controllers/indexController.js

From [GUACAMOLE-301](https://issues.apache.org/jira/browse/GUACAMOLE-301):
>
> The current login screen logic displays the prompt if credentials are requested and clears the prompt once login is successful, but this is partially incorrect. If the user navigates to a page which does not require authentication (such as one exposed by an extension), the login prompt will persist unless the entire interface is reloaded.
>
> Because visiting a page will immediately result in credentials being requested if login is required, the login prompt should simply be cleared upon successful navigation.
>

GUACAMOLE-301: Clear login interface if navigation succeeds.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
guacamole/src/main/webapp/app/form/directives/form.js
guacamole/src/main/webapp/app/form/templates/form.html
guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js
guacamole/src/main/webapp/app/manage/controllers/manageSharingProfileController.js
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/manage/templates/manageConnection.html
guacamole/src/main/webapp/app/manage/templates/manageConnectionGroup.html
guacamole/src/main/webapp/app/manage/templates/manageSharingProfile.html
guacamole/src/main/webapp/app/manage/templates/manageUser.html

Previously, Guacamole users within the database authentication backend could edit any of their own user attributes so long as they had `UPDATE` permission on their own user object. This change modifies this behavior, restricting editing of attributes related to scheduling to users with `ADMINISTER` permission on the user object, and applies that same logic across all object management pages.

GUACAMOLE-292: Restrict editing of attributes based on permissions.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.13.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.13.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml
guacamole-ext/src/main/java/org/apache/guacamole/form/EmailField.java
guacamole-ext/src/main/java/org/apache/guacamole/form/Field.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/User.java
guacamole/src/main/webapp/app/form/directives/form.js
guacamole/src/main/webapp/app/form/services/formService.js
guacamole/src/main/webapp/app/form/templates/emailField.html
guacamole/src/main/webapp/app/manage/styles/attributes.css
guacamole/src/main/webapp/app/manage/styles/connection-parameter.css
guacamole/src/main/webapp/app/navigation/directives/guacUserMenu.js
guacamole/src/main/webapp/app/navigation/navigationModule.js
guacamole/src/main/webapp/app/navigation/styles/user-menu.css
guacamole/src/main/webapp/app/navigation/templates/guacUserMenu.html
guacamole/src/main/webapp/app/rest/types/Field.js
guacamole/src/main/webapp/app/rest/types/User.js
guacamole/src/main/webapp/translations/en.json

This change adds reserved attribute names for each user's full name, email address, organization, and organizational role, exposing those attributes within the user menu if set. A new "EMAIL" field type has been added to allow the definition of attributes which accept only email addresses as values.
The database authentication has been modified to add columns to `guacamole_user` for these attributes, and allows the properties to be set by any user with "UPDATE" permission on the user object.

GUACAMOLE-292: Add base support for user profiles.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java

These changes modify the enforcement of database account restrictions (disabled accounts, scheduling, password expiration) such that they apply even if authentication did not come from the database, so long as [the `mysql-user-required` or `postgresql-user-required` properties](http://guacamole.incubator.apache.org/doc/gug/jdbc-auth.html#jdbc-auth-restrict) are set.

GUACAMOLE-284: Apply database account restrictions when a database account is required.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ModeledConnectionRecord.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.14.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.14.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml
guacamole/src/main/webapp/app/manage/templates/manageConnection.html
guacamole/src/main/webapp/app/rest/types/ConnectionHistoryEntry.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsConnectionHistory.js
guacamole/src/main/webapp/app/settings/templates/settingsConnectionHistory.html
guacamole/src/main/webapp/app/settings/types/ConnectionHistoryEntryWrapper.js
guacamole/src/main/webapp/translations/en.json

This pull request adds the necessary fields and methods to the JDBC module to track the remote host in the connection history table, and to display it in the various history output tables in the client interface.

GUACAMOLE-339: Add Remote Host to Connection History Table

---

doc/guacamole-playback-example/src/main/webapp/index.html
doc/guacamole-playback-example/src/main/webapp/playback.css
doc/guacamole-playback-example/src/main/webapp/playback.js
guacamole-common-js/src/main/webapp/modules/SessionRecording.js

For sufficiently large recordings, the existing implementation of `Guacamole.SessionRecording` can potentially block the main thread to the point that the script appears to have hung. This change modifies `Guacamole.SessionRecording` such that seek operations are performed asynchronously, with completion of the seek reported through a callback.
The playback example has been modified accordingly, providing a notification and cancel button for in-progress seek operations.

GUACAMOLE-346: Avoid blocking main thread when seeking.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/002-create-admin-user.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.10.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.11.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.9.sql

There were two changes necessary to achieve compatibility:
1. Name all indexes. PostgreSQL 8 does not generate names automatically. See: https://www.postgresql.org/docs/8.4/static/sql-createindex.html
2. Replace hex literals with calls to `decode()` PostgreSQL 8 does not provide hex literals (only octal). See: https://www.postgresql.org/docs/8.4/static/datatype-binary.html

GUACAMOLE-345: Modify schema scripts to be compatible with PostgreSQL 8.

---

guacamole/src/main/webapp/app/settings/directives/guacSettingsPreferences.js

This pull request adds a new SimpleUserContext to the CAS extension, instead of returning null, which seems to resolve the issue reported in this JIRA issue with errors trying to access the Settings page in Guacamole.

GUACAMOLE-358: Fix issue with 404 errors from REST API

---

guacamole/src/main/webapp/app/clipboard/services/clipboardService.js
guacamole/src/main/webapp/app/clipboard/styles/clipboard.css

As reported in [GUACAMOLE-310](https://issues.apache.org/jira/browse/GUACAMOLE-310), newlines are being stripped from clipboard data copied using the [W3C Clipboard API](https://www.w3.org/TR/clipboard-apis/). This makes clipboard use cumbersome for users where the browser provides direct integration of the clipboard, such as IE11 or Chrome with the [Clipboard Permission Manager](https://chrome.google.com/webstore/detail/clipboard-permission-mana/ipbhneeanpgkaleihlknhjiaamobkceh) extension.
This is due to newlines being stripped from `textContent` of a `<div>` despite `white-space: pre` being set. As this did indeed work before, this seems to be a recent browser behavior change. By reverting back to using a `<textarea>` the clipboard event target, newlines work as expected.

GUACAMOLE-310: Fix clipboard handling of newlines.

---

guacamole/src/main/webapp/app/clipboard/services/clipboardService.js
guacamole/src/main/webapp/app/index/controllers/indexController.js

Under IE11, the clipboard integration code can use an unusual amount of CPU, to the point of crippling the browser. This is due to a number of factors:
1. Copy/paste within content-editable `<div>` in IE11 is extremely slow (this is partly addressed by #185).
2. Attempts to read/write the clipboard result in events which the Guacamole interface listens on to determine whether to re-read the clipboard, resulting in a never-ending read/write cycle, even though the clipboard is not actually changing.
3. Depending on timing, clipboard read attempts may overlap. Since all read operations share the same event target, this may result in clipboard contents being duplicated (pasted multiple times within the event target prior to reading the event target contents).
This change switches event …

GUACAMOLE-128: Fix clipboard bounce.

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

Some implementations of the HTTP servlet request do not allow a free use of the getInputStream() and getParameter() methods. This is especially annoying in Apache Tomcat >= 7 and Servlet 3.0, where invoking the getParameter() method consumes the InputStream (making later uses of it fail) and consuming the InputStream makes later getParameter() calls fail to find the parameters, as the request body has been consumed.
This causes issues for tunnel servlets that need to access the request parameters, commonly used to pass authentication tokens or additional info provided in the "tunnel.connect()" call, as the tunnel needs later access to the request input stream. Applications using the popular Spring framework may be affected too, since some of its common filters also access the request …

GUACAMOLE-385: Add a convenience filter to cache the contents of HTTP requests

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml

The mapping for the `expired` column of `guacamole_user` is missing in the read direction for MySQL. For reference, see the corresponding PostgreSQL mapping:
https://github.com/apache/incubator-guacamole-client/blob/b90a98946359c9b0b7e4af8571034961d47322fa/extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml#L26-L44
The column is queried in each `SELECT`. The value is simply dropped upon being queried due to that part of the result being unmapped, leaving the `expired` property of each user at the initial value of `false`.

GUACAMOLE-395: Populate "expired" property of Guacamole users defined via MySQL / MariaDB.

---

extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/CASAuthenticationProvider.java
extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/DuoAuthenticationProvider.java
extensions/guacamole-auth-header/src/main/java/org/apache/guacamole/auth/header/HTTPHeaderAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/InjectedAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/user/SharedUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/RemoteAuthenticatedUser.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPAuthenticationProvider.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/UserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractAuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/UserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleAuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleUserContext.java
guacamole/src/main/java/org/apache/guacamole/GuacamoleServletContextListener.java
guacamole/src/main/java/org/apache/guacamole/GuacamoleSession.java
guacamole/src/main/java/org/apache/guacamole/extension/AuthenticationProviderFacade.java

This change modifies the Guacamole extension API, adding the following additional hooks:
Class / Interface        | Function       | Description
------------------------ | -------------- | -----------
`AuthenticationProvider` | `shutdown()`   | The web application is being shut down, and the `AuthenticationProvider` should clean up any resources which will not be automatically freed.
`AuthenticatedUser`      | `invalidate()` | The user associated with the `AuthenticatedUser` is logging out, or their session has been automatically invalidated.
`UserContext`            | `invalidate()` | The user associated with the `UserContext` is logging out, or their session has been automatically invalidated.
Existing extensions have been updated accordingly.

GUACAMOLE-393: Add extension logout/shutdown hooks

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java
guacamole-ext/src/main/java/org/apache/guacamole/token/StandardTokens.java

This change is meant to take the place of the spot fix implemented by #174, automatically pulling the "GUAC_USERNAME" token from the identifier of the `AuthenticatedUser` object if the associated `Credentials` to not have an explicit username set.

GUACAMOLE-341: Automatically pull GUAC_USERNAME token from AuthenticatedUser.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json

Minor tweak to add missing entries for the SQL Server module to the base jdbc en.json file.

GUACAMOLE-416: Add translation entries for SQL Server module.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json

Fix a typo that @mike-jumper caught in the translation file after the last commit.

GUACAMOLE-416: Fix typo in translation file

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/schema/002-create-admin-user.sql

Small PR here to fix issues with the init scripts - apparently got changed but not tested before they were committed the last time.  Oops.
Anyway, apparently SQL Server does not allow you to have semicolons at the end of the "GO" statements (sorry @mike-jumper).  Also missed one GO statement that was needed for a batch operation.

GUACAMOLE-363: Fix issues with schema initialization scripts.

---

extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/ticket/TicketValidationService.java

This PR catches the errors thrown by the CAS module and rethrows them as Guacmaole exceptions, and displays an error message in the login box.

GUACAMOLE-355: Catch CAS Errors and Display Them

---

guacamole-ext/src/main/java/org/apache/guacamole/net/event/AuthenticationSuccessEvent.java
guacamole-ext/src/main/java/org/apache/guacamole/net/event/TunnelCloseEvent.java
guacamole-ext/src/main/java/org/apache/guacamole/net/event/TunnelConnectEvent.java
guacamole-ext/src/main/java/org/apache/guacamole/net/event/UserEvent.java
guacamole/src/main/java/org/apache/guacamole/rest/auth/AuthenticationService.java
guacamole/src/main/java/org/apache/guacamole/tunnel/TunnelRequestService.java

This change refactors `UserEvent` and related classes, representing user identity with `AuthenticatedUser` rather than `UserContext`. The use of `UserContext` to represent identity was a holdover from the pre-0.9.8 days when auth was tied to storage, back before `AuthenticatedUser` existed.
This closes #197.

GUACAMOLE-412: Refactor UserEvent to provide AuthenticatedUser instead of UserContext.

---

extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/PrivateKeyGuacamoleProperty.java

Quick attempt at fixing a resource leak that Coverity identified when reading the private key file.  I think this is still in-scope for 0.9.14-incubating...

GUACAMOLE-362: Fix resource leak in FileInputStream

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

When the tunnel is closed and another `connect()` call is made, it stops
notifying about state changes (`onstatechanges`) if the connection continues
to fail.
Another issue is that the `Tunnel.onerror()` handler is never called the
second time, since it thinks the tunnel is already closed.
The fix is to set the state to `CONNECTING` when calling `connect()`.
I also moved the `setState()` function to the base Tunnel class and used
that whenever a state needs to change in any tunnel implementation, as this
seemed appropriate.

GUACAMOLE-431: Fix Tunnel handling of CLOSED state

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPConnectionService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ReferralAuthHandler.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/UserService.java

This PR fixes the JIRA issue 243, where errors in following referrals block LDAP authentication from succeeding, by allowing referral support to be configured.
This closes #129.

GUACAMOLE-243: Allow LDAP referral following to be configured

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

After the changes in https://github.com/apache/incubator-guacamole-client/pull/210, the `extraHeaders` variable was not visible to the tunnel object in the scope of the add headers function.
This PR fixes that by letting the function receive the headers to add as a parameter (which also makes more sense), and fixes the `StaticHTTPTunnel` that was using the same add headers approach without having it defined.

GUACAMOLE-437: Fix extraHeaders scope and StaticHTTPTunnel

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/schema/001-create-schema.sql
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/schema/002-create-admin-user.sql

Addressing issues discovered during the database portion of development related to [GUACAMOLE-96](https://issues.apache.org/jira/browse/GUACAMOLE-96), this change updates the SQL Server schema, adding missing types, adding indexes necessary for efficient joins on foreign keys, and copying existing formatting and documentation to ensure the various schemas are readily comparable.
Changes overall involved
* Matching the style and documentation of the PostgreSQL and MySQL schemas as much as possible.
* Adding indexes for foreign keys where necessary for efficient joins
* Adding missing `UNIQUE` constraints
* Restoring the `ON DELETE CASCADE` and `ON DELETE SET NULL` functionality that the application depends on (internal failures will occur during object deletion otherwise), in some cases …

GUACAMOLE-363: Bring SQL Sever schema to parity with MySQL/PostgreSQL.

---

extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/form/CASTicketField.java

When attempting to use the CAS extension with a protocol-compliant CAS server, I discovered that when requesting an authentication ticket the URL used by the extension is missing the `/login` URI path defined in the spec.
This PR adds the necessary additional path segment before appending the service name parameter.

GUACAMOLE-457: include CAS login URI when requesting auth ticket

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/schema/001-create-schema.sql

By defining custom types with `NOT NULL`, columns which use those types default to being `NOT NULL` rather that the standard default of being nullable. With recent reformatting of the SQL scripts to match the style of the MySQL / PostgreSQL scripts, this causes inserts to fail for some tables where `NULL` values are meant to be allowed.
The `NOT NULL` qualifier should be removed from the custom types, with the schema instead relying on explicit specification of `NOT NULL` in the column definition.

GUACAMOLE-363: Do not declare custom types as default "NOT NULL".

---

guacamole/src/main/java/org/apache/guacamole/rest/connection/APIConnection.java
guacamole/src/main/java/org/apache/guacamole/rest/history/APIActivityRecord.java
guacamole/src/main/java/org/apache/guacamole/rest/history/APIConnectionRecord.java
guacamole/src/main/java/org/apache/guacamole/rest/history/APISortPredicate.java
guacamole/src/main/java/org/apache/guacamole/rest/history/HistoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/user/APIUser.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserResource.java
guacamole/src/main/webapp/app/rest/types/Connection.js
guacamole/src/main/webapp/app/rest/types/User.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsUsers.js
guacamole/src/main/webapp/app/settings/styles/user-list.css
guacamole/src/main/webapp/app/settings/templates/settingsUsers.html
guacamole/src/main/webapp/translations/de.json
guacamole/src/main/webapp/translations/en.json
guacamole/src/main/webapp/translations/fr.json
guacamole/src/main/webapp/translations/it.json
guacamole/src/main/webapp/translations/nl.json
guacamole/src/main/webapp/translations/no.json
guacamole/src/main/webapp/translations/ru.json

Analogous to the connection history REST endpoint, these changes add a new user history endpoint which lists the start and end times of past user sessions. The user management interface is also updated, exposing the time that each user was last active (if known):

GUACAMOLE-394: Add interface for browsing user access history.

---

guacamole/src/main/webapp/app/rest/services/tunnelService.js
guacamole/src/main/webapp/app/rest/types/UserCredentials.js

Took a stab at locating all of the instances of window.location.origin and fixing this issue to maintain IE10/11 compatibility.  Basically used the fix suggested in the JIRA issue, with the slight modification of using $window.location instead of window.location.

GUACAMOLE-347: Fix issue with IE missing window.location.origin

---

guacamole/src/main/webapp/app/client/controllers/clientController.js

This change implements sending Ctrl-Alt-Del to the remote system by capturing Ctrl-Alt-End, which is a pretty standard hotkey among RDP clients for passing through the three-finger-salute to remote systems.

GUACAMOLE-113: Implement hotkey for sending Ctrl-Alt-Del

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js

This change adds a new private set of boolean flags within `Guacamole.Keyboard` which tracks whether certain platform-specific and browser-specific quirks are present, particularly those which can be reliably detected only through platform/browser-sniffing, specifically:
* Whether keyup events cannot really be relied upon at all (they are randomly dropped on iOS)
* ~Whether the keyup event is specifically unreliable for Caps Lock (a quirk of the Mac OS X event model, as noted by @flangelo in #209: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#Special_cases)~ (removed to be re-added in a separate PR)
* Whether the "Alt" key is safe to allow through to the browser, as it never represents a keyboard shortcut.

GUACAMOLE-232: Handle known platform/browser keyboard quirks semantically.

---

guacamole-ext/src/main/java/org/apache/guacamole/environment/LocalEnvironment.java

Wanted to see how others feel about this feature before spending more time on it. If the concept is agreeable, there's some work to do in updating documentation. Additionally, the start.sh script for the docker container image should probably be revised to take advantage of this feature.
Might also want to consider whether this feature must be enabled by the presence of another environment variable. This would prevent unexpected configuration of extension properties via the environment, with minor additional nuisance factor for using the feature.

GUACAMOLE-464: configuration properties from OS environment

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js

As noted by @flangelo in #209, Caps Lock will only result in keydown events on Mac OS X (keyup events are not dispatched). This change automatically releases Caps Lock immediately after it's pressed if the platform appears to be Mac.

GUACAMOLE-161: Do not rely on receiving keyup for Caps Lock on Mac.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLGuacamoleProperties.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLGuacamoleProperties.java
guacamole/src/main/java/org/apache/guacamole/auth/file/FileAuthenticationProvider.java

This change removes support for the following properties:
* `basic-user-mapping`, which has been deprecated since 0.9.10-incubating (8590a0a)
* `mysql-disallow-*` and `postgresql-disallow-*`, which have been deprecated since 0.9.8 (9b27a27)

GUACAMOLE-494: Remove support for properties which have been deprecated for sufficiently long.

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/ConfigurationService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusConnectionService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusGuacamoleProperties.java

Quick modification to the RADIUS extension to use FileGuacamoleProperty for CA and Key file properties.

GUACAMOLE-197: Use FileGuacamoleProperty for CA and Key file propeties.

---

guacamole/src/main/webapp/index.html

This is a quick tweak suggested by the person who opened -316 in JIRA to correctly preventing Compatibility Mode from kicking in for IE when it is enabled for subnets or certain networks.
Tested with Chrome on Linux and Windows to make sure there were no adverse impacts, there, and then tested on IE11 and Edge in Windows 10.  I don't have compatibility mode enabled across my network, so I don't know that it actually resolves the issue, but it doesn't make things worse.  Will ping back on the JIRA issue and see if I can get the owner to test it for me - unless someone else can give it a try??

GUACAMOLE-316: Tweak to handling IE Compatibility Mode

---

guacamole/src/main/java/org/apache/guacamole/rest/RESTExceptionWrapper.java

This updates the exception handling in the `RESTExceptionWrapper` such that it uses the HTTP Status codes built into the `GuacamoleStatus` class instead of parsing out the `Response.Status` codes manually.

GUACAMOLE-499: Have REST API leverage built-in HTTP Status Codes

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/AuthenticationProviderService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusConnectionService.java

Okay, PR to convert the RADIUS state from a `byte[]` to a hex string to avoid the encoding issues.  Tested with Challenge/Response authentication, and it appears to work.
Not sure if there's anywhere the documentation should be updated, since it still ends up as a `String` - I can throw some language about it being a hex string into the `RadiusStateField` class, if that makes sense.

GUACAMOLE-197: Convert state to Hex string to avoid encoding issues.

---

guacamole/src/main/webapp/app/home/styles/home.css

This PR expands the <a> tag for the connections on the home page such that it can be clicked anywhere that the hover region exists.

GUACAMOLE-304: Expand connection link to encompass entire hover area.

---

guacamole-common/src/main/java/org/apache/guacamole/GuacamoleException.java
guacamole-common/src/main/java/org/apache/guacamole/servlet/GuacamoleHTTPTunnelServlet.java
guacamole-common/src/main/java/org/apache/guacamole/websocket/GuacamoleWebSocketTunnelEndpoint.java
guacamole/src/main/java/org/apache/guacamole/rest/RESTExceptionWrapper.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty8/GuacamoleWebSocketTunnelServlet.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty9/GuacamoleWebSocketTunnelListener.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/tomcat/GuacamoleWebSocketTunnelServlet.java

Adds the getHttpStatusCode() method to the GuacamoleException class, which will allow for exceptions to explicitly override the HTTP status code as required.

GUACAMOLE-504: Add getHttpStatusCode() method to GuacamoleException class

---

guacamole/src/main/webapp/translations/en.json

Typo in translation file from previous commit - quick PR to fix that.

GUACAMOLE-448: Fix typo in translation file.

---

guacamole/src/main/webapp/app/navigation/services/userPageService.js

Took a stab at an implementation of the improvement for 508, taking user to home screen when Settings pages are available.  It's worth noting that the "Preferences" page for users is pretty much always available, so this only does it if there is more than one Settings page available.
Not sure it's the most efficient route...open to suggestions.

GUACAMOLE-508: Take user to home page when Settings pages are available.

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js

The "Print Screen" key is currently assigned to keysym 0xFD1D, which is `XK_3270_PrintScreen` and is technically incorrect. This should instead be 0xFF61 (`XK_Print`).

GUACAMOLE-517: Correct keysym definition of "Print Screen" key.

---

extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/CASAuthenticationProvider.java
extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/DuoAuthenticationProvider.java
extensions/guacamole-auth-header/src/main/java/org/apache/guacamole/auth/header/HTTPHeaderAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/InjectedAuthenticationProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/user/SharedUserContext.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPAuthenticationProvider.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/UserContext.java
extensions/guacamole-auth-openid/src/main/java/org/apache/guacamole/auth/openid/OpenIDAuthenticationProvider.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusAuthenticationProvider.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/TOTPAuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractAuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractUserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleAuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleConnectionDirectory.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleConnectionGroupDirectory.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleDirectory.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleUserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleUserDirectory.java

Note that these changes also involved improving `SimpleDirectory` and, as a result, deprecating the `SimpleConnectionDirectory`, `SimpleUserDirectory`, etc. classes (as the `SimpleDirectory` now accomplishes everything necessary while being cleaner and more generic).

GUACAMOLE-542: Add AbstractUserContext and AbstractAuthenticationProvider base classes.

---

guacamole/pom.xml
guacamole/src/main/webapp/app/auth/authModule.js
guacamole/src/main/webapp/app/auth/service/authenticationService.js
guacamole/src/main/webapp/app/history/historyModule.js
guacamole/src/main/webapp/app/history/services/guacHistory.js
guacamole/src/main/webapp/app/settings/services/preferenceService.js
guacamole/src/main/webapp/app/settings/settingsModule.js
guacamole/src/main/webapp/app/storage/services/localStorageService.js
guacamole/src/main/webapp/index.html

This change:
* Adds a new service, `localStorageService` / `localStorageServiceProvider`, which abstracts away handling of `window.localStorage` such that browser lack of support and lack of permission is handled transparently (falling back to temporary in-memory storage).
* Migrates storage of what used to be the `GUAC_AUTH` cookie to `localStorage` via the `localStorageService`.
* Migrates all previous direct use of `localStorage` (`guacHistory` and `preferenceService`) to `localStorageService`.
* Removes the dependency on "ngCookies" / "angular-cookies", as the webapp no longer makes use of client-side cookies whatsoever.

GUACAMOLE-549: Migrate to localStorage for storage of auth token.

---

guacamole/src/main/java/org/apache/guacamole/rest/auth/TokenRESTService.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserResource.java

If an extension truly needs an `HttpSession`, it should create it manually via the `HttpServletRequest`.

GUACAMOLE-549: Do not automatically create HttpSession.

---

guacamole/src/main/webapp/app/auth/service/authenticationService.js

The changes introduced via #278 incorrectly invalidate the cached auth token after having already updated it with the new auth result. This causes the user to be logged out immediately after logging in if they happen to have a stale auth token.
To reproduce the above:
1. Log into Guacamole and allow the session to expire *OR* manually set `GUAC_AUTH` within `localStorage` to an auth result that contains an old/invalid token.
2. Visit any page within Guacamole. As your token is invalid, the login screen should display.
3. Log in with correct credentials. Though login succeeds, you will be immediately logged out and kicked back to a login screen.
These changes correct the order in which the old token is invalidated and the new token is stored.

GUACAMOLE-526: Invoke logout() for the cached token BEFORE storing new token.

---

guacamole/src/main/webapp/app/client/templates/client.html
guacamole/src/main/webapp/app/form/templates/timeZoneField.html
guacamole/src/main/webapp/app/index/filters/arrayFilter.js
guacamole/src/main/webapp/app/manage/templates/manageConnection.html

The `toArray` filter is necessary wherever `orderBy` is being used to iterate over an object, as iterating over an object is not possible with AngularJS 1.6.x. This filter is already being correctly used for the list of available protocols in the connection edit screen, but is missing from:
1. The list of share links in the Guacamole menu.
2. The timezone field (on the user edit screen for users from the JDBC auth).
These changes add `toArray` to the above locations.
Additionally, as cases like the timezone field require both the key and value of each property to be available, these changes modify the `toArray` filter to produce an array of key/value pairs rather than just an array of values.
Further, to avoid [infdig](https://docs.angularjs.org/error/$rootScope/infdig) due to constantly …

GUACAMOLE-526: Use toArray as necessary for orderBy.

---

guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js
guacamole/src/main/webapp/app/manage/controllers/manageSharingProfileController.js
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/manage/directives/connectionPermissionEditor.js
guacamole/src/main/webapp/app/manage/directives/dataSourceTabs.js
guacamole/src/main/webapp/app/manage/directives/managementButtons.js
guacamole/src/main/webapp/app/manage/directives/systemPermissionEditor.js
guacamole/src/main/webapp/app/manage/templates/connectionPermissionEditor.html
guacamole/src/main/webapp/app/manage/templates/dataSourceTabs.html
guacamole/src/main/webapp/app/manage/templates/manageConnection.html
guacamole/src/main/webapp/app/manage/templates/manageConnectionGroup.html
guacamole/src/main/webapp/app/manage/templates/manageSharingProfile.html
guacamole/src/main/webapp/app/manage/templates/manageUser.html
guacamole/src/main/webapp/app/manage/templates/managementButtons.html
guacamole/src/main/webapp/app/manage/templates/systemPermissionEditor.html
guacamole/src/main/webapp/app/manage/types/ManagementPermissions.js
guacamole/src/main/webapp/app/rest/restModule.js
guacamole/src/main/webapp/app/rest/types/Protocol.js
guacamole/src/main/webapp/translations/en.json

A necessary basis for the user group management interface (which adds yet another management tab), these changes extract the common base code used by the various existing management tabs, which up until now has been largely duplicated.
New directives have been added to take care of data source tabs, permission management, and the save/cancel/clone/delete buttons. The permission test logic driving those buttons and other parts of each management tab has been moved into common class, as well.
This is a net increase in code due to the amount of documentation added, and a massive net decrease in the amount of code within the management controllers.

GUACAMOLE-220: Extract common base for management UI.

---

guacamole/src/main/webapp/app/manage/controllers/manageUserController.js

Redirecting the user back to the user list is handled automatically by the `managementButtons` directive. The other manage controllers were refactored to remove this, but this usage was missed.

GUACAMOLE-220: Rely on managementButtons directive to handle redirect after save.

---

guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/client/directives/guacZoomCtrl.js
guacamole/src/main/webapp/app/client/styles/menu.css
guacamole/src/main/webapp/app/client/templates/client.html

This change allows the zoom level (display scale) to be manually entered in addition to using the -/+ controls in the menu so that additional zoom levels can be reached that aren't currently possible with the 0.10 (10%) scale stepping.
Not sure if this is the right approach or not, but thought I'd give it a try!

GUACAMOLE-152: Allow zoom/scale to be manually entered.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/telnet.json

Add the new terminal-type parameter (apache/guacamole-server#167) to the protocol JSON files.

GUACAMOLE-565: Add terminal-type parameter for SSH and Telnet.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/telnet.json

apache/guacamole-server#132 changes the "color-scheme" parameter to be a configuration string instead of a simple enum, so update the protocol JSON accordingly.

GUACAMOLE-470: Update "color-scheme" parameter for SSH and Telnet.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/telnet.json
guacamole/src/main/webapp/translations/en.json

Follow-up to #288. Add en translations for the terminal-type parameter and its enum values. Also add an empty value to the terminal-type enum lists.

GUACAMOLE-565: Add en translations for terminal-type parameter.

---

guacamole/src/main/webapp/translations/de.json
guacamole/src/main/webapp/translations/en.json
guacamole/src/main/webapp/translations/es.json
guacamole/src/main/webapp/translations/fr.json
guacamole/src/main/webapp/translations/nl.json
guacamole/src/main/webapp/translations/no.json

Follow-up to #289. Remove translations for the "color-scheme" enum values, because the field type is now "TEXT" and not "ENUM" anymore.
Changing the field type to "TEXT" does have the disadvantage of losing localized enum choices. Maybe it would be better to keep "color-scheme" an ENUM, and add a "custom-color-scheme" TEXT field for customized color schemes?

GUACAMOLE-470: Remove translations for "color-scheme" enum values.

---

guacamole/src/main/webapp/app/home/controllers/homeController.js

Quick fix to typo reported on dev mailing list [1].
[1] - http://mail-archives.apache.org/mod_mbox/guacamole-dev/201805.mbox/%3CCAENMeX%3DwCfwNKJy_F%2BVK8E0jpzZkg6OCnbzpqUwSA9jPpUL77Q%40mail.gmail.com%3E

GUACAMOLE-571: Fix rootConnectionGroup typo in homeController.

---

guacamole-docker/bin/start.sh

Simple change that allows the application context to be specified for Guacamole within the Docker image, or defaults to guacamole if not overridden.
Pretty simple, but I believe it works and is reasonably safe??

GUACAMOLE-146: Allow webapp context to be specified in Docker

---

guacamole-ext/src/main/java/org/apache/guacamole/form/TextField.java
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/telnet.json
guacamole/pom.xml
guacamole/src/licenses/LICENSE
guacamole/src/licenses/bundled/datalist-polyfill-1.14.0/LICENSE
guacamole/src/main/webapp/app/form/controllers/selectFieldController.js
guacamole/src/main/webapp/app/form/controllers/textFieldController.js
guacamole/src/main/webapp/app/form/directives/formField.js
guacamole/src/main/webapp/app/form/services/formService.js
guacamole/src/main/webapp/app/form/templates/textField.html
guacamole/src/main/webapp/index.html
guacamole/src/main/webapp/translations/de.json
guacamole/src/main/webapp/translations/en.json
guacamole/src/main/webapp/translations/es.json
guacamole/src/main/webapp/translations/fr.json
guacamole/src/main/webapp/translations/nl.json
guacamole/src/main/webapp/translations/no.json

This change defines option semantics for `TEXT` fields using the [`<datalist>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist), leveraging this to provide the same predefined option values for the `color-scheme` parameter which were removed via #289 and #296.
Browsers vary in how exactly the field is rendered, but generally provide a text field with autocomplete and a drop-down menu of choices:
As not all browsers fully support `<datalist>` (with Safari lacking support entirely), this change also adds https://github.com/mfranzke/datalist-polyfill as a dependency, which is the polyfill recommended by the MDN documentation for `<datalist>`.

GUACAMOLE-470: Provide predefined values for "color-scheme" parameter.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledAuthenticatedUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/RemoteAuthenticatedUser.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/AuthenticationProviderService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/AuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractAuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/Credentials.java
guacamole-ext/src/main/java/org/apache/guacamole/token/StandardTokens.java

1. Add property for reading list of LDAP attributes in guacamole.properties.
2. Add LDAP attribute name and attribute value into credentials object.
3. Add attribute name and attribute value into Tokens from credentials object.

GUACAMOLE-524: Allow custom LDAP attributes to be used as tokens

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/AuthenticationProviderService.java

This PR fixes the issue identified by Coverity for dereferencing a null pointer in the changes introduces in #299.

GUACAMOLE-580: Check for null when retrieving LDAP user attributes

---

guacamole/src/main/webapp/app/form/directives/formField.js

This resolves a dead code issues found by Coverity and also restores the proper functionality for retrieving field options - if the value is not present or empty, the `getFieldOption()` method should have the translation service return the _EMPTY option value rather than bailing out with a null return value.

GUACAMOLE-585: getFieldOption should return EMPTY when value is not present

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/RemoteAuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/Credentials.java
guacamole/src/main/java/org/apache/guacamole/rest/auth/TokenRESTService.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserResource.java

This PR moves the setting of the remote address and remote hostname processing into the `Credentials` class and removes it from the client classes.  This should resolve the issue in GUACAMOLE-540, making determination of remote address more consistent across connection and user objects.

GUACAMOLE-540: Make remote address processing consistent

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/webapp/translations/en.json

This adds the client-side changes that correspond to the changes in guacamole-server to configure the name of the printer passed through in RDP connections.

GUACAMOLE-445: Add client-side changes for configuring RDP Printer Name

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/webapp/translations/en.json

Client-side changes to allow the drive name to be configured when redirecting a filesystem using RDP device redirection.

GUACAMOLE-446: Allow redirected drive name to be configured

---

guacamole/src/main/webapp/app/groupList/directives/guacGroupListFilter.js
guacamole/src/main/webapp/app/index/styles/headers.css
guacamole/src/main/webapp/app/manage/directives/connectionPermissionEditor.js
guacamole/src/main/webapp/app/manage/styles/manage-user.css
guacamole/src/main/webapp/app/manage/templates/connectionPermissionEditor.html
guacamole/src/main/webapp/app/manage/templates/manageUser.html
guacamole/src/main/webapp/app/navigation/directives/guacSectionTabs.js
guacamole/src/main/webapp/app/navigation/styles/tabs.css
guacamole/src/main/webapp/app/navigation/templates/guacSectionTabs.html
guacamole/src/main/webapp/app/settings/styles/settings.css
guacamole/src/main/webapp/app/settings/templates/settings.html
guacamole/src/main/webapp/translations/en.json

In the interest of reducing clutter within the group editor (which has even more sections than the already-somewhat-cluttered user editor), this change splits the "Connections" section into tabs such that the view can be limited to only the connections currently accessible by that user. This reduced view is selected by default for users which have access to at least one connection.
This has the effect that the default view within the editor (1) functions as a report of what the user may currently access and (2) allows direct management of the most relevant permissions:
To grant access to connections, connection groups, etc. which are not already accessible nor nested within already accessible groups, the administrator can switch to the "All Connections" view:
For any user that does not …

GUACAMOLE-220: Display readable connections only by default within permission editor.

---

guacamole/src/main/webapp/app/auth/service/authenticationService.js
guacamole/src/main/webapp/app/groupList/directives/guacGroupList.js
guacamole/src/main/webapp/app/home/controllers/homeController.js
guacamole/src/main/webapp/app/index/controllers/indexController.js
guacamole/src/main/webapp/app/index/styles/fatal-page-error.css
guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js
guacamole/src/main/webapp/app/manage/controllers/manageSharingProfileController.js
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/manage/directives/connectionPermissionEditor.js
guacamole/src/main/webapp/app/manage/directives/systemPermissionEditor.js
guacamole/src/main/webapp/app/navigation/directives/guacUserMenu.js
guacamole/src/main/webapp/app/navigation/services/userPageService.js
guacamole/src/main/webapp/app/rest/services/requestService.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsConnectionHistory.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsConnections.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsPreferences.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsSessions.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsUsers.js
guacamole/src/main/webapp/index.html
guacamole/src/main/webapp/translations/en.json

These changes add a new `requestService.DIE` constant which can be used in favor of `requestService.WARN` if failure of the request in question will result in the page being useless. The various usages of `requestService.WARN` have been updated to `requestService.DIE` where appropriate.
Unlike `requestService.WARN`, which only logs a warning to the browser console, `requestService.DIE` replaces the current page with a generic error:

GUACAMOLE-598: Display fatal error if a page is unusable / nonfunctional.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java

This allows the group membership attribute to be modified for the LDAP authentication module for directories that use a different one than the default of "member".

GUACAMOLE-593: Allow group membership attribute to be configured.

---

guacamole/src/main/java/org/apache/guacamole/extension/AuthenticationProviderFacade.java
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionModule.java

This change adds a new property, `skip-if-unavailable`, which allows specific authentication providers to be skipped in the event of an internal error. In situations where a Guacamole deployment involves multiple authentication providers, administrators can define this property to explicitly allow backend failures  without aborting authentication entirely.
For example, if a deployment is configured to use both LDAP and MySQL, but the network to the MySQL server is known to occasionally go down, the administrator might specify:
```
skip-if-unavailable: mysql
```
to allow LDAP to continue to be used even if connection errors prevent authentication using MySQL. Specifying multiple auth providers is also possible using commas:
```
skip-if-unavailable: mysql, ldap
```
If this property is …

GUACAMOLE-611: Selectively fall through to other extensions when authentication fails

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js
guacamole-common/src/main/java/org/apache/guacamole/websocket/GuacamoleWebSocketTunnelEndpoint.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty8/GuacamoleWebSocketTunnelServlet.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/jetty9/GuacamoleWebSocketTunnelListener.java
guacamole/src/main/java/org/apache/guacamole/tunnel/websocket/tomcat/GuacamoleWebSocketTunnelServlet.java
guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/client/types/ManagedClient.js
guacamole/src/main/webapp/app/client/types/ManagedClientState.js

This change corrects the behavior of the connection instability detection by adding tunnel-specific tests which are independent of the underlying Guacamole connection. Regardless of whether the remote desktop connection itself is returning data, these tests verify that the server side of the tunnel is reachable and responding.
For the WebSocket tunnel, these tests leverage the reserved opcode for tunnel-specific instructions to send a "ping" message which the tunnel is required to respond to. By sending these messages roughly every 500ms, the client side guarantees that there should always be traffic over the tunnel unless something is interrupting that traffic.
For the HTTP tunnel, these tests leverage the fact that HTTP already has a request/response pattern that is verified via the …

GUACAMOLE-567: Add specific connection stability test to tunnel implementations.

---

guacamole/src/main/webapp/app/index/styles/fatal-page-error.css
guacamole/src/main/webapp/index.html

As the fatal error message is selectively hidden using AngularJS, there is a moment before AngularJS has loaded during which the error message may be visible even though no error has occurred.
These changes alter the styling of the error such that it is always hidden by default, even before AngularJS kicks in. This is the same technique used to ensure that a mangled status notification dialog doesn't flash into view while the application is loading.

GUACAMOLE-598: Show fatal error message only after a fatal error has occurred.

---

guacamole-ext/src/main/java/org/apache/guacamole/net/auth/permission/SystemPermission.java
guacamole/src/main/webapp/app/rest/types/PermissionSet.js

The `CREATE_USER_GROUP` system permission was missing from both the `SystemPermission` class (guacamole-ext) and the `PermissionSet` type (JavaScript half of Guacamole webapp). Lacking this definition, management of the `CREATE_USER_GROUP` permission for users or groups fails.

GUACAMOLE-220: Add missing definitions for CREATE_USER_GROUP system permission.

---

guacamole/src/main/java/org/apache/guacamole/rest/activeconnection/ActiveConnectionDirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/connection/ConnectionDirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/connectiongroup/ConnectionGroupDirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/directory/DirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/sharingprofile/SharingProfileDirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserDirectoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/usergroup/UserGroupDirectoryResource.java

This change uses the correct `ObjectPermissionSet` to filter the identifiers of objects listed via REST when permission filtering is requested.
Previous code was always using the `ObjectPermissionSet` returned by `getUserPermissions()`, but this is only correct for user objects and thus was incorrect for all other object types (connections, connection groups, etc.). This bug likely went unnoticed due to minimal use of permission filtering, however it affects the behavior of the admin interface with respect to managing group memberships.

GUACAMOLE-220: Correct handling of permission-filtered directory search.

---

guacamole/src/main/webapp/app/settings/directives/guacSettingsUsers.js
guacamole/src/main/webapp/app/settings/styles/user-list.css
guacamole/src/main/webapp/app/settings/templates/settingsUsers.html
guacamole/src/main/webapp/translations/en.json
guacamole/src/main/webapp/translations/es.json
guacamole/src/main/webapp/translations/zh.json

This change adds two new columns to the user admin interface, "Full name" and "Organization", which display the contents of the standard attributes `guac-full-name` and `guac-organization` respectively. These attributes are also added to the set of filtered attributes, allowing the list of users to be filtered by any of the values displayed.

GUACAMOLE-624: Include user full name and organization in display and filter.

---

guacamole-common-js/src/main/webapp/modules/Client.js

These changes are the guacamole-common-js API changes which complement those of apache/guacamole-server#189.

GUACAMOLE-629: Add support for creating argument value streams using the "argv" instruction.

---

doc/guacamole-example/pom.xml
extensions/guacamole-auth-cas/pom.xml
extensions/guacamole-auth-duo/pom.xml
extensions/guacamole-auth-header/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/pom.xml
extensions/guacamole-auth-ldap/pom.xml
extensions/guacamole-auth-openid/pom.xml
extensions/guacamole-auth-quickconnect/pom.xml
extensions/guacamole-auth-radius/pom.xml
extensions/guacamole-auth-totp/pom.xml
guacamole-ext/pom.xml
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleDirectory.java
guacamole/pom.xml

As discussed on #319 and on [the dev@ mailing list](https://lists.apache.org/thread.html/874edd3a19b0cf0302cbb56f2406f6050cf4296dc31703aa34b30be6@%3Cdev.guacamole.apache.org%3E), this change bumps the Java requirement for all Java components to 1.8, with the exception of guacamole-common which remains at 1.6.
There is one change here that isn't simply bumping "1.6" to "1.8": the addition of the `@SafeVarargs` annotation to the `SimpleDirectory<ObjectType>` constructor that accepts a varargs array of `ObjectType`. This is due to a new warning regarding "heap pollution" introduced in newer Java compilers.
From [Oracle's documentation on heap pollution](https://docs.oracle.com/javase/tutorial/java/generics/nonReifiableVarargsType.html#vulnerabilities):
>
> ...
>
> ## Heap Pollution
>
> _Heap …

GUACAMOLE-635: Require Java 1.8 for all Java components except guacamole-common.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/RemoteAuthenticatedUser.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/AuthenticationProviderService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/user/AuthenticatedUser.java

These changes correct the JDBC and LDAP implementations of `AuthenticatedUser` such that `getAttributes()` and `setAttributes()` follow the definitions of the `Attributes` interface:
* Only attributes which `setAttributes()` will be persisting should be allowed to be set.
* Name/value pairs given to `setAttributes()`, if accepted, should be layered on top of existing attributes. They shouldn't replace the entire attribute map.

GUACAMOLE-524: Correct AuthenticatedUser implementations of Attributes interface.

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js

On iOS, distinct key events are sent for modifier keys, but these key events take the form of empty events with only modifier flags set. The current `Guacamole.Keyboard` implicit key logic seems correct, but a key event which has absolutely no information except modifier flags shouldn't be considered implicit; it's an explicit event for the specific modifiers involved.

GUACAMOLE-232: Mark key as implicitly pressed only when pressed due to another, identifiable key event.

---

extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/TOTPUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingConnection.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingConnectionGroup.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingDirectory.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingSharingProfile.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingUserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingUserGroup.java

When decorating the objects of other extensions, it is frequently necessary to unwrap the decorated object, such as required by `DecoratingDirectory`. These changes add a `protected` method to each of the delegating classes to make this easier and remove the need to repeatedly re-implement storage of the delegate.

GUACAMOLE-96: Add protected convenience method for retrieving delegate object.

---

guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/manage/controllers/manageUserGroupController.js
guacamole/src/main/webapp/app/rest/services/requestService.js

This change addresses a regression in user management due to changes made for user group support.
When attempting to manage a user or group that doesn't exist in the selected datasource, the interface is supposed to reconfigure itself to allow that user or group to be created. This is particularly necessary when combining LDAP and a database, to allow existing LDAP users to be easily copied within the database and associated with database groups or permissions.
Unfortunately, a combination of several changes to error handling and the management interface broke the above functionality, instead showing an internal error if the user/group does not yet exist.

GUACAMOLE-220: Ignore missing user or group when retrieving permissions/memberships.

---

extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/UserVerificationService.java

If a user lacks `UPDATE` permission on their own account, it will be impossible for that user to enroll. In this case, TOTP should simply be disabled for that user.

GUACAMOLE-96: Do not require TOTP for users that cannot enroll.

---

extensions/guacamole-auth-cas/pom.xml
extensions/guacamole-auth-radius/pom.xml

Looks like there are some differing versions of slf4j getting pulled into some of the extension modules by other dependencies, and causing errors to occur when loading the modules.  This adds the explicit dependency to the pom.xml files for the modules exhibiting these issues.

GUACAMOLE-670: Add slf4j logging to CAS and RADIUS modules

---

guacamole/src/main/webapp/app/navigation/directives/guacUserMenu.js

Authentication providers are not required to provide data for the users they authenticate. In this case, the data is needed only to display optional human-readable profile attributes instead of the username. If no such attributes are available, the username is used instead.

GUACAMOLE-598: Ignore if current user has no associated data.

---

guacamole-docker/bin/start.sh

Docker start script did not pass environment variable to set the name of the LDAP member attribute to find group members.

GUACAMOLE-674: added env variable for member attribute

---

Dockerfile
guacamole-docker/bin/build-guacamole.sh
guacamole-docker/bin/start.sh

Extending docker build process to allow passing maven profile to include radius auth.

GUACAMOLE-682: docker build with optional maven profile

---

guacamole-docker/bin/build-guacamole.sh
guacamole-docker/bin/start.sh

This change introduces openid authentication support for the docker build.
Openid is sorted as a first module to make it work together with database. 
The patch was tested together with this commit https://github.com/mike-jumper/guacamole-client/commit/a62a3dcb1125f4bc2dc562016e41df82a3d415db
to make it work against keycloak as openid provider.

GUACAMOLE-683: Add OpenID support in Docker Build Scripts

---

guacamole/util/check-translation.py

This change adds a utility script, `guacamole/util/check-translation.py`, which performs automated comparisons between the JSON files that define Guacamole's translated strings.
By default, strings which are present in English but absent in the translation will be listed (these will need to be added), as well as strings which are present in the translation but not in English (these are likely incorrect and should be removed). These checks can be disabled with command line options, if desired.
An additional duplicate string check can be enabled to test whether strings were incorrectly copied verbatim from English without being translated at all. This check includes some obvious exclusions (empty strings, simple numbers, protocol names, "Apache Guacamole"), but will likely produce false …

GUACAMOLE-699: Add helper script for verifying translations.

---

guacamole-docker/bin/start.sh

JIRA Issue: https://issues.apache.org/jira/browse/GUACAMOLE-704
This will add the ldap-follow-referrals config setting to the start.sh file for Docker if the LDAP_FOLLOW_REFERRALS environment variable is set. I've found that setting this to 'false' is necessary for Guacamole to behave correctly in my Active Directory environment.

GUACAMOLE-704: Add ldap-follow-referrals setting for Docker containers

---

extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/QuickConnectDirectory.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/Connectable.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingConnection.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingConnectionGroup.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleAuthenticationProvider.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleConnection.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleConnectionGroup.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleUserContext.java
guacamole/src/main/java/org/apache/guacamole/net/auth/Connectable.java

[As discussed on dev@](https://lists.apache.org/thread.html/c74221a629bd2da53996b0f6e4cfebc4647ac1239aa8817a45fd0c12@%3Cdev.guacamole.apache.org%3E), these changes modify the `Connectable` interface such that implementations of the previous version of the `connect()` function will continue to work, even if those implementations extended `SimpleConnection` and overrode the old, now-deprecated function. This is achieved through:
1. Continuing to use the old `connect()` as the basis for the implementation.
2. Using a `ThreadLocal` to make the additional `Map<String, String>` parameter available to the old `connect()` within a strict context.
The `SimpleConnection` class and related classes are also modified to provide the same behavior as past releases, particularly for downstream …

GUACAMOLE-524: Update connect() API changes for backward compatibility with 1.0.0.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionGroupPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/SharingProfilePermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserGroupPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionGroupPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/SharingProfilePermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserGroupPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionGroupPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/permission/ConnectionPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/permission/SharingProfilePermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserGroupPermissionMapper.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserPermissionMapper.xml

This should resolve the bug identified in [GUACAMOLE-697](https://issues.apache.org/jira/browse/GUACAMOLE-697) where assigning permissions for a connection to both a user and group results in an error in the web application.  Tested against a PostgreSQL database and it appears to resolve the issue.

GUACAMOLE-697: Add DISTINCT to selectOne permissions queries.

---

guacamole-docker/bin/start.sh

This will add all possible LDAP guacamole.properties settings to the start.sh script for the Docker container. The five that were missing are:
1. ldap-group-name-attribute
2. ldap-dereference-aliases
3. ldap-max-referral-hops
4. ldap-operation-timeout
5. ldap-max-search-results
I also re-formatted some set_optional_property lines that were < 80 characters to be a single line and re-ordered them single-line entries so they match the order in the documentation.

GUACAMOLE-716: Add all LDAP properties to Docker start script

---

guacamole-docker/bin/start.sh

JIRA issue: https://issues.apache.org/jira/browse/GUACAMOLE-713
This change would enable changing the Logback verbosity level using a LOGBACK_LEVEL environment variable passed to Docker using the start.sh script.  Doing this via a guacamole.properties setting would be more elegant, but I'm not familiar enough with the codebase to implement that right now.

 GUACAMOLE-713: Add support for changing Logback verbosity to Docker start script

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ObjectQueryService.java

JIRA Issue: https://issues.apache.org/jira/projects/GUACAMOLE/issues/GUACAMOLE-717
In certain cases, the LDAPSearchResults.next() function returns an LDAPException "Sizelimit Exceeded". In ObjectQueryService.search(), this is not handled within the immediate try/catch block so the other valid results are not returned to the calling function. This fix handles LDAPException the same graceful way that LDAPReferralException is handled.

GUACAMOLE-717: Handle LDAPException gracefully when doing a search

---

guacamole/pom.xml

Brings the logback version up to the latest stable available in Maven repository.

GUACAMOLE-734: Update logback version to latest stable.

---

extensions/guacamole-auth-cas/pom.xml
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/CASGuacamoleProperties.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/ConfigurationService.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/form/CASTicketField.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/ticket/TicketValidationService.java
extensions/guacamole-auth-openid/pom.xml
extensions/guacamole-auth-openid/src/main/java/org/apache/guacamole/auth/openid/conf/ConfigurationService.java
extensions/guacamole-auth-openid/src/main/java/org/apache/guacamole/auth/openid/form/TokenField.java
extensions/guacamole-auth-openid/src/main/java/org/apache/guacamole/auth/openid/token/TokenValidationService.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/URIGuacamoleProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/UriGuacamoleProperty.java

This PR implements a new property type, the `UriGuacamoleProperty`, which parses a string into a URI.  Several of the extensions were converted to use the new property, and I also added properties to the JDBC modules that allow for configuring the connection with a single URI property rather than the individual components.  Providing this type of property allows for validation of URI/URLs in the configuration file, catching errors when the configuration is loaded.
The other advantage of using URI is that, from what I have read, it takes care of all of the encoding of the various URL parts internal, which avoids the need to explicitly use `URLEncoder`.
For the JDBC modules, I configured it such that, if the URI is specified, the other module parameters are completely ignored.  This could …

GUACAMOLE-678: Implement new UriGuacamoleProperty

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java

This pull request allows the JDBC module to create empty users when authentication has succeeded but the user doesn't exist in the database.  This allows group membership to be processed for users authenticated with other modules, where the user does not actually exist in the database.

GUACAMOLE-715: Change how null JDBC users are handled

---

extensions/guacamole-auth-openid/src/main/java/org/apache/guacamole/auth/openid/form/TokenField.java

Fix issue introduced with #349.

GUACAMOLE-678: Assign clientID variable instead of string literal

---

guacamole-docker/bin/start.sh

This fixes an issue where, when the directory specified for the Tomcat WebApp context is already present (for example, ROOT), Tomcat does not actually deploy the application.  This cleans any existing context directory before linking in the WAR and starting Tomcat.

GUACAMOLE-146: Pre-clean the webapp context before deploying it.

---

guacamole/src/main/webapp/translations/cz.json

Hello,
I've just translated the guacamole interface into Czech. If anyone is interested...
https://github.com/Vict0rC/guacamole-client-cz
VictorC

GUACAMOLE-781: Add Czech translation

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/base/EntityMapper.xml

The non-recursive variant of the MySQL/MariaDB `selectEffectiveGroupIdentifiers` query is currently incorrect and will only include user groups that have members explicitly declared within the database, partially ignoring the effective group membership that may be declared by other extensions like LDAP.
This change corrects the above query such that it includes includes each of the following within the results via `UNION`:
* The user groups within the database that explicitly include the current user as a member
* The user groups within the database that explicitly include any of the passed `effectiveGroups` as members
* The user groups within the database that are named identically to the passed `effectiveGroups`

GUACAMOLE-715: Correct non-recursive MySQL/MariaDB effective group membership query.

---

guacamole/src/main/webapp/app/index/config/httpDefaults.js

IE 11 appears to ignore the `Cache-Control` header on requests despite RFC 7234 and does not invalidate cache after changes are made to a resource via PUT/DELETE/POST despite RFC 2616. It _does_ behave correctly when the `Pragma` header is included.
This behavior is not observed for Chrome/Firefox which both correctly honor the `Cache-Control` header and correctly invalidate cache after changes.

GUACAMOLE-783: Ensure GET requests to the REST API are not serviced from the cache in Internet Explorer.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledAuthenticatedUser.java

This pull request overrides the `getEffectiveUserGroups()` method for the `ModeledAuthenticatedUser` class such that the user groups are merged between ones passed in from the provider that authenticated the user and the ones present for the same user within the JDBC module.
I don't know if this is the best way to do this, if it fully resolves all of the issues associated with this particular JIRA issue, or if it introduces any adverse behavior, but my testing indicates that it at least clarifies/resolves the issue reported in GUACAMOLE-696.

GUACAMOLE-696: In JDBC module, merge effective groups

---

guacamole-ext/src/main/java/org/apache/guacamole/form/TimeZoneField.java
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
guacamole/src/main/webapp/app/form/controllers/timeZoneFieldController.js

As discussed on #348, the `TIMEZONE` field can indeed safely be used to represent the `timezone` parameter used by RDP and SSH. This change modifies the field definition added via #403 such that the `TIMEZONE` field type is used instead of `TEXT`, and updates the field type documentation to note the use of IANA identifiers.
This change also removes the `Canada/East-Saskatchewan` time zone, which is no longer available within the IANA database as of release "2017c".

GUACAMOLE-422: Switch to TIMEZONE field type for RDP/SSH "timezone" parameter.

---

guacamole/src/main/webapp/app/form/templates/form.html
guacamole/src/main/webapp/app/login/templates/login.html

Internet Explorer 11 interprets the `disabled` attribute on all HTML elements, even unknown elements like AngularJS directives, disabling any input fields that end up on the DOM tree within those elements. This breaks the login form.
The alternative `data-disabled` attribute form supported by AngularJS allows things to work without interference.

GUACAMOLE-742: Use "data-disabled" instead of "disabled" for directive attributes.

---

extensions/guacamole-auth-openid/src/main/resources/transformToken.js

These changes add more robust handling of the `id_token` parameter. The URL fragment is automatically reformatted from the format used by OpenID to the format used by AngularJS, regardless of the location of `id_token` within that fragment.
The fragment is reformatted from `#...` to `#/?...` if all of the following are true:
1. The fragment did not already start with `#/` (an AngularJS path).
2. The fragment did not already start with `#?` (which AngularJS will already handle as a list of parameters).
3. The fragment contains an `id_token` parameter, either at the beginning or elsewhere within the parameter list.
All other fragments are left untouched.

GUACAMOLE-805: Handle OpenID "id_token" parameter regardless of location in URL fragment.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java

This change addresses a regression introduced with #333.
Parameter tokens are intended to be interpreted by the connections stored within LDAP. This was previously done through explicitly using a `TokenFilter` and the `StandardTokens` class, however usage of `StandardTokens` is now deprecated and the values of tokens to be applied are now expected to be received through `connect()`. Usage of `StandardTokens` was removed from LDAP with commit 1210d56, but this is insufficient. An additional parameter must also be provided to the `SimpleConnection` constructor to enable its automatic token handling behavior.

GUACAMOLE-807: Correct handling of parameter tokens within LDAP.

---

guacamole/src/main/java/org/apache/guacamole/tunnel/TunnelRequestService.java

The changes introduced via #348 include a check of the form:
```java
if (timezone != null & !timezone.isEmpty()) {
...
}
```
This will result in a `NullPointerException` when `timezone` is null, as the `&` ensures `timezone.isEmpty()` will run in all cases. This change corrects the above null check such that proper short-circuit logic is used.

GUACAMOLE-422: Correct non-short-circuit logic in null check.

---

guacamole-common/src/main/java/org/apache/guacamole/protocol/ConfiguredGuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleProtocolCapability.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleProtocolVersion.java
guacamole-common/src/test/java/org/apache/guacamole/protocol/GuacamoleProtocolVersionTest.java

This change migrates from the `GuacamoleProtocolVersion` enum defined via #348 to an identically-named class with static convenience constants. Using a class rather than an enum here allows for unknown, future versions of the Guacamole protocol to be represented and compared internally, even when the version of the API in use does not have a specific constant for those versions.
Following through from there, this change also:
* Adds a `getProtocolVersion()` getter to `ConfiguredGuacamoleSocket` such that the negotiated protocol version can be retrieved by users of that class.
* Adds a unit test for `GuacamoleProtocolVersion` which verifies the parsing, string conversion, and comparison functionality.
* Adds `equals()` to `GuacamoleProtocolVersion` so that users of the class can test for …

GUACAMOLE-422: Allow arbitrary versions of the Guacamole protocol to be represented.

---

guacamole-ext/src/main/java/org/apache/guacamole/form/Field.java
guacamole-ext/src/main/java/org/apache/guacamole/form/LanguageField.java
guacamole/src/main/webapp/app/form/controllers/languageFieldController.js
guacamole/src/main/webapp/app/form/formModule.js
guacamole/src/main/webapp/app/form/services/formService.js
guacamole/src/main/webapp/app/form/templates/languageField.html
guacamole/src/main/webapp/app/settings/directives/guacSettingsPreferences.js
guacamole/src/main/webapp/app/settings/styles/preferences.css
guacamole/src/main/webapp/app/settings/templates/settingsPreferences.html

With the addition of a time zone preference, the current locale preferences section uses two different mechanisms for rendering available fields: a hard-coded table containing, for the language, and a dynamic form leveraging the `guacFormField` directive, for the time zone. This results in both a DOM structure which does not represent the semantics of the section (a single form) and rendering issues (the time zone field spans multiple lines):
This change adds a new `LANGUAGE` field type and leverages that type to migrate to the `guacForm` directive for the whole locale section:

GUACAMOLE-422: Use same display structure/mechanism for all locale preferences.

---

guacamole/src/main/webapp/app/client/styles/connection-select-menu.css
guacamole/src/main/webapp/app/client/styles/guac-menu.css
guacamole/src/main/webapp/app/client/templates/client.html
guacamole/src/main/webapp/app/navigation/styles/menu.css

With the recent changes from #391, the name of the connection within the Guacamole menu can overflow past the edge of the header, covering the share and user menus. These changes correct this, using ellipsis to represent the remaining portion of the connection name if it would otherwise overflow.

GUACAMOLE-723: Allow connection name to overflow cleanly in Guacamole menu.

---

guacamole/src/main/webapp/app/client/styles/connection-select-menu.css

Following up on #414, this change additionally allows the connection names _within_ the connection selection menu to cleanly overflow if they cannot otherwise fit within the menu.
For this to work, the connection selection menu has to have a defined width. I opted for generally wide menu which is still bounded by the Guacamole menu.

GUACAMOLE-723: Allow connection names to cleanly overflow in connection selection menu.

---

guacamole/src/main/webapp/app/client/templates/client.html
guacamole/src/main/webapp/app/navigation/directives/guacMenu.js

This change addresses the menu behavior regression [noted on GUACAMOLE-723](https://issues.apache.org/jira/browse/GUACAMOLE-723?focusedCommentId=16864910&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16864910), automatically closing open menus if the menu contents are clicked or any other part of the page is clicked.
As the connection selection menu is intended to be interactive and thus should remain open while the user is clicking on its contents, a `interactive` attribute has been added to the `guacMenu` directive allow this intent to be explicitly stated. If set to `true`, clicks within the menu contents will not close the menu.

GUACAMOLE-723: Automatically close menus upon click unless explicitly marked as interactive.

---

guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/navigation/services/userPageService.js

This change alters the behavior of the connection selection menu such that it is displayed only if multiple choices would be available within that menu. If only one connection or balancing group is available, the connection selection menu does not render, replaced by a simple `<h2>` header.
Part of this involved adding logic which recursively crawls the connection hierarchy. With that logic being added within `userPageService`, this change effectively addresses the intent of #370. If the user has only one connection or balancing group available, that will automatically be opened as their home page, regardless of how deeply that object is nested or whether there are other empty connection groups present.

GUACAMOLE-723: Display connection selection menu only if multiple connections are available.

---

guacamole/src/main/webapp/app/element/directives/guacFocus.js

Note: There were two parts of this issue this time around. The first(error message) has been fixed and described in the commit itself. As far as the inconsistency in focusing the username field on the initial page load is concerned, that seems to no longer happen as a result of this fix. I do not understand why that is the case, but that is the behavior I have observed. For that reason, I am uncertain whether we can deem that part as resolved.

GUACAMOLE-302: Refocus relevant in-progress login fields after auth failure

---

guacamole/src/main/webapp/app/home/templates/connectionGroup.html

Commit f92bf9c moved the `getClientIdentifier()` function to the `GroupListItem` class, thus making the function available as `item.getClientIdentifier()` within the connection or connection group templates referenced by an instance of the `guacGroupList` directive (see #391). That commit correctly updated all but the connection group template for the home screen, which was _incorrectly_ updated to reference the function as if it were directly on the scope. As such a function doesn't exist, AngularJS didn't substitute any value, resulting in non-functional connection group links.
This change updates the home screen connection group template to retrieve the client identifier using `item.getClientIdentifier()`, as originally intended.

GUACAMOLE-822: Correct retrieval of client identifier for connection groups.

---

guacamole/src/main/webapp/app/element/directives/guacFocus.js

It appears that we cannot rely on `focus()` working as expected unless its execution is deferred via `window.setTimeout()` or equivalent. If not deferred, the target element may not be ready to receive focus, and the attempt will silently fail.
Note that while there is a _chance_ that deferred execution will happen with the current usage of `$evalAsync()` within the `guacFocus` directive, this is not guaranteed. If it can, AngularJS will execute the function provided to `$evalAsync()` immediately after the current `$digest` loop and without control returning to the browser.

GUACAMOLE-302: Do not rely on $evalAsync() for assigning focus.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/webapp/translations/en.json

Please add these changes to code base to add Hunagarian keyboard support to Guacamole.

GUACAMOLE-837: Add RDP keymap for Hungarian keyboard layout

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

This patch will set the `tunnel.uuid` if it's undefined.

GUACAMOLE-846: tunnel.uuid not initialized if tunnel becomes UNSTABLE

---

guacamole/src/main/webapp/translations/ja.json

The names of Guacamole's language options should be in the same language as the translation, not in English. This change updates the name of the Japanese translation such that the name itself is also in Japanese.
I don't speak Japanese at all, but I am reasonably confident this is correct.

GUACAMOLE-821: Use Japanese word for the Japanese language as the name of the Japanese translation.

---

guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/client/templates/client.html
guacamole/src/main/webapp/app/client/types/ManagedArgument.js
guacamole/src/main/webapp/app/client/types/ManagedClient.js

This change leverages apache/guacamole-server#234 to automatically display a subset of connection parameters within the Guacamole menu:
Connection parameters are displayed only if each of the following is true:
1. The current value of the connection parameter was received via an inbound `argv` stream.
2. Creating an outbound `argv` stream for that same parameter resulted in a successful `ack`.
Changes to any parameters are applied once the menu is closed. After any parameter is changed, the above conditions are rechecked.

GUACAMOLE-630: Allow parameters received via "argv" streams to be edited within the Guacamole menu.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/ActiveConnectionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/TrackedActiveConnection.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/ConnectionSharingService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/connection/SharedConnectionDefinition.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/ActiveConnectionRecord.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/ActiveConnection.java
guacamole/src/main/java/org/apache/guacamole/rest/activeconnection/APIActiveConnection.java
guacamole/src/main/java/org/apache/guacamole/tunnel/TunnelRequest.java
guacamole/src/main/java/org/apache/guacamole/tunnel/TunnelRequestService.java
guacamole/src/main/java/org/apache/guacamole/tunnel/TunnelRequestType.java
guacamole/src/main/webapp/app/client/types/ManagedClient.js
guacamole/src/main/webapp/app/navigation/types/ClientIdentifier.js
guacamole/src/main/webapp/app/rest/services/activeConnectionService.js
guacamole/src/main/webapp/app/rest/types/ActiveConnection.js
guacamole/src/main/webapp/app/settings/directives/guacSettingsSessions.js
guacamole/src/main/webapp/app/settings/templates/settingsSessions.html

This change allows users to join active connections where doing so is supported by the extension providing the connection. In the case of the database authentication extensions, this means that users will be able to join their own active connections and administrators will be able to join _any_ active connection, in both cases without share links.
To make use of the support, users will need to navigate to the "Active Sessions" tab of the "Settings" screen. If the user has permission to join an active connection listed there, its name will be rendered as a link and will take the user to a client which joins the active connection once clicked:
The API basis for this change was modifying the `ActiveConnection` interface to additionally extend `Connectable`. The rest of the refactor followed …

GUACAMOLE-360: Add support for joining active connections without share links.

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusAuthenticationProviderModule.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusConnectionService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/conf/ConfigurationService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/conf/RadiusAuthenticationProtocol.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/conf/RadiusAuthenticationProtocolProperty.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/conf/RadiusGuacamoleProperties.java

Takes a stab at manually pulling in the MD4 provider for Java versions that do not include that support, which is required for MSCHAPv1/2 RADIUS conversations.
Full Disclosure: I do not have a RADIUS server running MSCHAP, so I cannot test these changes.  The code compiles, and this seems to be the method that will work based on other changes, but if someone can test against a Windows RADIUS server running MSCHAP, that would be helpful.

GUACAMOLE-774: Add in MD4 support for MSCHAPv1/2

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusAuthenticationProviderModule.java

This is probably not the best solution, but I'm having a hard time finding another.  The only `Provider` constructor present in Java 8 and lower is:
Provider(String name, double version, String info)
In Java 9, that constructor is deprecated, and the recommended one is:
Provider​(String name, String versionStr, String info)
Since the code introduced with that constructor is designed to handle MD4 requirements in *newer* versions of Java, it needs to work with newer versions.  Unless I'm missing some sort of way in Java you can say..."if running with Java version X and earlier, do this, else do this?"

GUACAMOLE-774: Fix deprecation issue with Java 9 and up.

---

extensions/guacamole-auth-radius/src/main/resources/translations/en.json

Got a little too delete-happy removing translation strings - turns out this one should be added back.

GUACAMOLE-769: Add back empty translation string.

---

guacamole/src/main/java/org/apache/guacamole/rest/auth/AuthenticationService.java

This resolves an issue where, depending on the order of stacked authentication modules, `GuacamoleInsufficientCredentialsException`s are overriden by `GuacamoleInvalidCredentialsException`s that occur prior to the insufficient exceptions.  This particular issue has come up with the RADIUS module when it gets a challenge/response and is stacked on top of the JDBC module, where the JDBC authentication occurs (and fails) prior to the RADIUS authentication attempt, and the additional credentials are never requested.

GUACAMOLE-684: Insufficient credentials should take precedence over other failures

---

guacamole/src/main/webapp/app/form/directives/guacInputColor.js
guacamole/src/main/webapp/app/form/services/colorPickerService.js
guacamole/src/main/webapp/app/form/services/formService.js
guacamole/src/main/webapp/app/form/templates/guacInputColor.html

This change adds a new service, `colorPickerService`, which abstracts away a singleton instance of Pickr which is initialized at page startup. The `guacInputColor` directive has been refactored to leverage this service rather than instantiate Pickr itself, thus avoiding lengthy initialization delays multiplied by the number of color fields.
Part of this involved modifying `formService` to only create injectors as necessary. Creating an injector causes services, providers, etc. in the modules of that injector to be initialized, breaking expectations if those modules have actually already been loaded.

GUACAMOLE-630: Use singleton instance of Pickr for all color input fields.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPConnectionService.java

This fixes an issue that occurs when using `try with resources`, because the connection gets automatically closed at the end of the first bind/search, which is undesirable.  As far as I can tell, the alternative to this is to take the code in the `bindAs()` method and replicate it into every method where we do any sort of LDAP operation, which doesn't seem terribly efficient.

GUACAMOLE-234: Fix bind issue that occurs using try-with-resources.

---

guacamole/src/main/webapp/app/index/controllers/indexController.js

Firefox, and perhaps other browsers, does not fire a keyup event for keys involved in submitting a form. This results in the enter key being stuck in a pressed state if it is used to submit Guacamole's login form.
Keyboard state should be reset whenever keyboard state cannot be reliably maintained. This is already done for loss of window focus, but should also be done for form submission (this specific case) and navigation to a different page (generic catch-all).

GUACAMOLE-817: Reset keyboard state on navigation and form submission.

---

extensions/guacamole-auth-ldap/schema/guacConfigGroup.schema

This patch targets the following error message:
`line 30 objectClass: AttributeType not found: "protocol"`

GUACAMOLE-889: Fix mismatching attribute names

---

guacamole-common-js/src/main/webapp/modules/Client.js
guacamole-common-js/src/main/webapp/modules/Display.js
guacamole-common-js/src/main/webapp/modules/Layer.js

Some browsers suffer from a memory leak when reading image data repeatedly using the `Image` object. Reading from `Blob` objects does not exhibit the same behavior. While reading from `Blob` objects has previously been seen to perform poorly compared to data URIs, this was observed when reading using `createObjectURL()`. The `createImageBitmap()` function appears to perform identically to reading data URIs using `Image`.
This change:
* Updates `drawBlob()` to leverage `createImageBitmap()` where available.
* Adds a new `drawStream()` function to `Guacamole.Display` which automatically selects between reading from the given stream using data URIs or `Blob` objects depending on what the platform best supports.

GUACAMOLE-884: Leverage createImageBitmap() for reading image data where supported.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ObjectQueryService.java

This fixes a regression introduced in GUACAMOLE-234 where undefined attribute values are passed through rather than being checked and changed to wildcards, as was the behavior prior to swapping over to the Apache LDAP API.
I've requested this go into the staging/1.1.0 branch since it is a regression introduced by changes in that branch.

GUACAOMLE-893: Fix regression in LDAP filter with null value

---

guacamole-docker/bin/start.sh

Add support for the following properties to start.sh:
- mysql-user-required
- postgresql-user-required

GUACAMOLE-897: Docker support for restricting authentication to database users only

---

guacamole-common-js/src/main/webapp/modules/AudioRecorder.js

This change uses the `Promise` returned by newer versions of `getUserMedia()` to handle success/failure in retrieving an audio stream, inherently falling back to the old callback form of `getUserMedia()`.

GUACAMOLE-732: Retrieve audio stream via Promise for newer versions of getUserMedia().

---

guacamole/src/main/webapp/app/form/controllers/languageFieldController.js

As noted on #453, a `[$rootScope:infdig]` error occurs on recent builds from git which prevents the language selection field from rendering. This is a regression from [GUACAMOLE-630](https://issues.apache.org/jira/browse/GUACAMOLE-630), specifically from commit 93ba19ac26a3509878023886eee0140bcf3face9, which changed the way that the injectors for fields are produced.
This change removes the `$apply()` call entirely, as it is unnecessary. Promises returned by the `$q` and `$http` services, including the promise returned by `languageService.getLanguages()`, will implicitly `$apply()` when needed.
It's not fully clear why this was not a problem before this commit. It may be that the way field injectors were produced in the past somehow did not satisfy the conditions which would normally …

GUACAMOLE-930: Remove unnecessary $scope.$apply().

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/AuthenticationProviderService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPConnectionService.java

Throwing `GuacamoleInvalidCredentialsException` breaks separation of concerns (`bindAs()` shouldn't assume that it's being used during login and that credentials given are the Guacamole user's credentials), and has unintended side effects (throwing subclasses of `GuacamoleUnauthorizedException` causes implicit session invalidation).

GUACAMOLE-937: Return null on bindAs() failures. Rely on caller to interpret and handle failures.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPConnectionService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ObjectQueryService.java

The `LdapNetworkConnection` returned by `getReferralConnection()` was being leaked when following referrals as there is no corresponding `close()` after the `search()` has completed. This change corrects the leak, adding a try-with-resources to ensure it's always closed.
To help make this more verifiable, this change also cleans up the referral logic a bit, adding additional logging and separating the concerns of `getReferralConnection()` from those of `search()`.

GUACAMOLE-936: Ensure LDAP connections for followed referrals are always closed.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLDriver.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLDriverProperty.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLGuacamoleProperties.java

This pull request implements the necessary properties and logic to support both the MySQL JDBC driver and the Maria JDBC driver.  Similar to the way the SQL Server module supports various drivers, it adds a guacamole.properties entry for `mysql-driver` which can have the value either `mysql` or `mariadb`, and calls the necessary JdbcHelper for the configured driver.  The default stays at MySQL.

GUACAMOLE-852: Support either MySQL or MariaDB JDBC drivers

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/AuthenticationProviderService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPConnectionService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ObjectQueryService.java

This change refactors the LDAP connection process such that the same pair of functions are always used for all connections:
* `createLDAPConnection()`, an internal function with several variants that simply constructs a new `LdapNetworkConnection` object having specific parameters set. The resulting object is *not* yet connected.
* `bindAs()`, which binds an `LdapNetworkConnection` using any one of several possible sources of credentials. The Apache Directory API will automatically connect before attempting to bind.
Part of this involved switching over to using `LdapConnectionConfig` internally for specifying the username/password of the bind operation, as the credentials used to bind will not be available for later reuse (such as when following a referral) unless they are associated with …

GUACAMOLE-938: Use same bind/connect process for all LDAP connections, including referrals.

---

guacamole/src/main/java/org/apache/guacamole/rest/APIError.java
guacamole/src/main/webapp/translations/en.json

This change defines a new `APP.TEXT_UNTRANSLATED` string which leverages variable substitution to provide a means of automatically defining strings for otherwise untranslated errors.

GUACAMOLE-955: Provide default translation string for all untranslated messages.

---

guacamole/src/main/webapp/translations/cs.json

GUACAMOLE-781: Translation updated based on latest en.json and filename fixed to cs.json

GUACAMOLE-781: Translation updated, filename fixed

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/webapp/translations/en.json

(See apache/guacamole-server#268)

GUACAMOLE-952: Add RDP parameter value and translation string for Hyper-V / VMConnect security mode.

---

guacamole-docker/bin/build-guacamole.sh
guacamole-docker/bin/start.sh

Hi,
This PR adds TOTP authentication method to the Docker image.
It's really helpful, making TOTP easy to use with Docker.
Let's merge this low-impact PR with #469 in a 1.1.1 Docker image ?
Many thanks 👍

GUACAMOLE-753: Add TOTP auth method to Docker image

---

guacamole-docker/bin/start.sh

Set the ldap-user-attributes if the corresponding LDAP_USER_ATTRIBUTES is set.

GUACAMOLE-987: Set ldap-user-attributes via env variable

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/AuthenticationProviderService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusConnectionService.java

This pull request attempts to fix a couple of minor issues with missing attributes on RADIUS packets, providing the NAS IP address (of the server running Guacamole Client), NAS Type (Virtual), and Client IP address (from authentication request).

GUACAMOLE-1001: Add Client IP and NAS attributes to RADIUS requests.

---

guacamole-ext/src/main/java/org/apache/guacamole/token/TokenFilter.java
guacamole-ext/src/test/java/org/apache/guacamole/token/TokenFilterTest.java

Per the JIRA issue, I've implemented the "upper" and "lower" modifiers for tokens to allow at least case to be converted.  Should be able to expand to fit other modifiers, if required, although case conversion is really the only thing I can think of.

GUACAMOLE-1081: Implement token modifiers for upper and lower case.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/SQLServerAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/SQLServerEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/SQLServerGuacamoleProperties.java

This change adds a configuration option for the instance name for SQL server and sets the correct property in the JDBC driver properties.

GUACAMOLE-583: Add ability to configure SQL Server instance name.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/SQLServerAuthenticationProviderModule.java

Turns out `JDBCHelper` does not use the `instanceName` property directly, so it looks like it needs to be set at the driver level, instead.

GUACAMOLE-583: Correct SQLServer instance name property configuration.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/ActiveConnectionPermissionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/ActiveConnectionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledChildDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledPermissions.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/RelatedObjectSet.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connectiongroup/ConnectionGroupService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/permission/AbstractPermissionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/permission/ModeledObjectPermissionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/permission/SystemPermissionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledAuthenticatedUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUserContext.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/PrivilegedModeledAuthenticatedUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/UserVerificationService.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractUserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingUserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/UserContext.java

To facilitate collaborative storage of arbitrary attributes between extensions, this change adds a new `getPrivileged()` function to the `UserContext` interface, allowing an internal and privileged `UserContext` to be retrieved. As only an extension may invoke this function (it is not called within the REST API), this allows extensions to expose privileged access to other extensions without requiring that users logging into Guacamole via those extensions have the same privileges.
For example, Guacamole's TOTP support has historically required that each user have `UPDATE` privileges on themselves, since the database authentication would otherwise deny the TOTP extension's attempt to store additional attributes for that user. With these changes, the TOTP support uses a privileged …

GUACAMOLE-708: Add API for exposing privileged access to extensions.

---

guacamole/src/main/webapp/app/groupList/templates/guacGroupList.html
guacamole/src/main/webapp/app/groupList/types/GroupListItem.js
guacamole/src/main/webapp/app/home/styles/home.css
guacamole/src/main/webapp/app/home/templates/connection.html
guacamole/src/main/webapp/app/home/templates/connectionGroup.html

Historically, Guacamole has displayed empty balancing groups identically to connections, keeping the balancing nature opaque to users that cannot see the content of the group. This behavior was accidentally removed in 0.9.10-incubating.
This change restores proper rendering of balancing groups by:
* Aligning the HTML structure of connection groups on the home screen with that of connections (see https://github.com/apache/guacamole-client/blob/7db03ba9cb9f4efb6ade04bbaaf913769c4fe219/guacamole/src/main/webapp/app/home/templates/connection.html).
* Adding a connection-style icon for connection groups, which is displayed instead of the expand/collapse icon if a connection group is both balancing and empty.

GUACAMOLE-823: Render empty balancing group as if they were connections.

---

guacamole/src/main/webapp/app/list/types/FilterPattern.js

As noted in [GUACAMOLE-820](https://issues.apache.org/jira/browse/GUACAMOLE-820), Guacamole's current search implementation performs strict matching when searching for IP addresses and subnets. This works well when a property contains _only_ an IP address (like `127.0.0.1`), but fails when matching a property that contains additional text (like `TEST - 127.0.0.1`).
This change modifies the IPv4 and IPv6 network matching mechanism such that any address-like substring is considered, rather than only the entire string. A string like `TEST - 127.0.0.1` will thus match a search for `127.0.0.1`, `127.0.0.0/8`, etc.

GUACAMOLE-820: Match IP address filters against IP addresses anywhere in object properties.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLGuacamoleProperties.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLGuacamoleProperties.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/SQLServerAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/SQLServerInjectorProvider.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerDriver.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerGuacamoleProperties.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerPasswordPolicy.java

As noted in the JIRA issue, it seems like it cold be useful to allow the JDBC module to auto-create users that are logged in successfully with other modules.  This PR introduces the option to enable it (and leaves it disabled by default), along with the creation of those users.
A little unsure if this is desirable behavior, and if this is the best way to go about it, but figured I'd give it a shot :smile:.

GUACAMOLE-708: Enable auto-creation of users in JDBC modules

---

guacamole-docker/bin/start.sh

Looking at the JIRA issue, it was originally entered as a Docker problem, so figured it might be nice to provide the Docker bits consistent with existing Docker functionality.

GUACAMOLE-728: Add Docker support for SSL configuration for MySQL and Postgres

---

extensions/guacamole-auth-saml/src/main/java/org/apache/guacamole/auth/saml/AuthenticationProviderService.java
extensions/guacamole-auth-saml/src/main/java/org/apache/guacamole/auth/saml/SAMLAuthenticationProviderResource.java
extensions/guacamole-auth-saml/src/main/java/org/apache/guacamole/auth/saml/conf/ConfigurationService.java

This change:
* Uses `UriBuilder` for URL construction rather than `String` concatenation, allowing addition of parameters, encoding of values, etc. to be syntax-aware. Adding query parameters to a URL string by concatenating something like `?foo=bar` does not work if the base URL already contains query parameters.
* Preferentially reads the entity ID from the SAML metadata XML, which may be present, relying on `guacamole.properties` only if this value is absent from the XML or the XML is not provided.
* Avoids overriding the ACS URL within the XML with the value from `guacamole.properties` unless the ACS URL is not present.

GUACAMOLE-103: Correct SAML extension construction of URLs.

---

extensions/guacamole-auth-saml/src/main/java/org/apache/guacamole/auth/saml/AuthenticationProviderService.java

The SAML authentication implementation currently contains an incorrect `null` check:
```java
// Grab the username, and, if present, finish authentication.
String username = samlResponse.getNameId().toLowerCase();
if (username != null) {
...
}
```
The intent is clearly to only move forward with using the Name ID as the username if it's present in the response, but that check would need to be performed on the result of `getNameId()` prior to invoking `toLowerCase()`. As-is, the lack of username in the SAML response will produce a `NullPointerException`.

GUACAMOLE-103: Transform username only if present.

---

guacamole/src/main/webapp/app/client/templates/connection.html
guacamole/src/main/webapp/app/client/templates/connectionGroup.html

This change updates the item structure of the Guacamole menu connection browser to match the home screen, correcting a regression in the rendering of empty connection groups.
See: https://issues.apache.org/jira/browse/GUACAMOLE-823?focusedCommentId=17145793&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17145793

GUACAMOLE-823: Update item structure of Guacamole menu connection browser to match home screen.

---

guacamole/src/main/webapp/app/client/controllers/clientController.js

Issue which evidenced starting with guacamole-server version 1.2.0. Send guacSyntheticKeyup (DEL key here) BEFORE deleting it for proper behavior.

GUACAMOLE-1125: Fix substituteKeysPressed handler on guacKeyup events

---

guacamole/src/main/java/org/apache/guacamole/rest/history/ActivityRecordSetResource.java
guacamole/src/main/java/org/apache/guacamole/rest/history/ConnectionHistoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/history/HistoryResource.java
guacamole/src/main/java/org/apache/guacamole/rest/history/UserHistoryResource.java

This change refactors `HistoryResource` such that it leverages a common base representation for all implementations of `ActivityRecordSet`. This allows the history records of any extension API leveraging `ActivityRecordSet` to be exposed in exactly the same filterable, sortable way without duplicating code.

GUACAMOLE-1123: Extract common base REST resources for representing ActivityRecordSets.

---

guacamole-docker/bin/build-guacamole.sh
guacamole-docker/bin/start.sh

Thanks for providing such a useful piece of software!
This pull request adds `guacamole-auth-header` to the `guacamole-client` Docker image.  Please let me know what I need to do to shepherd this pull request through the approval process.
The addition of `guacamole-auth-header` is very useful for folks like me who are running a Dockerized Guacamole instance behind a proxy that authenticates and authorizes with FreeIPA.

GUACAMOLE-857:  Add guacamole-auth-header to Docker image

---

guacamole-docker/bin/build-guacamole.sh
guacamole-docker/bin/start.sh

This branch provides to Docker image use the guacamole-auth-cas  (version 1.1.0).
Thank you very much.

GUACAMOLE-1082: Add guacamole-auth-cas to docker Script

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/PostgreSQLAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLGuacamoleProperties.java
guacamole-docker/bin/start.sh

Pass through environment variables to set `defaultStatementTimeout` and `socketTimeout`. See issue GUACAMOLE-919 for details.
If the TCP connection to the database is silently dropped (not closed), doing a ping query "SELECT 1;" will hang indefinitely. The socketTimeout option will put a timeout on this.
`defaultStatementTimeout` is not relevant to this issue. I thought it might have been at first. I've left this in incase having the option exposed is useful for other reasons.

GUACAMOLE-919: Implement PostgreSQL defaultStatementTimeout and socketTimeout

---

guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js

Fix to pass in the right function to check for connection group permissions. Was originally checking against connection permissions.

GUACAMOLE-1150: Fix for correctly checking connection group permissions.

---

guacamole-docker/bin/start.sh

Hi !
I need to add this variable to my docker-compose file to use my ldap.
So, I think i'm not alone, so I suggest to add it.
Maybe, it will be useful to add other variable like : 
ldap-dereference-aliases
ldap-follow-referrals
ldap-max-referral-hops
ldap-operation-timeout
Thanks for your work !

GUACAMOLE-1147: Add support for additional LDAP properties in Docker container

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLAuthenticationProviderModule.java

The MySQL driver expects locations for TrustStore and ClientStore to be in URI format (file:/path/to/store) - this pushes the URI format into the driverProperties, instead of getAbsolutePath(), which returns without the file:/ schema.

GUACAMOLE-1135: Return StoreUrls in URI format

---

extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/UserVerificationService.java

As described in [GUACAMOLE-1146](https://issues.apache.org/jira/browse/GUACAMOLE-1146), the `totp-period` property is not currently used when generating tokens. Tokens are always generated at the default 30-second interval, with `totp-period` only affecting invalidation of tokens. This is a bug - the configured interval should affect *both* generation and invalidation.
This change properly initializes the TOTP token generator with the configured period such that tokens are generated at the desired interval.

GUACAMOLE-1146: Take configured "totp-period" into account when generating tokens.

---

guacamole-ext/src/main/java/org/apache/guacamole/token/TokenFilter.java

Minor tweak to the token modifier functionality such that the modifiers are "UPPER" and "LOWER" for consistency with the case of the tokens themselves.

GUACAMOLE-1081: Switch token modifiers to upper-case for consistency.

---

guacamole-common-js/src/main/webapp/modules/Client.js
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleProtocolCapability.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleProtocolVersion.java
guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/client/styles/notification.css
guacamole/src/main/webapp/app/client/types/ManagedClient.js
guacamole/src/main/webapp/app/index/controllers/indexController.js
guacamole/src/main/webapp/app/notification/styles/notification.css
guacamole/src/main/webapp/app/notification/templates/guacNotification.html
guacamole/src/main/webapp/app/notification/types/Notification.js
guacamole/src/main/webapp/translations/en.json

This is a re-work of the re-work of the client-side parameter prompting changes proposed with #430. It is the result of building off that absolutely massive effort, re-testing the behavior of those changes, and reworking them with the following changes in approach:
* Prompts are implemented via enhancements to the existing `guacNotification` service, rather than creating a new `guacPrompt` service.
* The UI handling of `required` is separated from the `ManagedClient` handling of `required`, such that interface state is maintained if the user navigates away and back, or switches back and forth between connections.

GUACAMOLE-221: Add support for parameter prompting via "required".

---

extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
extensions/guacamole-auth-cas/src/main/resources/translations/ca.json
extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
extensions/guacamole-auth-duo/src/main/resources/translations/ca.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/ca.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
extensions/guacamole-auth-openid/src/main/resources/guac-manifest.json
extensions/guacamole-auth-openid/src/main/resources/translations/ca.json
extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
extensions/guacamole-auth-quickconnect/src/main/resources/translations/ca.json
extensions/guacamole-auth-radius/src/main/resources/guac-manifest.json
extensions/guacamole-auth-radius/src/main/resources/translations/ca.json
extensions/guacamole-auth-saml/src/main/resources/guac-manifest.json
extensions/guacamole-auth-saml/src/main/resources/translations/ca.json
extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
extensions/guacamole-auth-totp/src/main/resources/translations/ca.json
guacamole/src/main/webapp/translations/ca.json

This branch provides the Catalan translation for the guacamole-client project (version 1.1.0).
Thank you very much.

GUACAMOLE-1078: Add Catalan Language to Guacamole

---

extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
extensions/guacamole-auth-cas/src/main/resources/translations/pt.json
extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
extensions/guacamole-auth-duo/src/main/resources/translations/pt.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/pt.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
extensions/guacamole-auth-openid/src/main/resources/guac-manifest.json
extensions/guacamole-auth-openid/src/main/resources/translations/pt.json
extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
extensions/guacamole-auth-quickconnect/src/main/resources/translations/pt.json
extensions/guacamole-auth-saml/src/main/resources/guac-manifest.json
extensions/guacamole-auth-saml/src/main/resources/translations/pt.json
extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
extensions/guacamole-auth-totp/src/main/resources/translations/pt.json
guacamole/src/main/webapp/translations/pt.json

Add translation files for the webapp and the following extensions:
- guacamole-auth-cas
- guacamole-auth-duo
- guacamole-auth-jdbc
- guacamole-auth-openid
- guacamole-auth-quickconnect
- guacamole-auth-saml
- guacamole-auth-totp

GUACAMOLE-1207: Add Portuguese translation

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
guacamole-common-js/src/main/webapp/modules/Tunnel.js
guacamole-common/pom.xml
guacamole-common/src/main/java/org/apache/guacamole/net/DelegatingGuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/net/GuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/ConfiguredGuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/FailoverGuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/FilteredGuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleConfiguration.java
guacamole/src/main/java/org/apache/guacamole/rest/tunnel/TunnelResource.java
guacamole/src/main/webapp/app/client/types/ManagedClient.js
guacamole/src/main/webapp/app/rest/services/tunnelService.js

Previously, the underlying protocol of an active connection was available only via the connection definition itself. That information is not available if the user is connecting through a connection group or a shared connection, causing handling of the `argv` and `required` instructions to fail in those cases.
These changes establish a REST API endpoint for retrieving underlying protocol unformation from the tunnel, independent of whether a connection, connection group, or shared connection was used. This involved:
* Adding a `onuuid` event to `Guacamole.Tunnel` to allow implementations to reliably wait for assignment of the tunnel UUID.
* Adding a `getProtocol()` function to the `GuacamoleSocket` interface, defaulting to unknown (`null`). This required upgrading the guacamole-common build …

GUACAMOLE-221: Expose underlying protocol at tunnel level.

---

extensions/guacamole-auth-cas/pom.xml
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/AuthenticationProviderService.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/CASGuacamoleProperties.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/ConfigurationService.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/LdapNameGuacamoleProperty.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/group/GroupFormat.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/group/GroupParser.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/group/LDAPGroupParser.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/group/PlainGroupParser.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/ticket/TicketValidationService.java
extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/user/CASAuthenticatedUser.java
extensions/guacamole-auth-cas/src/test/java/org/apache/guacamole/auth/cas/group/LDAPGroupParserTest.java
guacamole-docker/bin/start.sh

This PR builds upon the changes proposed by @doctorfree via #563 (which itself built upon #454 from @siacali), aiming to clean up the LDAP parsing logic such that things are actually LDAP-aware. I did this by:
1. Pulling the changes from #563.
2. Squashing those changes down to a single commit, preserving authorship and the original commit message.
3. Building off of that.
Instead of regex-driven parsing of LDAP DNs, these changes leverage `LdapName` to truly parse each DN. As CAS may also expose multiple effective groups through a `Collection`, these changes also specifically test for this and include each group therein.
I have refactored the configuration properties to reflect this:
* `cas-group-attribute` - The CAS attribute that determines group membership. If omitted, groups aren't …

GUACAMOLE-793: Add support for retrieving effective groups from CAS.

---

extensions/guacamole-auth-json/README.md
extensions/guacamole-auth-json/src/main/java/org/apache/guacamole/auth/json/connection/ConnectionService.java
extensions/guacamole-auth-json/src/main/java/org/apache/guacamole/auth/json/user/UserDataConnection.java

This adds support for parameter tokens in the auth-json plugin.
This feature was already merged and approved on the original guacamole-auth-json project and the (relevant) commits have been ported over.
See: https://github.com/glyptodon/guacamole-auth-json/pull/11
&& https://github.com/apache/guacamole-client/pull/576

GUACAMOLE-1218: auth-json - add support for guacamole paramater tokens

---

guacamole-docker/bin/build-guacamole.sh
guacamole-docker/bin/start.sh

The Docker file is currently missing the auth-json extension & configuration. 
This allows us to enable the extension by defining the $JSON_SECRET_KEY environmental variable

GUACAMOLE-1218: Add auth-json config & extension to docker

---

guacamole-ext/pom.xml

The merge of #576 broke the build due to the addition of the `ByteArrayProperty` class to guacamole-ext. That class depends on JAXB for decoding base64, which is not available out-of-the-box for Java 9 and later.
JAXB is inherently made available within the context of the Guacamole webapp. This change explicitly declares that by listing the JAXB API as a provided dependency of guacamole-ext, thus fixing the build.

GUACAMOLE-1218: Declare availability of JAXB APIs at guacamole-ext level (they are provided by the webapp).

---

guacamole-docker/bin/start.sh

Due to the settings of the OIDC provider, I was forced to set openid-max-token-validity to 24 hours. This was not supported by the start.sh script so I was forced to create a build myself. I think it would be justified for this small patch to go into the script though.

GUACAMOLE-1284: add OPENID_MAX_TOKEN_VALIDITY to start.sh

---

guacamole-docker/bin/build-guacamole.sh

Without `OPENSSL_CONF` explicitly set, the guacamole-common-js portion of the build fails, as PhantomJS (used for the new unit tests) cannot find `libssl_conf.so`:
139677016997504:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
139677016997504:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139677016997504:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139677016997504:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
Feb 12, 2021 5:09:33 AM …

GUACAMOLE-1204: Correct Docker image build failure due to PhantomJS.

---

Dockerfile
guacamole-docker/bin/start.sh

Hi,
This is a rework of #469, and solves https://issues.apache.org/jira/browse/GUACAMOLE-890, allowing Guacamole Docker image to run as non-root user.
Below is why, for now, Guacamole image can't be run as non-root user, and how we solve this.
So first, now, thanks to #553, Docker image is now based on `tomcat:8.5-jdk8`.
Here's below the directory structure from the last `tomcat:8.5-jdk8`  image :
```
total 152
-rw-r--r-- 1 root root 19318 Jun 30 21:53 BUILDING.txt
-rw-r--r-- 1 root root  5408 Jun 30 21:53 CONTRIBUTING.md
-rw-r--r-- 1 root root 57011 Jun 30 21:53 LICENSE
-rw-r--r-- 1 root root  1726 Jun 30 21:53 NOTICE
-rw-r--r-- 1 root root  3255 Jun 30 21:53 README.md
-rw-r--r-- 1 root root  7136 Jun 30 21:53 RELEASE-NOTES
-rw-r--r-- 1 root root 16262 Jun 30 21:53 RUNNING.txt
drwxr-xr-x …
```

GUACAMOLE-890: Security: Allow image to run as non-root user

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/kubernetes.json
guacamole/src/main/webapp/translations/en.json

This change adds the definition and translation for the `exec-command` parameter introduced by apache/guacamole-server#301.

GUACAMOLE-1174: Add definitions and translations for Kubernetes "exec" command parameter.

---

guacamole/src/main/java/org/apache/guacamole/rest/RequestSizeFilter.java

As flagged by Coverity, the private `DEFAULT_MAX_REQUEST_SIZE` constant was erroneously _not_ declared `static`. As a private integer constant, it really should be `static`. It doesn't make sense for a constant to be an instance variable.

GUACAMOLE-1298: Declare default request size limit constant as static.

---

extensions/guacamole-auth-quickconnect/pom.xml
extensions/guacamole-auth-quickconnect/src/licenses/guice-3.0/COPYING
extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/QuickConnectAuthenticationProvider.java
extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/QuickConnectAuthenticationProviderModule.java
extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/QuickConnectDirectory.java
extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/QuickConnectUserContext.java
extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/conf/ConfigurationService.java
extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/rest/QuickConnectREST.java
extensions/guacamole-auth-quickconnect/src/main/java/org/apache/guacamole/auth/quickconnect/utility/QCParser.java
extensions/guacamole-auth-quickconnect/src/test/java/org/apache/guacamole/auth/quickconnect/utility/QCParserTest.java

This implements the necessary bits to allow someone to specify in the guacamole.properties file a list of either explicitly allowed parameters or a list of explicitly denied parameters for the QuickConnect module.  In specifying either or both of these options, an administrator can control what functionality or access end users have access to while still allowing the flexibility of ad-hoc connections.

GUACAMOLE-1025: Allow QuickConnect module to configure allowed and/or denied parameters

---

doc/guacamole-example/pom.xml
doc/guacamole-playback-example/pom.xml
extensions/guacamole-auth-duo/pom.xml
extensions/guacamole-auth-openid/pom.xml
extensions/guacamole-auth-quickconnect/pom.xml
extensions/guacamole-auth-radius/pom.xml
extensions/guacamole-auth-totp/pom.xml
guacamole-common-js/pom.xml
guacamole-common/pom.xml
guacamole-ext/pom.xml
guacamole/pom.xml
pom.xml

This change updates the versions of all Maven plugins to the latest, allowing the build to succeed against newer versions of the JDK. Where reasonable, the version declarations for affected plugins were moved to the main parent `pom.xml`.

GUACAMOLE-1317: Update all Maven plugins to latest.

---

guacamole-docker/README.md
guacamole-docker/bin/start.sh

The specific issue at hand is corrected by the first commit (bdb2ad3), while the remaining commit (fae16c7) cleans up other Docker-related files where this issue occurs only cosmetically.

GUACAMOLE-1316: Remove all unnecessary/incorrect trailing whitespace from Docker-related files.

---

guacamole/src/main/webapp/translations/ca.json
guacamole/src/main/webapp/translations/en.json
guacamole/src/main/webapp/translations/pt.json
guacamole/src/main/webapp/translations/zh.json

Following files had unnessery trailing whitespaces.
guacamole/src/main/webapp/translations/ca.json
guacamole/src/main/webapp/translations/en.json
guacamole/src/main/webapp/translations/pt.json
guacamole/src/main/webapp/translations/zh.json

GUACAMOLE-1337: Remove unnessery trailing whitespaces from guacamole webapp translation files

---

extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
extensions/guacamole-auth-cas/src/main/resources/translations/ko.json
extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
extensions/guacamole-auth-duo/src/main/resources/translations/ko.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/ko.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
extensions/guacamole-auth-openid/src/main/resources/guac-manifest.json
extensions/guacamole-auth-openid/src/main/resources/translations/ko.json
extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
extensions/guacamole-auth-quickconnect/src/main/resources/translations/ko.json
extensions/guacamole-auth-saml/src/main/resources/guac-manifest.json
extensions/guacamole-auth-saml/src/main/resources/translations/ko.json
extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
extensions/guacamole-auth-totp/src/main/resources/translations/ko.json
guacamole/src/main/webapp/translations/ko.json

Add translation files for the webapp and the following extensions:
- guacamole-auth-cas
- guacamole-auth-duo
- guacamole-auth-jdbc
- guacamole-auth-openid
- guacamole-auth-quickconnect
- guacamole-auth-saml
- guacamole-auth-totp

GUACAMOLE-1291: Add Korean language support

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusConnectionService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/conf/ConfigurationService.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/conf/RadiusGuacamoleProperties.java

This change creates the `radius-nas-ip` property, allowing administrators to configure that manually. If the property is not set, it falls back to the functionality present today, which uses `InetAddress.getLocalHost()` to attempt to determine the IP address automatically.

GUACAMOLE-1252: Allow RADIUS NAS IP to be manually configured.

---

doc/guacamole-example/src/main/webapp/index.html
guacamole-common-js/jsdoc-conf.json
guacamole-common-js/src/main/webapp/modules/Event.js
guacamole-common-js/src/main/webapp/modules/Mouse.js
guacamole-common-js/src/main/webapp/modules/Position.js
guacamole/src/main/webapp/app/client/directives/guacClient.js

This change migrates `Guacamole.Mouse` from the old-style `onthing` event handlers:
```javascript
mouse.onmousedown =
mouse.onmouseup   =
mouse.onmousemove = function sendMouseState(state) {
guac.sendMouseState(state);
};
```
to the new event stack:
```javascript
mouse.onEach(['mousedown', 'mouseup', 'mousemove'], function sendMouseEvent(e) {                
guac.sendMouseState(e.state);
});
```
To keep things reasonable for review, I've limited this body of changes to only those necessary to migrate `Guacamole.Mouse`. Other PRs will follow for other eventy parts of the Guacamole JavaScript API. ;)

GUACAMOLE-1204: Migrate Guacamole.Mouse from legacy event handlers to the new event stack.

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/conf/ConfigurationService.java

Quick fix to a potential null de-reference found by Coverity.

GUACAMOLE-1252: Fix potential null dereference getting NAS IP.

---

src/main/assembly/dist.xml

The sizable, auto-generated `node_modules` directory created by NPM during the build needs to be explicitly excluded from the guacamole-client source archive.

GUACAMOLE-773: Exclude node_modules directory from source archive.

---

guacamole/src/main/frontend/webpack.config.js

The on-screen keyboard layouts and AngularJS templates were previously part of the Java webapp build, but are now part of the NPM/Webpack build. Those files were incorrectly left out of the Webpack config, causing the on-screen keyboard and automatic display resize to fail.
Display of the on-screen keyboard fails without these files as it relies on loading the on-screen keyboard layouts dynamically via HTTP. Handling of automatic display resize fails because this relies on a hidden  `<object>` element containing a blank HTML document, with that document served statically over HTTP.

GUACAMOLE-773: Restore missing static template/layout files.

---

extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
extensions/guacamole-auth-header/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
extensions/guacamole-auth-json/src/main/resources/guac-manifest.json
extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json
extensions/guacamole-auth-openid/src/main/resources/guac-manifest.json
guacamole/src/main/java/org/apache/guacamole/extension/Extension.java
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionModule.java
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionOrderProperty.java

Currently, Guacamole extensions are always loaded in order of their filenames, and changing that order requires renaming those files. These changes add a new property, `extension-priority`, that allows the order of extensions to be overridden independently of filenames.
The format of the property is a comma-separated list of extension namespaces, with the special value "*" used to denote any extensions not explicitly listed. This allows the order to be overridden for only those extensions that the administrator decides _must_ be loaded first or last when present. It's not an error for an extension to be listed that isn't actually installed (the property just declares the desired relative order when any of the extensions listed are present), but a warning will be logged if an extension is …

GUACAMOLE-1364: Add support for overriding extension priority without renaming files.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/DynamicallyAuthenticatedDataSource.java

The `DynamicallyAuthenticatedDataSource` introduced via [GUACAMOLE-641](https://issues.apache.org/jira/browse/GUACAMOLE-641) does not correctly set driver-specific JDBC properties like `allowMultiQueries`, resulting in failures for queries that depend on those properties. Additionally, the `PooledDataSource` constructor in use does not initialize internal values used by `PooledDataSource` to verify connections being returned to the pool, resulting in an eternally empty pool and new connections being created for each query.
This change corrects the above by:
1. Adding support for the same named injectable values as mybatis-guice's `PooledDataSourceProvider`.
2. Manually invoking `forceCloseAll()` within the constructor, which will initialize the required internals for `PooledDataSource` …

GUACAMOLE-641: Correct regressions in custom pooled datasource behavior.

---

guacamole/src/main/frontend/src/app/client/types/ManagedClient.js

As of #623, visiting a deployment of the latest `master` fails with the following error in browser devtools:
```
Uncaught Error: Module parse failed: Identifier '$rootScope' has already been declared (41:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const $document               = $injector.get('$document');
|     const $q                      = $injector.get('$q');
>     const $rootScope              = $injector.get('$rootScope');
|     const $window                 = $injector.get('$window');
|     const activeConnectionService = $injector.get('activeConnectionService');
<anonymous> http://localhost:8080/guacamole/guacamole.dc07c6323ec1d94a3644.js:306
g …
```

GUACAMOLE-724: Remove duplicate injection of $rootScope (already injected via parameter).

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-dist/pom.xml
pom.xml

The distribution .tar.gz of the guacamole-auth-jdbc set of extensions should be called `guacamole-auth-jdbc-VERSION.tar.gz`, not `guacamole-auth-jdbc-dist-VERSION.tar.gz`.

GUACAMOLE-1378: Correct naming of guacamole-auth-jdbc dist .tar.gz archive.

---

guacamole/pom.xml
guacamole/src/main/frontend/src/index.html
guacamole/src/main/frontend/src/verifyCachedVersion.js
guacamole/src/main/frontend/webpack.config.js
guacamole/src/main/java/org/apache/guacamole/CacheRevalidationFilter.java
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionModule.java
guacamole/src/main/java/org/apache/guacamole/resource/ResourceServlet.java
guacamole/src/main/webapp/WEB-INF/web.xml
pom.xml

To avoid mismatches between cached and current resources, and to ensure extension JavaScript is automatically kept up-to-date, this change:
* Adds `Cache-Control` and `Pragma` headers to the `app.js`, `app.css`, and `index.html` reponses to ensure browsers will revalidate their cached copies of these resources going forward.
* Adds an automated JavaScript sanity check that compares the version of `app.js` against `index.html` and attempts to refresh the browser's cache if `index.html` is older.

GUACAMOLE-275: Automatically refresh browser cache after extension/application updates.

---

guacamole/src/main/frontend/src/app/client/controllers/clientController.js
guacamole/src/main/frontend/src/app/navigation/types/ClientIdentifier.js

The AngularJS `$location.path()` function unavoidably and automatically URL-encodes all values, so we cannot encode things ahead of time in an attempt to remove special meaning from values. Instead, this change switches over to a URL-safe client identifier format (no `=`, `+`, or `/` characters) while maintaining backward compatibility with the previous format.

GUACAMOLE-1383: Avoid double-encoding client identifiers within URLs.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/group/UserGroupService.java
guacamole-docker/bin/start.sh

This change builds off the proposed changes submitted @echu2013 via #497, additionally addressing the feedback on that PR:
* The default value for the new `ldap-group-search-filter` property should produce backward-compatible behavior when not specified (it should default to `(objectClass=*)`).
* The group search filter should always be taken into account when retrieving user groups (it was erroneously ignored if connections were also being stored in LDAP).
I also went ahead and added a corresponding environment variable for the Docker image.

GUACAMOLE-996: Add support for specifying an LDAP group filter.

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js
guacamole/src/main/frontend/src/layouts/de-de-qwertz.json
guacamole/src/main/frontend/src/layouts/en-us-qwerty.json
guacamole/src/main/frontend/src/layouts/es-es-qwerty.json
guacamole/src/main/frontend/src/layouts/fr-fr-azerty.json
guacamole/src/main/frontend/src/layouts/it-it-qwerty.json
guacamole/src/main/frontend/src/layouts/nl-nl-qwerty.json
guacamole/src/main/frontend/src/layouts/ru-ru-qwerty.json

Guacamole's on-screen keyboard and part of its general keyboard handling incorrectly define "Super" as the "Windows" or "Command" key. This is incorrect. The correct key for the "Windows" key (or the Mac "Command" key) is "Meta".

GUACAMOLE-1386: Correct definitions of "Meta" and "Super" keys.

---

guacamole/src/main/frontend/src/app/client/controllers/clientController.js

The set of visible connections is normally updated when switching to a different group, with all failed/disconnected connections removed from the view during the switch (as the user has seen the status). The logic within `setAttachedGroup()` erroneously applies this filter even if the group is not changing, resulting in all disconnected connections being removed from the view when only a change has been made to the group.
This change corrects the logic of `setAttachedGroup()` such that it performs the tasks associated with changing the attached group only if the group is actually different.

GUACAMOLE-1387: Update and filter tiled connections only if group is actually changing.

---

guacamole/doc/example/user-mapping.xml
guacamole/src/main/java/org/apache/guacamole/auth/file/Authorization.java
guacamole/src/main/java/org/apache/guacamole/auth/file/AuthorizeTagHandler.java

Currently, the `user-mapping.xml` file only supports plain-text or MD5. While it is typically expected that this authentication mechanism is only used for small proof-of-concept deployments, it may still be widely used for smaller deployments, like in a home-lab or small business with a limited IT team.
The changes I'm proposing would add support for the SHA-256 hashing algorithm  to bring the authentication mechanism into the current cryptographic era. MD5 has been broken since near the turn of the century and SHA1 just a few years ago.
https://issues.apache.org/jira/browse/GUACAMOLE-1391

GUACAMOLE-1391: Add support for hashing passwords with SHA-256 in user-mapping.xml

---

guacamole/src/main/java/org/apache/guacamole/auth/file/AuthorizeTagHandler.java

There was a typo in referencing the Enum value.

GUACAMOLE-1391: Correct typo when referencing SHA_256 enum

---

guacamole/src/main/java/org/apache/guacamole/rest/connection/ConnectionResource.java

The sort order of connection history entries should be *descending* (with the most recent connection attempt shown first). This has been incorrect since 1.3.0 due to the migration to the newer, searchable/sortable history structure, which defaults to ascending order.

GUACAMOLE-1366: Correct sort order of connection history entries.

---

guacamole/src/main/frontend/src/app/client/styles/client.css

The CSS rule expanding the guac-tiled-clients directive to fit the viewport was not properly updated when the elements and classes involved were changed via c9900434c443f46429970d1e73c238c3a5382ece. The "tiled-client-list" class was previously used to represent the root element of the set of tiled clients, but that element was replaced with the "guac-tiled-clients" directive.

GUACAMOLE-1398: Explicitly fit guac-tiled-clients directive to available space.

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js

On ChromeOS (and possibly other platforms), the "Meta" key is used as an alternative means of pressing keys that aren't present on the hardware keyboard, like "End" (Meta+Right) or "Home" (Meta+Left). In these cases, the flag representing the Meta key is cleared once it ceases to be a modifier of the key pressed, but if Guacamole has already sent the Meta keypress to the remote desktop, it's too late to undo that keypress. The remote environment incorrectly believes Meta was pressed, resulting in counterintuitive behavior like the Windows "Start" menu opening up.
These changes correct the above behavior by deferring handling of "Meta" keypresses until after its identity has been verified through either (1) an explicit keyup event releasing "Meta" or (2) another key event that acknowledges …

GUACAMOLE-1386: Defer handling of "Meta" key until its identity is verified.

---

guacamole/src/main/frontend/src/app/index/config/indexRouteConfig.js

With the addition of the '*' to the route parameters, the AngularJS router will interpret parameters that include a slash, allowing for user, group, and connection names to contain slashes.

GUACAMOLE-1261: Enable eager interpretation of route parameters for users, groups, and connections.

---

extensions/guacamole-auth-totp/src/main/resources/templates/authenticationCodeField.html

In some cases I start typing the totp code and the input field doesn't have focus. 
So forcing an autofocus is more user friendly.

GUACAMOLE-1397: AUTH-TOTP set autofocus to input field

---

guacamole-ext/src/main/java/org/apache/guacamole/properties/ByteArrayProperty.java

The default decoder from `BaseEncoding.base16()` requires uppercase. There is an option to require lowercase instead, but no option to ignore case entirely.

GUACAMOLE-1218: Allow both lowercase and uppercase for hex values of ByteArrayProperty.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/ConfigurationService.java

If `ldap-servers.yml` is entirely empty (contains purely placeholder content), the current implementation will fail with a `NullPointerException` as valid but empty YAML is parsed by Jackson as `null`. Further, if `ldap-servers.yml` was used but is later deleted by the admin, the old cached version of `ldap-servers.yml` will continue being used.
Instead, if `ldap-servers.yml` is empty or deleted, the LDAP support should move forward as if no `ldap-servers.yml` was provided.

GUACAMOLE-957: Correct handling of empty/deleted ldap-servers.yml.

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/JacksonLDAPConfiguration.java

Clearly, the default value for the search bind password should be the search bind password from the underlying default object ... not the search bind DN.

GUACAMOLE-957: Correct copypasta in retrieval of LDAP search bind password.

---

extensions/guacamole-auth-saml/src/main/java/org/apache/guacamole/auth/saml/user/SAMLAuthenticatedUser.java

`Collectors.toUnmodifiableMap()` is not part of Java 8, thus the build against Java 8 is broken as of #653. This should fix that.

GUACAMOLE-1364: Do not rely on Collectors.toUnmodifiableMap().

---

guacamole/src/main/frontend/src/app/index/controllers/indexController.js

As noted in [GUACAMOLE-680](https://issues.apache.org/jira/browse/GUACAMOLE-680?focusedCommentId=17457554&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17457554), the current behavior of the "Re-login" button can be confusing when logging out to switch accounts, as the URL state prior to logging out is preserved. The typical expectation would be that logging back in will take the user back to the home screen.

GUACAMOLE-680: Navigate user back to home screen upon clicking "re-login".

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/frontend/src/translations/en.json

This change adds the corresponding parameter value and translation for the new keymap added via apache/guacamole-server#342.

GUACAMOLE-1064: Add Norwegian keymap parameter value and translation.

---

guacamole-docker/bin/start.sh

Make api-session-timeout settable in Docker via env var API_SESSION_TIMEOUT

GUACAMOLE-1475: Make api-session-timeout settable via env var

---

guacamole/src/main/frontend/src/app/index/filters/escapeFilter.js
guacamole/src/main/frontend/src/app/settings/templates/settingsConnections.html
guacamole/src/main/frontend/src/app/settings/templates/settingsUserGroups.html
guacamole/src/main/frontend/src/app/settings/templates/settingsUsers.html

This pull request implements an AngularJS filter - `escape` - for escaping special characters in strings that will end up as part of a URL, and then implements the `escape` on the user, group, and connection links so that users and groups that contain special characters will be correctly interpreted, resolving the bug in the associated Jira issue.

GUACAMOLE-1261: Escape strings used to generate URLs for user, groups, and connections.

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/resources/html/sso-providers.html
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/resources/styles/sso-providers.css

The SSO provider list unexpectedly shrinks when the invalid login "shake" animation plays due to the use of `display: table-row` vs. the login form's own use of `display: table-cell`. Migrating the SSO provider list to simple absolute positioning corrects this and matches the way the Guacamole version is rendered.

GUACAMOLE-1364: Correct rendering of SSO provider list during invalid login animation.

---

guacamole-docker/README.md
guacamole-docker/bin/build-guacamole.sh
guacamole-docker/bin/initdb.sh
guacamole-docker/bin/start.sh

Implement SQL Server support in Docker Image.
According to JIRA issue, need to check if it's legally allowed (saw other ASF software are using it so I guess it could be)
Have a good review :)

GUACAMOLE-1418: Add support of SQL Server JDBC plugin in Docker Image

---

guacamole/src/main/frontend/src/app/navigation/services/userPageService.js

This resolves an issue where permissions inherited through groups were not initially factored in to the home page for a user.

GUACAMOLE-1275: Use effective permissions for determining user home page.

---

guacamole-ext/src/main/java/org/apache/guacamole/properties/FileGuacamoleProperties.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/PropertiesGuacamoleProperties.java

As noted in [GUACAMOLE-1511](https://issues.apache.org/jira/browse/GUACAMOLE-1511), whitespace at the end of property values in `guacamole.properties` is a frequently-encountered "gotcha", with any such whitespace invisibly causing failures. This change alters the behavior of `guacamole.properties` such that whitespace at the end of property values no longer has meaning.

GUACAMOLE-1511: Automatically trim whitespace from property values.

---

guacamole-ext/src/main/java/org/apache/guacamole/properties/PropertiesGuacamoleProperties.java

A previous iteration of the whitespace-trimming changes (#688) involved an additional constructor variation. After removing that portion, the original constructor for `PropertiesGuacamoleProperties` was not restored correctly, and now recursively invokes itself.

GUACAMOLE-1511: Revert incorrect recursive constructor invocation.

---

extensions/pom.xml
guacamole/src/main/java/org/apache/guacamole/GuacamoleServletContextListener.java
guacamole/src/main/java/org/apache/guacamole/extension/Extension.java
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionClassLoader.java
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionModule.java

This change adds support for nesting .jar files within extensions, automatically extracting those files to a temporary directory for inclusion within the classpath. The files and directory are deleted automatically upon webapp shutdown or, if that somehow fails, upon JVM exit.
This should also remove the need to exclude metadata from signed .jars, as such libraries will now be able to successfully access and verify themselves.

GUACAMOLE-1508: Add support for nesting .jar files within extensions.

---

guacamole-docker/bin/start.sh

…arameter via environment variable
Enable configuration of of the 'extension-priority' parameter via environment variable.
Details: https://issues.apache.org/jira/browse/GUACAMOLE-1507

GUACAMOLE-1507: Enable Docker configuration of of the 'extension-priority' property

---

guacamole/src/main/frontend/src/app/clipboard/services/clipboardService.js

The clipboard service previously and incorrectly resynced the internal clipboard with itself. This had the effect of forcing a resync of the internal clipboard contents to the external, local clipboard, clearing that clipboard of whatever was copied before.

GUACAMOLE-1523: Resync ONLY local clipboard to internal clipboard.

---

extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmRecordService.java

An SSH server record in KSM has an associated "KeyPair" field, but this field need not be set. If unset, the current logic ignores the rest of the record and assumes there is no private key at all. Instead, the standard fallbacks of locating an attached PEM file, locating an alternative password field, etc. should be used.
Without this change, a PEM file attached to an SSH server record is counter-intuitively ignored despite there being no other key associated with the record.

GUACAMOLE-641: Use "KeyPair" typed field for private key only if non-empty.

---

guacamole-docker/bin/start.sh

Addressing the issue of missing SAML Plugin in Docker Image.
Please include in next release. Thank You!

GUACAMOLE-1322: Include SAML Plugin in Docker Image

---

doc/guacamole-playback-example/src/main/webapp/playback.js
guacamole-common-js/src/main/webapp/modules/SessionRecording.js
guacamole-common-js/src/main/webapp/modules/StringReader.js
guacamole-common-js/src/main/webapp/modules/Tunnel.js
guacamole-common-js/src/main/webapp/modules/UTF8Parser.js

This change adds support for playback of large recordings by:
1. Leveraging the `Blob` object  for storage of the retrieved recording. Unlike strings, which exist purely in memory, the browser will leverage disk storage for `Blob` objects that are too large to fit in memory.
2. Using the Fetch API for HTTP retrieval of recordings. Unlike traditional XHR, the Fetch API allows the HTTP response to be handled as a true stream without building a giant string in memory containing the entire response.

GUACAMOLE-896: Allow playback of session recordings that cannot fit in memory.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/frontend/src/translations/ca.json
guacamole/src/main/frontend/src/translations/cs.json
guacamole/src/main/frontend/src/translations/de.json
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/src/translations/es.json
guacamole/src/main/frontend/src/translations/fr.json
guacamole/src/main/frontend/src/translations/it.json
guacamole/src/main/frontend/src/translations/ko.json
guacamole/src/main/frontend/src/translations/nl.json
guacamole/src/main/frontend/src/translations/no.json
guacamole/src/main/frontend/src/translations/pt.json
guacamole/src/main/frontend/src/translations/zh.json

This PR adds entry for pl-pl-qwerty keymap for RDP in rdp.json and updates all translations files referencing server keyboard layouts with appropriate entry.

GUACAMOLE-1495: Add keymap for Polish keyboard layout for RDP

---

guacamole-common-js/src/main/webapp/modules/SessionRecording.js

This change corrects a logic error that prevented recordings from playing back properly as of the recent addition of large recording support. The instruction buffer was incorrectly compared against the buffer size threshold after the download had completed, resulting in the last block of data being ignored. If the entire recording was approximately `BLOCK_SIZE` or less, then the entire recording would not play.

GUACAMOLE-896: Always flush instruction buffer upon end of static tunnel.

---

guacamole-docker/bin/start.sh

This commit fixes an issue where the Docker init-script won't start if only the auth-json extension is present.

GUACAMOLE-1539: fix docker init logic when only auth-json is configured

---

guacamole-common-js/src/main/webapp/modules/Client.js
guacamole-common-js/src/main/webapp/modules/Display.js
guacamole-common-js/src/main/webapp/modules/SessionRecording.js

The `seek()` function of `Guacamole.SessionRecording` previously caused rendering artifacts under certain circumstances due to two primary issues:
1. The current frame was incorrectly updated to the desired frame, rather than the nearest keyframe, resulting in required instructions being skipped.
2. The state of past seeks and past playback was not fully cleared when a new seek is requested, potentially resulting in a clash of pending instructions and corrupt display state.
This change corrects the above, ensuring seeks always start from the nearest keyframe, replay all instructions required to reach the specific desired frame relative to that keyframe, and always clear out any pending display state from previous seeks/plays.

GUACAMOLE-462: Correct recording playback artifacts during seek().

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

This change corrects the behavior of the `onload` event for session recordings, which should only fire when the recording has finished loading.
Prior to this change, `onload` would fire as soon as the recording started downloading _and_ after the recording finished loading. This is because the tunnel implementation preemptively calls `disconnect()` within `connect()` to ensure any established connection is torn down before initiating a new connection. With the tunnel state (incorrectly) initialized to `CONNECTING`, this resulted in an incorrect `onstatechange` for `CLOSED` at the beginning of all connections.

GUACAMOLE-1545: Ensure tunnel "onload" fires only for true state changes.

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js
guacamole/src/licenses/bundled/glyptodon-enterprise-player/LICENSE
guacamole/src/licenses/bundled/glyptodon-enterprise-player/README
guacamole/src/main/frontend/src/app/index/config/indexRouteConfig.js
guacamole/src/main/frontend/src/app/index/filters/resolveFilter.js
guacamole/src/main/frontend/src/app/player/directives/player.js
guacamole/src/main/frontend/src/app/player/directives/playerDisplay.js
guacamole/src/main/frontend/src/app/player/directives/progressIndicator.js
guacamole/src/main/frontend/src/app/player/playerModule.js
guacamole/src/main/frontend/src/app/player/styles/player.css
guacamole/src/main/frontend/src/app/player/styles/playerDisplay.css
guacamole/src/main/frontend/src/app/player/styles/progressIndicator.css
guacamole/src/main/frontend/src/app/player/styles/seek.css
guacamole/src/main/frontend/src/app/player/templates/player.html
guacamole/src/main/frontend/src/app/player/templates/playerDisplay.html
guacamole/src/main/frontend/src/app/player/templates/progressIndicator.html
guacamole/src/main/frontend/src/app/settings/controllers/connectionHistoryPlayerController.js
guacamole/src/main/frontend/src/app/settings/directives/guacSettingsConnectionHistory.js
guacamole/src/main/frontend/src/app/settings/settingsModule.js
guacamole/src/main/frontend/src/app/settings/styles/history-player.css
guacamole/src/main/frontend/src/app/settings/styles/history.css
guacamole/src/main/frontend/src/app/settings/templates/settingsConnectionHistory.html
guacamole/src/main/frontend/src/app/settings/templates/settingsConnectionHistoryPlayer.html
guacamole/src/main/frontend/src/app/settings/types/ConnectionHistoryEntryWrapper.js
guacamole/src/main/frontend/src/images/action-icons/guac-pause.svg
guacamole/src/main/frontend/src/images/action-icons/guac-play-link.svg
guacamole/src/main/frontend/src/images/action-icons/guac-play.svg
guacamole/src/main/frontend/src/translations/en.json

This change adapts the player implementation from https://github.com/glyptodon/glyptodon-enterprise-player, adding a screen for playing back session recordings stored alongside history records. When an extension provides session recordings for history entries, a link to play back that recording directly and within Apache Guacamole is displayed in the "Logs" column of the history list:
Clicking on the link navigates to a screen with a player that loads the recording and allows it to be played back:
This can be used in practice by:
1. Installing the "guacamole-history-recording-storage" extension (from #698).
2. Configuring a connection for session recording by ...
* ... setting its recording path to `${HISTORY_PATH}/${HISTORY_UUID}` and checking "automatically create path":
* ... or …

GUACAMOLE-462: Add in-app player for session recordings.

---

extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/TOTPUser.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/TOTPUserContext.java
extensions/guacamole-auth-totp/src/main/resources/translations/en.json

The previous functionality provided two checkboxes: one for requesting that the TOTP key be cleared, and another for directly managing whether the TOTP key has been confirmed. This is confusing as checkboxes normally represent state, but the "reset" checkbox here is representing an action:
Instead, both checkboxes should represent state:

GUACAMOLE-1550: Allow TOTP key to be cleared by setting its generation status.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/src/translations/fr.json

Adds FR-CA keyboard layout and its French and English translations
Related to https://github.com/apache/guacamole-server/pull/376

GUACAMOLE-1312: Adds FR-CA keyboard layout

---

guacamole/src/main/frontend/src/app/client/directives/guacClientNotification.js
guacamole/src/main/frontend/src/app/client/directives/guacFileTransfer.js
guacamole/src/main/frontend/src/app/client/services/guacTranslate.js
guacamole/src/main/frontend/src/app/client/templates/guacFileTransfer.html
guacamole/src/main/frontend/src/app/client/types/TranslationResult.js
guacamole/src/main/frontend/src/app/rest/services/tunnelService.js

From https://issues.apache.org/jira/browse/GUACAMOLE-1571:
- JSON-formatted errors received from the server during upload streams are not properly handled, leading to error messages not being displayed to the user
- The list of translatable upload errors is hardcoded in the JS, meaning that translations cannot be supplied for currently untranslated errors by extensions.  (NOTE: the same issue exists for the client notification system)
- In Firefox only, upload streams that are rejected do not contain any response information - the status code is 0 in the XHR, and the response information is blank in the network tab - this is likely related to this issue: https://stackoverflow.com/questions/20210252/status-code-text-and-all-response-headers-are-null-for-an-xhr-that-has-status-c
This PR …

GUACAMOLE-1571: Properly wrap stream errors, and check available translations instead of hardcoding.

---

guacamole-ext/src/main/java/org/apache/guacamole/net/auth/ConnectionRecord.java

As of recent changes from GUACAMOLE-462, extensions built for older Guacamole releases may fail with an `AbstractMethodError` due to the new `getUUID()` function added to the `ActivityRecord` interface. While the new function has a default implementation and therefore should be backward compatible, the `ConnectionRecord` interface redeclares `getUUID()` _without a default implementation_, thus causing the method to become abstract: https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html#extending
This change adds a corresponding default implementation to `ConnectionRecord`.

GUACAMOLE-462: Ensure compatibility with 1.x extensions is maintained.

---

extensions/guacamole-history-recording-storage/src/main/java/org/apache/guacamole/history/connection/HistoryConnectionRecord.java

As noted by Coverity, the potential `null` return from `getUUID()` is not correctly handled within the `HistoryConnectionRecord` wrapper. This change corrects handling of the UUID such that records without corresponding UUIDs are simply ignored.

GUACAMOLE-462: Do not attempt to retrieve recordings for records with null UUIDs.

---

guacamole/src/main/frontend/src/app/settings/directives/guacSettingsConnectionHistory.js

The history screen does not display the correct set of history entries as of recent changes from GUACAMOLE-462. This is because the sort properties of the table in the UI no longer match the sort properties used by the REST API, resulting in only very old records being displayed:
Translating the new properties to the proper REST API properties solves the issue:
The incorrect behavior is only reproducible on a system with more than 1000 history records. On systems with fewer records, the same records will be present in the returned set regardless of how they are sorted.

GUACAMOLE-462: Request correct sort order from REST API when searching history.

---

guacamole/src/main/frontend/src/app/rest/services/patchService.js

As described in https://issues.apache.org/jira/browse/GUACAMOLE-1579, the auth token is not used, and can be safely removed.

GUACAMOLE-1579: Stop including the auth token when making requests to the /api/patches endpoint.

---

extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmRecordService.java

During testing, it was discovered that the fields of a KSM vault record that are initially set to a value and later cleared will be returned as an empty string, not `null`. This change alters the processing of these fields such that both the empty string and `null` are handled equivalently.

GUACAMOLE-641: Ensure empty strings within KSM record fields are handled as if the field value is absent.

---

guacamole-common-js/pom.xml

Per https://github.com/ariya/phantomjs/issues/15344, PhantomJS is not being actively maintained, and should no longer be used if possible.
The newest version of `jasmine-maven-plugin` does just that - using headless versions of Chrome and Firefox to run tests instead. Unfortunate that it's still a beta version, but it seems to be the best option for fixing this problem.

GUACAMOLE-1614: Upgrade to latest jasmine-maven-plugin version to avoid PhantomJS use entirely.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/HistoryTrackingConnection.java

Oops, missed this in the [original change](GUACAMOLE-1616). Adding the `HISTORY_UUID` field doesn't do much if I never actually send the updated tokens along.

GUACAMOLE-1616: Send updated tokens after adding HISTORY_UUID.

---

extensions/guacamole-vault/modules/guacamole-vault-base/pom.xml
extensions/guacamole-vault/modules/guacamole-vault-base/src/main/java/org/apache/guacamole/vault/conf/VaultConfigurationService.java
extensions/guacamole-vault/modules/guacamole-vault-base/src/main/java/org/apache/guacamole/vault/secret/WindowsUsername.java
extensions/guacamole-vault/modules/guacamole-vault-base/src/test/java/org/apache/guacamole/vault/secret/WindowsUsernameTest.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/conf/KsmConfigurationService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmClient.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmRecordService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmSecretService.java

As discussed in https://issues.apache.org/jira/browse/GUACAMOLE-1623, this allows the KSM vault extension to 
* read a domain token out of records in the vault directly, 
* or to split the username field into domain and username tokens if no domain is directly defined, if the username matches the expected formats as seen at https://docs.microsoft.com/en-us/windows/win32/secauthn/user-name-formats#user-principal-name, and if the configuration property is enabled.

GUACAMOLE-1623: Extract domain field directly from the vault, or split out of username.

---

extensions/guacamole-vault/modules/guacamole-vault-base/src/test/java/org/apache/guacamole/vault/secret/WindowsUsernameTest.java

Oops, my [previous PR for GUACAMOLE-1623](https://github.com/apache/guacamole-client/pull/736) had a java 9+ only initializer (`List.of`).
This PR changes it to use the Java 8 compatible `Arrays.listOf` initializer.

GUACAMOLE-1623: Use Java 8 List initializer to fix Java 8 build.

---

extensions/guacamole-vault/modules/guacamole-vault-base/src/main/java/org/apache/guacamole/vault/user/VaultDirectoryService.java
extensions/guacamole-vault/modules/guacamole-vault-base/src/main/java/org/apache/guacamole/vault/user/VaultUserContext.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/KsmAuthenticationProviderModule.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmDirectoryService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/resources/translations/en.json

This change allows a user to put KSM one-time tokens directly into the connection group edit screen. If the token is invalid, an error will be displayed to the user.
This change will also validate the base64 KSM config blob at save time.
There's still no way to use a one-time-token directly in the `guacamole.properties` config file since the webapp can't rewrite that.

GUACAMOLE-1643: Allow usage of one-time KSM tokens when editing connection groups

---

extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmSecretService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmConnectionGroup.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmDirectoryService.java

This is a follow on from https://github.com/apache/guacamole-client/pull/743, and fixes a few related bugs:
- The KSM configuration attribute does not show up on existing connection groups that do not already have a value set
- Setting an empty value for the KSM configuration attribute on a connection group causes a failure when attempting to connect to a connection in that group

GUACAMOLE-1643: Fix bugs in KSM connection group edit behavior

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/java/org/apache/guacamole/auth/saml/acs/AuthenticationSessionManager.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/java/org/apache/guacamole/auth/saml/acs/SAMLService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/java/org/apache/guacamole/auth/saml/conf/ConfigurationService.java

The previous approach didn't actually allow requests to be signed - this change modifies the way we're calling the SAML library to allow signatures to be appended to the request as query parameters.
Draft since more testing is needed.

GUACAMOLE-1372: Modify usage of SAML library to allow signed requests.

---

guacamole/src/main/frontend/src/app/client/types/ManagedFileUpload.js
guacamole/src/main/frontend/src/app/rest/services/tunnelService.js
guacamole/src/main/java/org/apache/guacamole/tunnel/InputStreamInterceptingFilter.java

File uploads are split into chunks so that request size limits imposed by CDNs (such as Cloudflare's 100mb limit) are no longer an issue. 
The GuacamoleWriter responsible for writing to the stream stays open until the end of the upload rather than being closed by an opcode upon completion of a POST request.

GUACAMOLE-1320: Provide chunked file upload mechanism

---

Dockerfile

This change corrects the Docker build failures noted on https://issues.apache.org/jira/browse/GUACAMOLE-1614, which are ultimately due to the Jasmine Maven plugin requiring chromium-driver to run its tests.

GUACAMOLE-1614: Include chromium-driver in Docker build for sake of JS unit tests.

---

guacamole-common-js/src/main/webapp/modules/Client.js
guacamole-common-js/src/main/webapp/modules/Tunnel.js

From [GUACAMOLE-1687](https://issues.apache.org/jira/browse/GUACAMOLE-1687):
> Chrome, the various Chromium variants, and Safari will heavily throttle JavaScript timers within background tabs and windows. This prevents the tunnel from issuing its keep-alive ping and may result in a disconnect.
This change alters the way the keep-alive pings are sent, leveraging the pings received from the server to signal that another ping may need to be sent. Pings are still scheduled using JavaScript timers, but:
* Non-chained timeouts are used instead of chained timeouts or `setInterval()` (to avoid running into [Chrome's heavy throttling criteria](https://developer.chrome.com/blog/timer-throttling-in-chrome-88/)).
* Those pings will now be sent _immediately_ if enough time has elapsed since the last …

GUACAMOLE-1687: Leverage network activity to ensure keep-alive pings are sent.

---

guacamole/src/main/java/org/apache/guacamole/rest/auth/AuthenticationService.java
guacamole/src/main/java/org/apache/guacamole/rest/auth/GuacamoleAuthenticationProcessException.java

The recent changes adding support for automatically banning IP addresses that repeatedly fail to authenticate (#758) have resulted in the details of internal errors being omitted from the Tomcat logs, instead being logged as “User authentication was aborted”.
For example, if PostgreSQL is being used but the database server has not been started, the following is logged:
```
12:12:59.935 [http-nio-8080-exec-2] WARN  o.a.g.e.AuthenticationProviderFacade - The "postgresql" authentication provider has encountered an internal error which will halt the authentication process. If this is unexpected or you are the developer of this authentication provider, you may wish to enable debug-level logging. If this is expected and you wish to ignore such failures in the future, please set …
```

GUACAMOLE-990: Ensure internal errors during auth reach global error handling/logging.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-vault/modules/guacamole-vault-base/src/main/java/org/apache/guacamole/vault/conf/VaultAttributeService.java
extensions/guacamole-vault/modules/guacamole-vault-base/src/main/java/org/apache/guacamole/vault/user/VaultUserContext.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/GuacamoleExceptionSupplier.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/KsmAuthenticationProviderModule.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/conf/KsmAttributeService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/conf/KsmConfigurationService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmClient.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmSecretService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmConnection.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmConnectionGroup.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmDirectory.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmDirectoryService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmUser.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmUserFactory.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/resources/translations/en.json
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingUserContext.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/UserContext.java
guacamole/src/main/frontend/src/app/manage/controllers/manageUserController.js
guacamole/src/main/frontend/src/app/rest/services/schemaService.js
guacamole/src/main/frontend/src/app/settings/directives/guacSettingsPreferences.js
guacamole/src/main/frontend/src/app/settings/templates/settingsPreferences.html
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/webpack.config.js
guacamole/src/main/java/org/apache/guacamole/rest/schema/SchemaResource.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserObjectTranslator.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserResource.java

As mentioned in https://issues.apache.org/jira/browse/GUACAMOLE-1656, this allows users to specify their own KSM configurations, which can fill in any values not already provided by the admin-defined KSM configuration.
I've added a section to the end of the user preferences form for users to edit their own attributes. The Save button only applies to the user attributes immediately above - any existing preferences (mouse mode, language, etc) are still automatically updated whenever the changes are made.

GUACAMOLE-1656: Add per-user KSM vault functionality.

---

Dockerfile

Installs unzip and fixes docker start.sh to support setting LOGBACK_LEVEL to file path without delimiter problems

GUACAMOLE-1628: Docker image of guacamole client is missing unzip

---

guacamole/pom.xml

This change un-breaks the build by excluding the optional JavaMail dependency introduced by the latest version of Logback 1.3.x.

GUACAMOLE-1594: Exclude optional JavaMail dependency from Logback.

---

extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/conf/KsmAttributeService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/conf/KsmConfigurationService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/user/KsmDirectoryService.java
guacamole/src/main/frontend/src/app/settings/directives/guacSettingsPreferences.js
guacamole/src/main/frontend/src/app/settings/templates/settingsPreferences.html

This change ensures that:
* Users only see the KSM config attribute on their preferences if they have permission to edit it (i.e. update access to their own user).
* Admins do not see the user KSM config attribute for users if user-specific KSM attributes are not enabled.
* Clarified the meaning of the user-specific KSM attribute in light of the above.

GUACAMOLE-1656: Fix user preferences permissioning.

---

extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/conf/KsmConfigurationService.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmClient.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmClientFactory.java
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmSecretService.java

As discussed in [GUACAMOLE-1772](https://issues.apache.org/jira/browse/GUACAMOLE-1722) this allows user configuration of the KSM API call timeout.
While I was in there, I also cleaned up some warnings about unchecked null references.

GUACAMOLE-1772: Allow user configuration of KSM API call timeout.

---

guacamole/src/main/java/org/apache/guacamole/rest/directory/DirectoryObjectTranslator.java

Attributes with a value of `null` get filtered out when saving objects. An empty `timezone` attribute is `null`, but we want to save null value attributes.

GUACAMOLE-1728: Allow Null User Object attributes to be saved.

---

guacamole-common-js/src/main/webapp/modules/Client.js
guacamole-common/src/main/java/org/apache/guacamole/protocol/ConfiguredGuacamoleSocket.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleClientInformation.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleProtocolCapability.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleProtocolVersion.java
guacamole/src/main/frontend/src/app/client/controllers/clientController.js
guacamole/src/main/frontend/src/app/client/directives/guacClientMessage.js
guacamole/src/main/frontend/src/app/client/directives/guacMessageDialog.js
guacamole/src/main/frontend/src/app/client/styles/client-message.css
guacamole/src/main/frontend/src/app/client/styles/message-dialog.css
guacamole/src/main/frontend/src/app/client/templates/client.html
guacamole/src/main/frontend/src/app/client/templates/guacClientMessage.html
guacamole/src/main/frontend/src/app/client/templates/guacMessageDialog.html
guacamole/src/main/frontend/src/app/client/types/ManagedClient.js
guacamole/src/main/frontend/src/app/client/types/ManagedClientMessage.js
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/java/org/apache/guacamole/tunnel/TunnelRequestService.java

This is the client-side change for apache/guacamole-server#358, which adds support for notifying the connection owner when a user joins the connection.

GUACAMOLE-1293: Add client-side support for receiving join and leave notifications.

---

guacamole-docker/bin/start.sh

This corrects an issue in the Docker start.sh file for guacamole-client where the `SAML_IDP_URL` environment variable is not required when the metadata file is not provided. If an environment variable containing the URI of the metadata file is not provided, then the IdP URL should be required in addition to the entity ID and the callback URL.

GUACAMOLE-1322: Add SAML_IDP_URL as required for Docker container absent a metadata file.

---

guacamole/src/main/frontend/src/app/client/directives/guacClientUserCount.js
guacamole/src/main/frontend/src/app/client/styles/tiled-client-grid.css
guacamole/src/main/frontend/src/app/client/templates/guacClientUserCount.html
guacamole/src/main/frontend/src/translations/en.json

This change corrects the rendering of anonymous users withing the new user count UI, displaying those users as "Anonymous" with distinct styling:
When these users join/leave a connection, the message displayed is also specific to anonymous users:

GUACAMOLE-1293: Display anonymous users within a shared session as "Anonymous".

---

guacamole-docker/bin/start.sh

Add missing optional configuration options from docker start.sh script

GUACAMOLE-1733: Add missing optional configuration options from docker start.sh script

---

guacamole/src/main/frontend/src/app/storage/services/sessionStorageFactory.js

This change modifies the behavior of `sessionStorageFactory` such that the automatic deep copy is cached, rather than recreated each time. Instead, the deep copy is created _once_ and then only recreated if changes are made externally to the cached copy.

GUACAMOLE-1745: Ensure deep copies of session storage are created only if necessary.

---

guacamole/src/main/frontend/src/app/auth/service/authenticationService.js
guacamole/src/main/frontend/src/app/index/controllers/indexController.js
guacamole/src/main/java/org/apache/guacamole/GuacamoleSession.java
guacamole/src/main/java/org/apache/guacamole/rest/auth/HashTokenSessionMap.java
guacamole/src/main/java/org/apache/guacamole/rest/session/SessionResource.java

This change adds a periodic check that automatically clears out the local UI state if the server has invalidated the session. The main purpose of this is to ensure the UI always reflects server-side state within a reasonable timeframe, especially for the case that an admin may inadvertently leave a page open containing sensitive data.
The check is implemented with a `HEAD` request to `.../api/session` - a new REST API mechanism which returns HTTP 204 if the session is valid but does not affect that session's last access timestamp (all other REST API requests for resources within a session will update that timestamp).

GUACAMOLE-1744: Automatically clean up UI if session has expired in the background.

---

guacamole/src/main/frontend/src/app/clipboard/directives/guacClipboard.js
guacamole/src/main/frontend/src/app/clipboard/styles/clipboard.css
guacamole/src/main/frontend/src/app/clipboard/templates/guacClipboard.html
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/src/translations/ja.json

When bringing up the Guacamole menu (Ctrl+Alt+Shift) the contents of your clipboard are immediately visible within the clipboard editor. For privacy purposes, the contents of the clipboard editor should be hidden/collapsed until the user chooses to expand/show them.
This Pull request updates the Clipboard Directive to prevent displaying clipboard data in the clipboard editor until the clipboard editor has been focused on.

GUACAMOLE-1740: Don't display clipboard contents in the clipboard editor until it is focused on.

---

guacamole/src/main/frontend/src/app/index/controllers/indexController.js

The changes recently merged via #798 erroneously navigate the user back to `#/` if they visit a custom, unauthenticated page from an extension while not logged in. This change corrects that logic to use the presence/absence of a cached auth token as the primary condition determining whether their session should be retested for validity.

GUACAMOLE-1744: Clean up UI only if user is not logged in.

---

guacamole-docker/bin/build-guacamole.sh

GUACAMOLE-1738 Update version of MySQL connector used to resolve issue 1738 where it can no longer connect to the MySQL server using the new extension and old connector: https://issues.apache.org/jira/projects/GUACAMOLE/issues/GUACAMOLE-1738

GUACAMOLE-1738: Update version of MySQL connector

---

guacamole/src/main/frontend/src/app/clipboard/styles/clipboard.css

This pull request corrects the new CSS rules for the guacamole clipboard settings such that they affect strictly what they are intended to affect.

GUACAMOLE-1740: Prevent collisions of clipboard inactive and active classes with other classes of the same name.

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/java/org/apache/guacamole/auth/ssl/SSLClientAuthenticationResource.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/java/org/apache/guacamole/auth/ssl/conf/WildcardURIGuacamoleProperty.java

This change:
* Updates `WildcardURIGuacamoleProperty` such that it explicitly handles possible `null` inputs (omitted properties).
* Updates handling of received PEM such that anything but a single X.509 certificate is rejected, including PEM that contains nothing at all.

GUACAMOLE-839: Correct handling of possible null values within SSL/TLS client auth support.

---

guacamole/src/main/frontend/src/app/index/controllers/indexController.js
guacamole/src/main/frontend/src/app/index/styles/automatic-login-rejected.css
guacamole/src/main/frontend/src/index.html

This change adds an additional overall application state for the case that an error occurred during authentication without the use of a login form, and provides an alternative location for that error to be rendered when no login form is present.
For example, if authentication is attempted via some sort of SSO, but is repeatedly failing and is now being throttled by "guacamole-auth-ban", the following will appear (instead of a mysterious blank page):

GUACAMOLE-1756: Display login failures regardless of whether the interactive login form was used.

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/resources/html/sso-providers.html
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/resources/styles/sso-providers.css
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-cas/src/main/resources/html/sso-provider-cas.html
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-openid/src/main/resources/html/sso-provider-openid.html
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/resources/html/sso-provider-saml.html
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/resources/html/sso-provider-ssl.html

This change alters the HTML patches used by the various SSO extensions such that the common SSO provider list is added to the login UI no more than once. Additional SSO extensions that add to the UI after the first will simply add themselves to the existing list.

GUACAMOLE-1757: Ensure SSO provider list is added to login UI only once.

---

extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/TOTPUser.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/TOTPUserContext.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/UserVerificationService.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/usergroup/TOTPUserGroup.java
extensions/guacamole-auth-totp/src/main/resources/translations/en.json

Continuing the work started in #577, this adds an attribute to the TOTP module at both a user and group level that allows for disabling the TOTP requirement for a certain user or users who are members of one or more groups that have the requirement disabled.
This closes #577.

GUACAMOLE-1219: Add support for disabling TOTP for specific users and groups.

---

guacamole/src/main/frontend/src/app/auth/service/authenticationService.js

This corrects the issue noted by: https://github.com/apache/guacamole-client/commit/b6ce4776258ba5366a852b6dc950fb55306c28b1#r107038781

GUACAMOLE-839: Omit properties added by AngularJS core from auth request parameters.

---

Dockerfile
guacamole-common-js/.gitignore
guacamole-common-js/karma-ci.conf.js
guacamole-common-js/package-lock.json
guacamole-common-js/package.json
guacamole-common-js/pom.xml
guacamole-docker/bin/build-guacamole.sh

https://github.com/apache/guacamole-client/pull/826, but targeted at `staging/1.5.1` instead of `master.`
This change:
- Switches from jasmine-frontend-plugin to maven-frontend-plugin to get the build working
- Switches from chrome to firefox for unit tests 
- Disables tests unless explicitly requested so the build can be run in environments without firefox installed.
Future improvements that would be good (but are out of scope for fixing the build):
- Have `npm` run the build and tests
- Create a full-fledged NPM package for `guacamole-common-js` that could be published.

GUACAMOLE-1765: Use maven-frontend-plugin instead of jasmine-frontend-plugin to fix docker build.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLGuacamoleProperties.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLGuacamoleProperties.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerGuacamoleProperties.java

SQL Server limits all queries to a maximum of 2100 parameters. This can cause queries to fail within Guacamole if the number of objects being queried would exceed that limit.
This pull request updates the SQL-Server, MySQL, and PostgreSQL jdbc code to perform batch operations when attempting to query large collections of objects

GUACAMOLE-1253: Update select all queries to process in batches.

---

guacamole/src/main/frontend/src/app/import/controllers/importConnectionsController.js
guacamole/src/main/frontend/src/app/import/services/connectionParseService.js

This change does two things:
* Fix a bug where the loading spinner would be applied and never go away when file parsing succeeded, with connection errors
* Allow a bit more leeway for users in how they declare their group declarations:
- They can (as before) specify the full path like "ROOT/parent/child"
- They can use just a leading slash instead of the root group like "/parent/child"
- They can leave off the leading slash, like "parent/child"
- They can optionally include a trailing slash like "parent/child/"

GUACAMOLE-926: Fix loading bug and fuzzier group matching

---

guacamole/src/main/frontend/src/app/rest/services/tunnelService.js

Hello,
This change hides the authentication token from the http parameter by using the predefined header "Guacamole-Token" instead for the following API call.
GET /api/session/tunnels/<tunnel ID>/protocol?token=<token>

GUACAMOLE-1775: Auth token as a parameter in "session/tunnels/<tunnel ID>/protocol" request

---

guacamole/src/main/frontend/src/app/import/templates/connectionImport.html
guacamole/src/main/java/org/apache/guacamole/rest/directory/DirectoryResource.java

Yet again I failed to find these when I was fixing the earlier issues that I also failed to find earlier.
Anyway, this PR fixes 2 more problems:
* The permission replacement checkbox wasn't getting disabled properly
* An exception is thrown when trying to use the REPLACE verb in the patch directory endpoint, if a decorating extension e.g. `guacamole-history-recording-storage` is used.

GUACAMOLE-926: Batch import - fix UI issue with permission checkbox, fix replace error when using decorating extension.

---

extensions/guacamole-auth-totp/src/main/resources/translations/zh.json

Hello!
Found some missing translations in this extension during the trial.
So I updated the `zh.json` based on the `en.json` as well.
Also, tested locally by replacing the zh.json file directly, seems work well.

GUACAMOLE-1781: Update Simplified Chinese translation for totp auth extension

---

guacamole/src/main/frontend/src/app/import/services/connectionCSVService.js
guacamole/src/main/frontend/src/app/import/services/connectionParseService.js

Yet another batch import bugfix / improvement!? Nobody could have seen _this_ coming!
This change does two things:
* Fixes an issue where file-level CSV errors didn't get surfaced to the user
* Attempts to correct any invalidly-cased user-provided connection parameter values, when the parameter has a limited number of possible options.
The latter is intended to help out with the case where a user may, while editing a CSV in many popular spreadsheets, have their "true" values for boolean parameters converted to "TRUE", which the backend will not understand.

GUACAMOLE-926: Batch Import: Attempt to correct incorrectly-cased parameter values if possible

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

This change reapplies the same commits from #708 against `staging/1.5.2`.

GUACAMOLE-1562: Correct handling of received tunnel UUIDs.

---

guacamole/src/main/frontend/src/app/rest/services/tunnelService.js

This change reapplies the same commits from #841 against `staging/1.5.2`.

GUACAMOLE-1775: Use header for auth token instead of a parameter in "session/tunnels/<tunnel ID>/protocol" request

---

guacamole/src/main/java/org/apache/guacamole/rest/usergroup/UserGroupObjectTranslator.java

This change reapplies the same commits from #733 against `staging/1.5.2`.

GUACAMOLE-1606: UserGroup should retrieve UserGroup attributes, not User attributes.

---

guacamole-common-js/src/main/webapp/modules/Parser.js
guacamole-common-js/src/main/webapp/modules/Tunnel.js
guacamole-common-js/src/test/javascript/ParserSpec.js
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleInstruction.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleParser.java
guacamole-common/src/test/java/org/apache/guacamole/protocol/GuacamoleInstructionTest.java
guacamole-common/src/test/java/org/apache/guacamole/protocol/GuacamoleParserTest.java

The Java and JavaScript implementations of the Guacamole protocol parser may cause unexpected parsing failures due to those languages' use of UTF-16 internally for string representations and string length. In particular, characters involving high/low surrogates may end up with miscalculated length prefixes, ultimately causing the resulting instruction to fail to parse.
These changes refactor both implementations to calculate lengths in a way that takes high/low surrogates into account, and refactor the tunnel implementations to use a common parser.
The internal implementations of the length calculation (`codePointCount()` in Java and regex in JavaScript) were chosen after benchmarking the parser to verify that performance is not impacted. The "naive" solution (walking the string and …

GUACAMOLE-615: Correct potential parse failures in webapp parser implementations.

---

.ratignore
Dockerfile
guacamole-docker/mozilla-firefox.pref
pom.xml

This change:
1. Updates the Docker image build to use an up-to-date tag (`maven:3-jdk-8` does not appear to be updated any longer).
2. Manually updates the dependencies of `minify-maven-plugin` to pull in `plexus-utils`, which is no longer included automatically as of Maven 3.9.x.
The update to the Docker image build causes the same breakage as can be seen in CI (https://ci-builds.apache.org/job/Guacamole/job/guacamole-client-master/235/), while the update to the `pom.xml` fixes that breakage.

GUACAMOLE-1788: Fix build against Maven 3.9.x.

---

extensions/guacamole-auth-ban/pom.xml
extensions/guacamole-auth-ban/src/main/resources/guac-manifest.json
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-dist/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/resources/guac-manifest.json
extensions/guacamole-display-statistics/pom.xml
extensions/guacamole-display-statistics/src/main/resources/guac-manifest.json

This change fixes the guacamole-client build following the 1.5.2 version number bump by additionally bumping the versions of components that are not part of 1.5.2.

GUACAMOLE-1790: Bump version numbers of components not within 1.5.2.

---

guacamole-common-js/src/main/webapp/modules/Parser.js

The documentation build is currently failing with the following error:
```
$ jsdoc -c jsdoc-conf.json
ERROR: Unable to parse a tag's type expression for source file /home/mjumper/apache/guacamole/guacamole-client/guacamole-common-js/src/main/webapp/modules/Parser.js in line 310 with tag title "param" and text "{!*[]} elements
The values that should be encoded as the elements of a Guacamole
instruction. Order of these elements is preserved. This array MUST have
at least one element.": Invalid type expression "!*[]": Expected "=", "|", or end of input but "[" found.
ERROR: Unable to parse a tag's type expression for source file /home/mjumper/apache/guacamole/guacamole-client/guacamole-common-js/src/main/webapp/modules/Parser.js in line 324 with tag title "param" and text "{!*[]} elements …
```

GUACAMOLE-615: Correct JSDoc annotation for array of any type.

---

guacamole/src/main/frontend/src/app/import/controllers/importConnectionsController.js

I tried creating a connection with the name “平仮名” using CSV, JSON, and YAML file types. The existing file parsing logic will return a name of "å¹³ä»®å" instead.
Luckily, the fix was easy. All the file type checks (including the check of the first few bytes to see if the file is secretly a zip in disguise) still work as expected.

GUACAMOLE-926: Fix UTF-8 handling in batch import files.

---

guacamole-common-js/jsdoc-conf.json
guacamole-common-js/package-lock.json
guacamole-common-js/package.json
guacamole-common-js/pom.xml

This change adds JSDoc to the build, such that:
* Generation of JSDoc for guacamole-common-js need not be a separate, manual process at release time (it's just part of `mvn package`).
* The build fails if JSDoc fails to generate.

GUACAMOLE-1754: Generate JSDoc for guacamole-common-js as part of Maven build.

---

guacamole-common-js/src/main/webapp/modules/SessionRecording.js
guacamole-common-js/src/test/javascript/SessionRecordingSpec.js

When creating a new SessionRecording from a blob an error is thrown in the `readNextBlock` function when reading `blob.size` since `blob` is undefined. My understanding is that this will always be the case when creating a new SessionRecording from a blob.

GUACAMOLE-1793: Fix creation of SessionRecording from blob.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerEnvironment.java

As discussed in https://issues.apache.org/jira/browse/GUACAMOLE-1796, a batch size of `1000` is too big when fetching large lists of  connections.
I tested and verified that the suggested batch size of `500` works correctly when fetching thousands of connections, where `1000` does not.

GUACAMOLE-1796: Reduce SQL Server batch size to ensure fetching large lists of connections still works. 

---

doc/licenses/ipaddress-5.4.0/README
doc/licenses/ipaddress-5.4.0/dep-coordinates.txt
doc/licenses/spring-framework-5.3.27/README
doc/licenses/spring-framework-5.3.27/dep-coordinates.txt
doc/licenses/spring-security-5.8.3/NOTICE
doc/licenses/spring-security-5.8.3/README
doc/licenses/spring-security-5.8.3/dep-coordinates.txt
extensions/guacamole-auth-json/pom.xml
extensions/guacamole-auth-json/src/main/java/org/apache/guacamole/auth/json/RequestValidationService.java
extensions/guacamole-auth-json/src/test/java/org/apache/guacamole/auth/json/RequestValidationServiceTest.java

Newer versions of Spring Security lack support of Java 8.

GUACAMOLE-1809: Replace library used for IP address matching

---

guacamole-common-js/src/main/webapp/modules/SessionRecording.js

This is fixing an issue created in https://github.com/apache/guacamole-client/commit/7176ccce682202fcc0f804d52e9fba5efeee5a83 where frames are (in effect) never scheduled during recording playback, so whatever frame you seek to is just stuck forever.
I guess when I tested this I must not have properly rebuilt things, but I confirmed it was properly built and tested now.

GUACAMOLE-1803: Fix frame scheduling logic in recording playback.

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js

This is essentially a revert of https://github.com/apache/guacamole-client/commit/2a30cadb1e8163e6228e03816d452eb4a5b98e06
I've verified that right alt / altgr work both correctly windows / linux, ~but there's some kind of Mac-specific issue mentioned in https://issues.apache.org/jira/browse/GUACAMOLE-1113 that I'm not sure of, so drafting for now.~

GUACAMOLE-1113: Restore right alt in keyboard handler.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/permission/ModeledObjectPermissionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/permission/ModeledPermissionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/permission/SystemPermissionService.java

The issue here is that if you do a connection batch import with a file with 1000 connections, granting permission to each of these connections to a single user:
1. The connection creation succeeds since the connection creation is properly batched
2. The attempt to grant permissions causes an error since the permission updates were _not_ batched
This PR fixes point 2.

GUACAMOLE-1796: Batch updates to permissions so large permission changes can succeed.

---

extensions/guacamole-auth-ban/pom.xml
extensions/guacamole-auth-ban/src/main/resources/guac-manifest.json
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-dist/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/resources/guac-manifest.json
extensions/guacamole-display-statistics/pom.xml
extensions/guacamole-display-statistics/src/main/resources/guac-manifest.json

[This PR build](https://github.com/apache/guacamole-client/actions/runs/5468351262/jobs/9955867163?pr=894) is failing because a few extensions didn't have their versions bumped when 1.5.3 changes were merged back to master. 
Note that none of the affected extensions were actually modified in that PR. This error likely hasn't happened on the master branch due to stale docker layers.
This change corrects the versions so that everything builds correctly.

GUACAMOLE-1829: Correct versions of dependencies for remaining 1.5.2 versioned extensions.

---

Dockerfile

The 12.2.0 version breaks compatibility in terms of SSL/TLS behavior, causing database connection failures that did not previously occur.

GUACAMOLE-1838: Downgrade SQL Server JDBC driver to latest 9.4.x.

---

guacamole-common-js/src/main/webapp/modules/Parser.js

This fixes instruction buffers from xhr-based tunnels being processed multiple times in some cases due to the `startIndex` getting reset in the parser.

GUACAMOLE-1849: Fix a bug in Parser.js where receive would reparse instructions multiple times.

---

extensions/guacamole-auth-json/src/main/java/org/apache/guacamole/auth/json/RequestValidationService.java

Adds the `@Inject` notation to the constructor in `RequestValidationService` class so that it loads correctly with Guice, correcting an issue introduced by the addition of the parameterized construction from GUACAMOLE-1809.

GUACAMOLE-1851: Add Inject notation to RequestValidationService constructor to fix Guice loading.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/usergroup/UserGroupService.java

This change corrects a typo in database user group management, properly separating permission enforcement of _user_ creation from _user group_ creation.
As noted on [GUACAMOLE-1856](https://issues.apache.org/jira/browse/GUACAMOLE-1856), this happily does _not_ have security implications:
>
> ... A user with permission to create other users and the unintentional permission to create user groups would not be able to leverage that access to gain or grant any additional privileges:
>
> * A user cannot add users to a group unless they already have sufficient privileges to grant permissions to those users directly.
> * A user cannot grant any permissions to a group that they cannot already grant to a user.
>
It's the enforcement of other permissions that dictate whether anything can actually be …

GUACAMOLE-1856: Correct CREATE_USER vs. CREATE_USER_GROUP check in creation of groups.

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/pom.xml

[As noted on GUACAMOLE-839](https://issues.apache.org/jira/browse/GUACAMOLE-839?focusedCommentId=17770213&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17770213), the `bcpkix-fips` library depends on `bc-fips` using a version range. This leads to an unpredictable build and breakage of the license check whenever a new version of `bc-fips` is released.
These changes override the `bc-fips` dependency, instead explicitly selecting what is currently the latest version.

GUACAMOLE-839: Force usage of non-dynamic version of Bouncy Castle FIPS.

---

extensions/guacamole-auth-totp/src/main/resources/translations/de.json
guacamole/src/main/frontend/src/translations/ca.json
guacamole/src/main/frontend/src/translations/cs.json
guacamole/src/main/frontend/src/translations/de.json
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/src/translations/es.json
guacamole/src/main/frontend/src/translations/fr.json
guacamole/src/main/frontend/src/translations/ko.json
guacamole/src/main/frontend/src/translations/pl.json
guacamole/src/main/frontend/src/translations/pt.json
guacamole/src/main/frontend/src/translations/zh.json

some improvements to german translation

GUACAMOLE-1692: Updated german translation

---

guacamole/src/main/frontend/src/translations/en.json

This PR fixes a follow-up/copy-paste error introduced by #767 
Sorry for the inconvenience

GUACAMOLE-1692: Fix follow-up error on en.json

---

guacamole/src/main/frontend/src/app/settings/styles/history-player.css

These changes fix some styling issues with the heatmaps added in https://github.com/apache/guacamole-client/pull/927.
The heatmap and legend styling have both been tweaked to ensure that they show up on both black and white backgrounds (such as the opened text event viewer).

GUACAMOLE-1876: Fix heatmap and legend styling to work better with event viewer open.

---

guacamole/src/main/frontend/src/app/client/controllers/clientController.js
guacamole/src/main/frontend/src/app/client/services/guacFullscreen.js
guacamole/src/main/frontend/src/translations/de.json
guacamole/src/main/frontend/src/translations/en.json

associated JIRA issue: https://issues.apache.org/jira/browse/GUACAMOLE-1525
see also: GUACAMOLE-989 and GUACAMOLE-124
To start fullscreen mode:
Open gucamole's special menu via Ctrl+Alt+Shift and click fullsceen:
("Vollbild" is german for Fullscreen)

GUACAMOLE-1525: Support for true fullscreen mode and keyboard lock

---

guacamole/src/main/frontend/src/app/settings/styles/history-player.css

This change ensures that the session recording player controls can be hidden, even when the playback is paused. The controls will always be shown when the control bar is hovered over.
This is to allow admins to look at the bottom of the screen (which can contain import things like a task bar) when the recording is paused.

GUACAMOLE-1872: Hide session recording playback controls even when paused.

---

guacamole-docker/bin/start.sh

New PR according to https://issues.apache.org/jira/browse/GUACAMOLE-1860 and #913

GUACAMOLE-1860: fix typos in env variables

---

extensions/guacamole-auth-ban/pom.xml
extensions/guacamole-auth-ban/src/main/resources/guac-manifest.json
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-dist/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/resources/guac-manifest.json
extensions/guacamole-display-statistics/pom.xml
extensions/guacamole-display-statistics/src/main/resources/guac-manifest.json

This addresses the build failures on `master` as of the merge of #934.

GUACAMOLE-1887: Bump versions numbers of projects outside 1.5.4 scope.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerEnvironment.java

Individual connection (not connection group) concurrency limits are intended to be unlimited by default, however the application is enforcing a default per-user concurrency limit of “1”.
These changes set the default per-user concurrency limit to 0.

GUACAMOLE-1909: Update the default Max Connections Per User to 0.

---

guacamole/src/main/frontend/src/app/client/controllers/clientController.js
guacamole/src/main/frontend/src/app/client/directives/guacTiledClients.js
guacamole/src/main/frontend/src/app/client/styles/menu.css
guacamole/src/main/frontend/src/app/client/templates/client.html
guacamole/src/main/frontend/src/app/client/types/ManagedArgument.js
guacamole/src/main/frontend/src/app/client/types/ManagedClient.js
guacamole/src/main/frontend/src/app/form/directives/form.js
guacamole/src/main/frontend/src/app/form/directives/formField.js
guacamole/src/main/frontend/src/app/form/templates/form.html

This change allows extensions to define custom fields that have a few new capabilities, namely:
* Request the showing or hiding of the menu
* Save their own values without having to close the menu
* Receive events when the client, arguments, or protocol changes

GUACAMOLE-1904: Enhanced client menu field functionality

---

extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
extensions/guacamole-auth-header/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
extensions/guacamole-auth-json/src/main/resources/guac-manifest.json
extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json
extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
extensions/guacamole-auth-radius/src/main/resources/guac-manifest.json
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-cas/src/main/resources/guac-manifest.json
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-openid/src/main/resources/guac-manifest.json
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/resources/guac-manifest.json
extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
extensions/guacamole-history-recording-storage/src/main/resources/guac-manifest.json
extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/resources/guac-manifest.json
guacamole/src/main/java/org/apache/guacamole/extension/ExtensionModule.java

Got all the pom.xml files in the last pull request, but forgot the extension loader and the guac-manifest files.

GUACAMOLE-1906: Bump guac-manifest versions and add 1.5.5 to the extension loader.

---

extensions/guacamole-auth-ban/pom.xml
extensions/guacamole-auth-ban/src/main/resources/guac-manifest.json
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-dist/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/pom.xml
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/resources/guac-manifest.json
extensions/guacamole-display-statistics/pom.xml
extensions/guacamole-display-statistics/src/main/resources/guac-manifest.json

Bumps version for the components outside the 1.5.x scope up to 1.5.5.

GUACAMOLE-1915: Bump versions for projects outside the 1.5.5 scope.

---

guacamole/src/main/frontend/src/app/client/directives/guacClient.js

A follow on from https://github.com/apache/guacamole-client/pull/942, this change further adds new events to be broadcast when mouse or touch events are handled in the client. This is to allow custom fields that live outside the client menu to de-focus text fields and the like so they don't intercept user input that's intended to go into the client (since clicking inside the client won't automatically defocus input elements rendered outside the client, as users might expect).

GUACAMOLE-1904: Broadcast events for mouse/touch events in client.

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-openid/src/main/java/org/apache/guacamole/auth/openid/AuthenticationProviderService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-openid/src/main/java/org/apache/guacamole/auth/openid/conf/ConfigurationService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-openid/src/main/java/org/apache/guacamole/auth/openid/token/TokenValidationService.java

GUACAMOLE-1844 : OIDC JWT claims as user token
This patch allows IDP to send JWT claims that can be mapped to user tokens, prefixed with OIDC_. Same case transormation apply than LDAP_ and CAS_.
Define openid-attributes-claim-type with a comma-separated list of claims that should be mapped.
Multivalued JWT claims are not unrolled.

GUACAMOLE-1844 : OIDC JWT claims as user token

---

doc/licenses/logback-1.3.14/LICENSE.txt
doc/licenses/logback-1.3.14/README
doc/licenses/logback-1.3.14/dep-coordinates.txt
pom.xml

As discussed in https://github.com/apache/guacamole-client/pull/954, this is the latest Java 8 compatible version of Logback.

GUACAMOLE-1905: Revert to Java-8-compatible Logback 1.3.14.

---

doc/licenses/woodstox-core-5.4.0/README
doc/licenses/woodstox-core-5.4.0/dep-coordinates.txt
doc/licenses/woodstox-core-6.5.0/dep-coordinates.txt
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/pom.xml

In https://github.com/apache/guacamole-client/pull/954, the version of woodstox was bumped from `5.4.0` to `6.5.0`, but `6.5.0` is a major version bump past the `5.2.1` version that java-saml expects. }
This change restores the old `5.4.0` version of woodstox, which should remain in place until a newer `5.*` version of woodstox is released, or `java-saml` has a new release that uses a `6.*` version of woodstox.

GUACAMOLE-1905: Revert to java-saml-compatible version of woodstox.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/kubernetes.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/telnet.json
guacamole/src/main/frontend/src/translations/en.json

This is a follow on to https://github.com/apache/guacamole-client/pull/961. We should provide the same options for typescripts.

GUACAMOLE-1931: Add configuration option to allow overwriting typescript files.

---

guacamole/src/main/frontend/src/app/history/services/guacHistory.js
guacamole/src/main/frontend/src/app/home/controllers/homeController.js
guacamole/src/main/frontend/src/app/home/directives/guacRecentConnections.js
guacamole/src/main/frontend/src/app/home/styles/home.css
guacamole/src/main/frontend/src/app/home/templates/guacRecentConnections.html
guacamole/src/main/frontend/src/app/home/templates/home.html
guacamole/src/main/frontend/src/app/index/styles/headers.css
guacamole/src/main/frontend/src/app/settings/directives/guacSettingsPreferences.js
guacamole/src/main/frontend/src/app/settings/services/preferenceService.js
guacamole/src/main/frontend/src/app/settings/templates/settingsPreferences.html
guacamole/src/main/frontend/src/translations/en.json

I took a stab at an implementation of some initial changes to the Recent Connections that allow the user to control 1) whether they show up at all, and 2) how many connections are kept.
As part of the change I modified the title bar across the top a bit - used the Application Name in the upper-left (instead of "Recent Connections") and made it slightly smaller. I'm perfectly happy to take suggestions on alternatives for this - as many well know by this time, UX design is a weak spot for me :-).

GUACAMOLE-1866: Add capability for users to configure recent connections

---

guacamole/src/main/frontend/src/app/history/services/guacHistory.js
guacamole/src/main/frontend/src/app/home/directives/guacRecentConnections.js
guacamole/src/main/frontend/src/app/home/styles/home.css
guacamole/src/main/frontend/src/app/home/templates/guacRecentConnections.html

This is an additional change to the "Recent Connections" functionality that allows for a connection to be removed from the list. A small red "X" is added to the upper-right corner of the connection thumbnail, as shown in the image below, and, when clicked, the connection will be removed.
It's worth noting that I had some trouble positioning the "X" exactly where I wanted it (directly over the thumbnail image), while still allowing the click functionality to work correctly. If anyone has suggestions on how to update the CSS to position, but allow it to work, I'm open to suggestions. The main challenge was that I cannot place the `<div></div>` tags that contain the image inside of the `<a></a>` tags, so positioning over the `<img>` was a bit challenging.

GUACAMOLE-1866: Allow recent connections to be removed.

---

extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/UserVerificationService.java

A simple take at randomizing the key for users who have not confirmed enrollment. I'm not sure if this introduces any other gotchas or security issues - it almost seems too simple?

GUACAMOLE-1068: Generate random key at each login if key is unconfirmed.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json

We identified an issue where users were facing a generic error when attempting to save Guacamole connection parameters that exceeded the maximum allowed length (4096 characters). The error message was not clear and did not provide useful feedback regarding the input size constraint on the database column for connection parameters.
To enhance the user experience and provide a more informative error message, I have implemented the following changes:
- Added a new method `validateParameters` within the `ConnectionService` class. This method checks each connection parameter's value against the known maximum size limit before a connection is created or updated. If a parameter value exceeds the maximum allowed length, the method throws a `TranslatableGuacamoleClientOverrunException` with a …

GUACAMOLE-1948: Provide a comprehensive error message for input exceeding database column.

---

Dockerfile

Pull request based on discussion [here](https://lists.apache.org/thread/yoqfy9s6bfvcsgccc33kylgyk9h7pwko) and followup to `guacamole-server` pull request [here](https://github.com/apache/guacamole-server/pull/499).
I have tested that it works on macOS (arch: amd64) and a Raspberry Pi 4 (arch: aarch64), open to hearing how it works on other architectures!

GUACAMOLE-1374: Updating base Docker image for building on ARM

---

guacamole-common-js/src/main/webapp/modules/Mouse.js

Modern-day browsers abide the standardized wheel event (typed `WheelEvent`), however to support older browsers the legacy `DOMMouseScroll` (FireFox) and `mousewheel` (all others) events are also being registered.
However modern browsers support both the modern event as well as the legacy, which results in the wheel handler being registered multiple times. This results in the wheel handler firing twice instead of once, causing excessive scrolling.
This change separates the event registration such that either the modern or the legacy events are registered, and not both.

GUACAMOLE-1967: Remove duplicate wheel handler registrations.

---

guacamole-docker/environment/REMOTE_IP_VALVE_/configure.sh

Something I discovered when trying to deploy my other changes; https://github.com/apache/guacamole-client/pull/979 introduces a regression with the REMOTE_IP_VALVE_* environment variable scraper, in that `xmlstarlet` needs a separate --insert argument for each attribute in order to work.

GUACAMOLE-374: Fix xmlstarlet syntax for RemoteIpValve attributes

---

extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/AuthenticationProviderService.java

This change is intended to supersede the changes proposed by poor @josnabattula via PR #931 that I have been very slow to review. It builds off the original commit (27bbd35a3d8d7bfb41ac50dfc145e1314121d289) by:
* Removing unnecessary use of `TokenName.canonicalize()` (there's no need to dynamically derive the token name of a static value).
* Decoupling the concept of extracting the domain from the concept of using that domain to create a token (`getDomainToken()` renamed and redocumented as `getUserDomain()`).
* Removing unnecessary recompilation of the domain extraction `Pattern` (there's no need to repeatedly recompile the regex each time a user logs in - it never changes).

GUACAMOLE-1881: Add parameter token containing the domain of LDAP/AD usernames.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLEnvironment.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLGuacamoleProperties.java

These properties allow connecting to a MySQL 8.4+ database server. 
Either the public key can be retrieved from the server and set using the `mysql-server-rsa-public-key-file` property, or the public key can be automatically retrieved by setting the `mysql-allow-public-key-retrieval` property.

GUACAMOLE-1979: Allow setting required properties for connecting to MySQL 8.4 and later.

---

guacamole/src/main/frontend/src/app/clipboard/directives/guacClipboard.js
guacamole/src/main/frontend/src/app/clipboard/styles/clipboard.css
guacamole/src/main/frontend/src/app/clipboard/templates/guacClipboard.html
guacamole/src/main/frontend/src/translations/ca.json
guacamole/src/main/frontend/src/translations/cs.json
guacamole/src/main/frontend/src/translations/de.json
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/src/translations/fr.json
guacamole/src/main/frontend/src/translations/ja.json
guacamole/src/main/frontend/src/translations/zh.json

The current hidden clipboard implementation requires two clicks to use the editor: one click to show the clipboard contents, and another click to focus the editor.
This change updates the clipboard editor UI such that only a single click is required to show the clipboard contents. Focus is automatically given to the editor upon clicking:
1 - No action yet taken | 2 - Hover | 3 - Click
-------------------------|-----------|-----------

GUACAMOLE-1740: Do not require multiple clicks to begin editing the clipboard.

---

guacamole/src/main/frontend/src/app/settings/templates/settingsConnections.html

Users that are used to the established Guacamole UI will be used to clicking the leftmost button when attempting to create a new connection, but the leftmost button has changed from "New Connection" to "Import".
This change restores that original button order, with "New Connection" being on the far left.

GUACAMOLE-926: Reorder "Import" button to end to avoid fighting muscle memory.

---

extensions/guacamole-auth-duo/pom.xml
extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/UserVerificationService.java
extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/conf/ConfigurationService.java
extensions/guacamole-auth-json/pom.xml
extensions/guacamole-auth-totp/pom.xml
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/conf/ConfigurationService.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/UserVerificationService.java
guacamole-ext/pom.xml
guacamole-ext/src/main/java/org/apache/guacamole/properties/IPAddressListProperty.java

This pull request implements the feature proposed in Jira for GUACAMOLE-1855 - the Duo and TOTP modules can be configured to either be bypassed for users logging in from specific hosts, or can be configured to be explicitly required for users logging in from specific hosts, while other hosts are bypassed.
This allows situations where users connecting from the Internet ought to be required to complete MFA, but users logging in from behind a VPN or on a corporate network may not need to perform the extra authentication step.

GUACAMOLE-1855: Allow MFA modules to be configured to bypass or enforce for specific hosts.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java

This is an attempt at resolving the challenge specified in the Jira ticket, which is that the default `${GAUC_DATE}` and `${GUAC_TIME}` tokens may not match up to the JDBC start date/time. JDBC-specific tokens have been added - including the start date/time, which are pulled from the `ActiveConnectionRecord` for the connection - which should allow the date and time to match up with the database records. Other tokens have been added, as well, which will also resolve some other Jira issues, such as wanting to use the connection name in the token.

GUACAMOLE-61: Add JDBC-specific tokens, including start date and time

---

extensions/guacamole-auth-ldap/schema/guacConfigGroup.ldif
extensions/guacamole-auth-ldap/schema/guacConfigGroup.schema
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/simple/SimpleConnection.java

This pull request implements the changes necessary to support the `GuacamoleProxyConfiguration` in LDAP connections (and any future extensions that make use of the `SimpleConnection` class.  Not entirely sure this is the right/best way to go, but took a stab at it.

GUACAMOLE-577: Support for configuring the Guacamole Proxy in LDAP Connections

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java

This tweaks the recently-added JDBC tokens to following the naming conventions that the other extensions use.

GUACAMOLE-61: New JDBC tokens should follow the standard naming conventions.

---

extensions/guacamole-auth-ldap/schema/guacConfigGroup.ldif
extensions/guacamole-auth-ldap/schema/guacConfigGroup.schema
extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/connection/ConnectionService.java

Slight correction to the schema files - the proxy hostname attribute should be single-valued, similar to port and encryption method.
...and one comment that I caught that was incorrect...

GUACAMOLE-577: guacConfigProxyHostname should be single-valued.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java

Coverity caught that I had failed to make the strings for defining the JDBC tokens `static`, so here's a quick fix for that.

GUACAMOLE-61: Strings for token names should be static.

---

extensions/guacamole-auth-restrict/src/main/java/org/apache/guacamole/auth/restrict/RestrictionVerificationService.java

I've added a few null checks and re-arranged a couple of other checks to address some issues that Coverity flagged in the recently-committed login restriction code.

GUACAMOLE-1020: Perform some additional null checks in restriction verification service.

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/java/org/apache/guacamole/auth/sso/SSOAuthenticationProvider.java

Fixes an issue with duplicate bindings for the `Environment` class(es) in the SSO modules.

GUACAMOLE-1239: Remove Environment binding from SSO base class.

---

guacamole-docker/entrypoint.d/000-migrate-docker-links.sh
guacamole-docker/entrypoint.d/010-migrate-legacy-variables.sh

These changes add a new `entrypoint.d/000-migrate-docker-links.sh` script that migrates environment variables coming from the following Docker links:
* `guacd`
* `mysql`
* `postgres`
* `sqlserver`
That's the entire list of all Docker links we've ever supported historically. Any other variables that may be from other Docker links are untouched.
The migration intentionally occurs before the general deprecated environment variable migration script, as `POSTGRES_PORT` can be either from direct usage of that deprecated environment variable _or_ from a deprecated Docker link.

GUACAMOLE-374: Restore support for legacy Docker links.

---

extensions/guacamole-auth-restrict/src/main/java/org/apache/guacamole/auth/restrict/Restrictable.java
extensions/guacamole-auth-restrict/src/main/java/org/apache/guacamole/auth/restrict/RestrictionVerificationService.java
extensions/guacamole-auth-restrict/src/main/java/org/apache/guacamole/auth/restrict/connection/RestrictedConnection.java
extensions/guacamole-auth-restrict/src/main/java/org/apache/guacamole/auth/restrict/connectiongroup/RestrictedConnectionGroup.java
extensions/guacamole-auth-restrict/src/main/java/org/apache/guacamole/auth/restrict/form/DateTimeRestrictionField.java
extensions/guacamole-auth-restrict/src/main/java/org/apache/guacamole/auth/restrict/usergroup/RestrictedUserGroup.java
extensions/guacamole-auth-restrict/src/main/resources/config/restrictConfig.js
extensions/guacamole-auth-restrict/src/main/resources/controllers/dateTimeRestrictionFieldController.js
extensions/guacamole-auth-restrict/src/main/resources/guac-manifest.json
extensions/guacamole-auth-restrict/src/main/resources/templates/dateTimeRestrictionField.html
extensions/guacamole-auth-restrict/src/main/resources/translations/en.json

This pull request implements an additional restriction type in the guacamole-auth-restrict extension that allows `Connection` and `ConnectionGroup` objects to be made available only after a certain date and/or only up to a certain date, adding to the overall ability to finely control when connections and connection groups are available. The changes will add the top two options in the following screenshot:
Error messages will be similar to those thrown when the connection is restricted using the other (existing) options.

GUACAMOLE-1701: Implement connection date and time before and after restrictions.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/EntityService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledAuthenticatedUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/usergroup/ModeledUserGroup.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/usergroup/UserGroupService.java
guacamole-ext/src/main/java/org/apache/guacamole/environment/DefaultEnvironment.java
guacamole-ext/src/main/java/org/apache/guacamole/environment/DelegatingEnvironment.java
guacamole-ext/src/main/java/org/apache/guacamole/environment/Environment.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractAuthenticatedUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractIdentifiable.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/AbstractUserGroup.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/DelegatingUser.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/Identifiable.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/CaseSensitivity.java

This change removes the `isCaseSensitive()` function recently added to `Identifiable` to avoid any case where a faulty implementation within one extension's `AuthenticatedUser`, etc. may cause incorrect behavior within the proper implementation of another. Instead, we rely purely on the global configuration setting.
This change also:
* Eliminates the `GuacamoleException` that `getCaseSensitivity()` may throw, instead providing a default implementation that handles logging of such errors.
* Adds a `canonicalize()` convenience function to `CaseSensitivity` to abstract away transformation of identifiers into a case-insensitive form.
thus avoiding much boilerplate.

GUACAMOLE-1239: Refactor away need for isCaseSensitive() function of Identifiable.

---

extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/user/AuthenticatedUser.java

There was an outstanding reference to `ConfigurationService` that needed to be removed. This change also removes the unused `Logger`.

GUACAMOLE-1239: Fix RADIUS extension build.

---

guacamole-common-js/src/main/webapp/modules/Client.js

A `<canvas>` cannot have a width or height of zero. We _do_ have a check for this, but we're actually still calling `toCanvas()` regardless of that check, breaking playback of session recordings depending on the content of the recording.
This change corrects this by moving the call to `toCanvas()` such that it only occurs if the layer has non-zero width and height.

GUACAMOLE-2018: Convert layer to canvas during exportState() only if layer is non-empty.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole/src/main/frontend/src/translations/ca.json
guacamole/src/main/frontend/src/translations/cs.json
guacamole/src/main/frontend/src/translations/de.json
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/src/translations/es.json
guacamole/src/main/frontend/src/translations/fr.json
guacamole/src/main/frontend/src/translations/ko.json
guacamole/src/main/frontend/src/translations/pl.json
guacamole/src/main/frontend/src/translations/pt.json
guacamole/src/main/frontend/src/translations/zh.json

Add Czech keyboard layout to client connected to https://issues.apache.org/jira/browse/GUACAMOLE-1708
Closing https://github.com/apache/guacamole-client/pull/1054

GUACAMOLE-1708: Add Czech keyboard layout

---

guacamole/src/main/frontend/src/app/player/services/playerHeatmapService.js

I believe we can simply limit minimum `maxPossibleBucketValue` to 1 instead of having variable `NUM_BUCKETS`.

GUACAMOLE-2021: Fix session recording playback heatmap for short videos.

---

extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmClient.java

Fixes the issue plus changes log messages for this case:
`16:52:41.850 [http-nio-8080-exec-10] WARN  o.a.g.vault.ksm.secret.KsmClient - "keeper://XXX/field/login" could not be resolved: Record 'XXX' not found`
`16:52:42.442 [http-nio-8080-exec-10] WARN  o.a.g.vault.ksm.secret.KsmClient - "keeper://XXX/field/password" could not be resolved: Record 'XXX' not found`

GUACAMOLE-2030: Fix KSM static token mapping for per-user config.

---

guacamole-common/src/main/java/org/apache/guacamole/io/ReaderGuacamoleReader.java
guacamole-common/src/test/java/org/apache/guacamole/io/ReaderGuacamoleReaderTest.java

Implement the GuacamoleParser within the ReaderGuacamoleReader to support multi byte characters when reading instructions.

GUACAMOLE-2036: Implement the GuacamoleParser within the ReaderGuacamoleReader.

---

guacamole-common/src/main/java/org/apache/guacamole/io/ReaderGuacamoleReader.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleInstruction.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleParser.java

This change builds on the changes from @aleitner via #1057, optimizing for the common case where a parsed `GuacamoleInstruction` must be converted back into Guacamole protocol and re-sent. With these changes, performance of both `read()` and `readInstruction()` are identical, and both exceed the performance of past releases.
For benchmarks and further context, see [the final review comment on PR #1057](https://github.com/apache/guacamole-client/pull/1057#pullrequestreview-2642357246).

GUACAMOLE-2036: Reuse buffers received by parser when converting instructions back to character arrays.

---

guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleInstruction.java
guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleParser.java

This change improves on #1063 a bit, removing the need to alter the public API to support the internals of `GuacamoleParser`.

GUACAMOLE-2036: Refactor away public constructor accepting internal char array.

---

guacamole/src/main/frontend/src/app/player/services/keyEventDisplayService.js

Timestamps of key events within the “Keystroke Log” UI will sometimes show as “0:00”, even though there are no associated details displayed and such a timestamp would be in the past.
This is caused by batches that get created but end up not having any events completed within the `batchSeparation` time frame.

GUACAMOLE-2005: FIlter out batches that ended up not having any keystroke events.

---

extensions/guacamole-display-statistics/src/main/resources/directives/guacClientStatistics.js
extensions/guacamole-display-statistics/src/main/resources/styles/clientStatistics.css
extensions/guacamole-display-statistics/src/main/resources/templates/guacClientStatistics.html

Add a close button:
Show statistics bar again:

GUACAMOLE-2020: Allow hiding the display statistics bar.

---

guacamole-common/src/main/java/org/apache/guacamole/protocol/GuacamoleParser.java

In guacamole-server `GUAC_INSTRUCTION_MAX_ELEMENTS` is defined as 128. In guacamole-client, `INSTRUCTION_MAX_ELEMENTS` is still 64.

GUACAMOLE-2036: Increase the number of max elements to match guacamole server.

---

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/kubernetes.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/telnet.json
guacamole-ext/src/main/resources/org/apache/guacamole/protocols/vnc.json
guacamole/src/main/frontend/src/translations/en.json

[Jira Discussion](https://issues.apache.org/jira/browse/GUACAMOLE-2002)

GUACAMOLE-2002: Allow connection clipboard limits to be configured.

---

guacamole-common-js/src/main/webapp/modules/SessionRecording.js

At first I considered to unite and refactor `Guacamole.SessionRecording.loadInstruction` and `function handleInstruction(opcode, args)`. My idea was to get rid of `Guacamole.SessionRecording.getElementSize`. Unfortunately, most likely it will not allow us to fix the issue isolated because the recording can be received as a blob or via a tunnel.  `loadInstruction`/`getElementSize` are used for both cases and through `Gucamole.Parser`. There would be too many changes with a chance of new bugs affecting not just the playback.
So to fix the issue isolated, I simply calculate UTF8 string byte size for every instruction content. Performance benchmarks show that a custom implementation of such a function works better than TextEncoder and Blob API. For example, [a …

GUACAMOLE-2043: Fix playback of recordings which have multibyte character instructions.

---

guacamole-docker/entrypoint.d/010-migrate-legacy-variables.sh

The deprecation warning and continued support for `POSTGRESQL_USER` were unintentionally removed as part of earlier changes for GUACAMOLE-374.

GUACAMOLE-374: Restore support and deprecation warning for POSTGRESQL_USER variable.

---

extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/java/org/apache/guacamole/auth/ssl/conf/ConfigurationService.java
guacamole-docker/build.d/010-map-guacamole-extensions.sh

As I document the SSL client auth support, I encountered the `SSL_ENABLED` environment variable and realized the current naming of these configuration options is going to be pretty confusing.
This change addresses that by switching the configuration option prefix from `ssl` to `ssl-auth`, thus `SSL_ENABLED` becomes a more sensible `SSL_AUTH_ENABLED`.

GUACAMOLE-1956: Rename SSL client auth properties to use "ssl-auth" prefix (not just "ssl").

---

extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/DuoAuthenticationProvider.java
extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/UserVerificationService.java
extensions/guacamole-auth-header/src/main/java/org/apache/guacamole/auth/header/AuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/sharing/ConnectionSharingService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
extensions/guacamole-auth-json/src/main/java/org/apache/guacamole/auth/json/RequestValidationService.java
extensions/guacamole-auth-json/src/main/java/org/apache/guacamole/auth/json/user/UserDataService.java
extensions/guacamole-auth-json/src/test/java/org/apache/guacamole/auth/json/RequestValidationServiceTest.java
extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/AuthenticationProviderService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-cas/src/main/java/org/apache/guacamole/auth/cas/AuthenticationProviderService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-openid/src/main/java/org/apache/guacamole/auth/openid/AuthenticationProviderService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/java/org/apache/guacamole/auth/saml/AuthenticationProviderService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/java/org/apache/guacamole/auth/ssl/AuthenticationProviderService.java
extensions/guacamole-auth-totp/src/main/java/org/apache/guacamole/auth/totp/user/UserVerificationService.java
guacamole-ext/src/main/java/org/apache/guacamole/net/RequestDetails.java
guacamole-ext/src/main/java/org/apache/guacamole/net/auth/Credentials.java
guacamole/src/main/java/org/apache/guacamole/event/RemoteAddress.java

We cannot rely on referencing the `HttpServletRequest` outside the scope of that request. To fix this behavior, this change:
* Refactors away reliance on continued references to `HttpServletRequest` within `Credentials`, replacing them with a `RequestDetails` copy of the request.
* Deprecates:
* `getRequest()` in favor of `getRequestDetails()`
* `setRequest()`, `setSession()`, `setRemoteAddress()`, and `setRemoteHostname()` in favor of `setRequestDetails()`

GUACAMOLE-2052: Maintain independent copy of request details in Credentials.

---

extensions/guacamole-auth-header/src/main/java/org/apache/guacamole/auth/header/AuthenticationProviderService.java
extensions/guacamole-auth-json/src/main/java/org/apache/guacamole/auth/json/AuthenticationProviderService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/java/org/apache/guacamole/auth/sso/user/SSOAuthenticatedUser.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-cas/src/main/java/org/apache/guacamole/auth/cas/ticket/TicketValidationService.java
extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/java/org/apache/guacamole/auth/saml/AuthenticationProviderService.java

This was missing from the SSL SSO and is necessary to ensure the `${GUAC_USERNAME}` token is properly substituted in cases where SSO and SSO-like auth methods are used.

GUACAMOLE-839: Ensure all SSO and related mechanisms set Credentials username.

---

guacamole-ext/src/main/java/org/apache/guacamole/net/RequestDetails.java

This change replaces usage of `asIterator()` with direct, traditional usage of the relevant `Enumeration`. The `asIterator()` function was added to `Enumeration` in Java 9 and can't be used here.

GUACAMOLE-2065: Remove usage of asIterator() (not part of Java 8).

---

guacamole-ext/src/main/java/org/apache/guacamole/properties/FileGuacamoleProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/GuacamoleProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/IntegerGuacamoleProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/LongGuacamoleProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/StringGuacamoleProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/StringListProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/TimeZoneGuacamoleProperty.java
guacamole-ext/src/main/java/org/apache/guacamole/properties/URIGuacamoleProperty.java

Took a quick stab at fixing this issue with adding the comma back in as a delimiter. Not tested, yet, but I think the RegEx is sound.

GUACAMOLE-2051: Allow Guacamole properties to be either comma or semi-colon or comma delimited.

---

guacamole/src/main/frontend/src/app/player/directives/player.js
guacamole/src/main/frontend/src/app/player/styles/player.css
guacamole/src/main/frontend/src/app/player/templates/player.html
guacamole/src/main/frontend/src/translations/en.json
guacamole/src/main/frontend/src/translations/fr.json

Currently the only way to close the recording video player is to use the browser's "back" button.
Add a button that automatically hides with the control bar:

GUACAMOLE-2025: Add a button to close the recording video player.
