- guacamole/src/main/webapp/translations/nl.json
I added the missing translations from the en.json file and made a style correction.
> GUACAMOLE-2 Added Missing translations for screen recording etc in Dutch

- guacamole/src/main/webapp/app/rest/services/tunnelService.js
This change alters the `iframe` cleanup of `tunnelService.downloadStream()` to take place only after one of the following events:
1. The `load` event for the `iframe` fires (not all browsers do this, Chrome in particular).
2. A "reasonable" amount of time has elapsed after the stream has ended, and it is likely that the browser has finished saving the file (5 seconds).
Lacking these changes, it is possible that the `iframe` will be removed prior to the actual file save, thus causing the download to be canceled immediately upon completion.
> GUACAMOLE-105: Clean up download iframe only if likely to be safe.

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/fr.json
Added a few of the translations provided by the reporter on this issue.  There are quite a few others missing - and I don't speak French - but thought I'd at least add the ones that were provided.
> GUACAMOLE-156: Add missing French translations.

- guacamole-common-js/src/main/webapp/modules/Tunnel.js
https://issues.apache.org/jira/browse/GUACAMOLE-229
> GUACAMOLE-229: Remove intervals properly when XHR is polling.

- guacamole-common-js/src/main/webapp/modules/Client.js
Adding functions for exporting/importing client state allow snapshots of Guacamole sessions to be taken, such that instructions following those snapshots can be replayed with the same effect.
This mainly has practical uses for [GUACAMOLE-250](https://issues.apache.org/jira/browse/GUACAMOLE-250), where these opaque state objects will form the basis of auto-generated keyframes, but is required in any case where a Guacamole session may need to be rewound (otherwise, the entire session would need to be replayed to produce the same state).
> GUACAMOLE-250: Add support for saving/restoring Guacamole.Client state.

- doc/guacamole-example/pom.xml
- doc/guacamole-playback-example/pom.xml
- extensions/guacamole-auth-cas/pom.xml
- extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-duo/pom.xml
- extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-header/pom.xml
- extensions/guacamole-auth-header/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-dist/pom.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/pom.xml
- extensions/guacamole-auth-ldap/pom.xml
- extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-noauth/pom.xml
- extensions/guacamole-auth-noauth/src/main/resources/guac-manifest.json
- guacamole-common-js/pom.xml
- guacamole-common-js/src/main/webapp/modules/Version.js
- guacamole-common/pom.xml
- guacamole-ext/pom.xml
- guacamole/pom.xml
- pom.xml
Everything was modified this time.
> GUACAMOLE-314: Bump version numbers of all modified components to 0.9.13-incubating.

- guacamole-common-js/src/main/webapp/modules/Tunnel.js
https://issues.apache.org/jira/browse/GUACAMOLE-437
When establishing a Guacamole tunnel to an endpoint that requires (for example) authentication, it is often needed to send custom headers. The existing `withCredentials` option works well for session cookies in cross-domain environments, but when there are no sessions or authentication relies on headers, there is no way to have an authenticated tunnel request.
This PR adds an optional variable to the `HTTPTunnel` so users can configure a set of custom headers to be sent on every tunnel request. That can be used to configure additional headers for authentication, distributed tracing, and other needs. Something like:
```javascript
var tunnel = new Guacamole.HTTPTunnel(endpoint, true);
tunnel.extraHeaders = {
"X-Auth-Token": "Foo", …
```
> GUACAMOLE-437: Allow to send custom headers with the Guacamole tunnel requests

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/es.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
- guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
- guacamole/src/main/webapp/translations/en.json
- guacamole/src/main/webapp/translations/es.json
This include the spanish translation to the guacamole client. For the extensions it is translated only the jdbc tree.
> GUACAMOLE-463: Spanish translation for Guacamole client. 

- guacamole-common-js/src/main/webapp/modules/AudioRecorder.js
Pretty simple change here to prefer the newer getUserMedia() method.
> GUACAMOLE-237: Move to new getUserMedia method.

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ArbitraryAttributeMap.java
#233 introduced code specific to the 1.8 version of the JDK, breaking the build on platforms with 1.7. This PR restores compatibility with 1.7.
> GUACAMOLE-96: Restore compatibility with 1.7 JDK.

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml
Fix for issue identified in GUACAMOLE-505 for the stray left join in the SQL Server UserMapper.xml file.
> GUACAMOLE-505: Remove stray left join in SQL Server UserMapper.

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/user/PasswordRecordMapper.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserRecordMapper.xml
Fixes a couple of issues reported with SQL Server compatibility and the lack of support for the LIMIT keyword.
> GUACAMOLE-525: Fix issues with SQL Server compatibility

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
In addition to inherently correcting the behavior of the "disabled" flag, this also corrects the handling of password expiration, only following the password expiration flow if the user actually used the database to authenticate.
> GUACAMOLE-529: Apply database-specific account restrictions depending on context.

- guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json
- guacamole-ext/src/main/resources/org/apache/guacamole/protocols/telnet.json
- guacamole/src/main/webapp/translations/en.json
Client-side changes to allow the backspace key to be configured for SSH and Telnet sessions.
> GUACAMOLE-269: Add fields for controlling Backspace behavior.

- guacamole/src/main/webapp/app/clipboard/services/clipboardService.js
Finally: the Holy Grail.
https://developers.google.com/web/updates/2018/03/clipboardapi
https://www.w3.org/TR/clipboard-apis/#async-clipboard-api
> GUACAMOLE-559: Add support for reading/writing clipboard contents using the Asynchronous Clipboard API.

- guacamole-common/src/main/java/org/apache/guacamole/protocol/FailoverGuacamoleSocket.java
Some protocols, in particular SSH and telnet, may send a decent amount of data before the connection status is known. The previous limit of roughly 2KB was a bit small.
This change increases the default limit to 128KB and allows the limit to be overridden.
> GUACAMOLE-622: Increase FailoverGuacamoleSocket instruction queue limit.

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/activeconnection/ActiveConnectionPermissionService.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledPermissions.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/permission/AbstractPermissionService.java
See build failure:
https://lists.apache.org/thread.html/a03a4116cd1cef9fea9144d11f328e9bb16070b50bcdde3e1e678dfd@%3Cdev.guacamole.apache.org%3E
> GUACAMOLE-360: Update active connection permission check to support user groups.

- extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/AuthenticationProviderService.java
- extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/ConfigurationService.java
- extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/conf/PrivateKeyGuacamoleProperty.java
- extensions/guacamole-auth-cas/src/main/java/org/apache/guacamole/auth/cas/form/CASTicketField.java
- extensions/guacamole-auth-cas/src/main/resources/casModule.js
These changes clean up code and correct a minor typo that caused the CAS redirect to fail.
> GUACAMOLE-526: Correct redirect issue with CAS module

- guacamole-docker/bin/build-guacamole.sh
- guacamole-docker/bin/start.sh
Added Duo to the docker build and start scripts.
> GUACAMOLE-271: Duo in docker image

- guacamole-docker/README.md
- guacamole-docker/bin/start.sh
Did my best to follow the CONTRIBUTING, as I meant to submit these changes a while back.
JIRA: https://issues.apache.org/jira/browse/GUACAMOLE-626
> GUACAMOLE-626: Add support for Docker secrets to startup.sh

- extensions/guacamole-auth-cas/pom.xml
- extensions/guacamole-auth-cas/src/licenses/LICENSE
- extensions/guacamole-auth-cas/src/licenses/bundled/jaxb-api-2.3.1/license.txt
- extensions/guacamole-auth-duo/pom.xml
- extensions/guacamole-auth-duo/src/licenses/LICENSE
- extensions/guacamole-auth-duo/src/licenses/bundled/jaxb-api-2.3.1/license.txt
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-dist/src/licenses/LICENSE
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-dist/src/licenses/bundled/jaxb-api-2.3.1/license.txt
- extensions/guacamole-auth-totp/pom.xml
- extensions/guacamole-auth-totp/src/licenses/LICENSE
- extensions/guacamole-auth-totp/src/licenses/bundled/jaxb-api-2.3.1/license.txt
Updates pom.xml to include the javax.xml.bind dependency explicitly for modules that require it.
> GUACAMOLE-736: Explicitly pull in javax.xml.bind depdendency

- guacamole/src/main/webapp/app/form/directives/form.js
- guacamole/src/main/webapp/app/form/directives/formField.js
- guacamole/src/main/webapp/app/form/services/formService.js
- guacamole/src/main/webapp/app/form/templates/checkboxField.html
- guacamole/src/main/webapp/app/form/templates/dateField.html
- guacamole/src/main/webapp/app/form/templates/emailField.html
- guacamole/src/main/webapp/app/form/templates/form.html
- guacamole/src/main/webapp/app/form/templates/numberField.html
- guacamole/src/main/webapp/app/form/templates/passwordField.html
- guacamole/src/main/webapp/app/form/templates/selectField.html
- guacamole/src/main/webapp/app/form/templates/textAreaField.html
- guacamole/src/main/webapp/app/form/templates/textField.html
- guacamole/src/main/webapp/app/form/templates/timeField.html
- guacamole/src/main/webapp/app/form/templates/timeZoneField.html
- guacamole/src/main/webapp/app/login/directives/login.js
- guacamole/src/main/webapp/app/login/styles/dialog.css
- guacamole/src/main/webapp/app/login/templates/login.html
These changes:
* Add a new `disabled` attribute to the `guacForm` and `guacFormField` directives which allow fields and forms to be disabled.
* Updates existing field types to support being disabled.
* Disables the login form while the authentication request is being processed and while the initial route following login has not yet been satisfied.
The CSS associated with the login dialog has also been updated such that the dialog doesn't repeatedly flash/fade with each state change.
> GUACAMOLE-742: Provide feedback while login is in progress.

- guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
- guacamole/src/main/webapp/translations/en.json
Someone else did the hard work of generating the keymap, so I'll finish it up with the simple JSON modification. :smile:
> GUACAMOLE-354: Add de-ch-qwertz option for RDP keymap.

- guacamole/src/main/webapp/app/form/directives/form.js
- guacamole/src/main/webapp/app/form/directives/formField.js
- guacamole/src/main/webapp/app/form/templates/checkboxField.html
- guacamole/src/main/webapp/app/form/templates/dateField.html
- guacamole/src/main/webapp/app/form/templates/emailField.html
- guacamole/src/main/webapp/app/form/templates/form.html
- guacamole/src/main/webapp/app/form/templates/languageField.html
- guacamole/src/main/webapp/app/form/templates/numberField.html
- guacamole/src/main/webapp/app/form/templates/passwordField.html
- guacamole/src/main/webapp/app/form/templates/selectField.html
- guacamole/src/main/webapp/app/form/templates/textAreaField.html
- guacamole/src/main/webapp/app/form/templates/textField.html
- guacamole/src/main/webapp/app/form/templates/timeField.html
- guacamole/src/main/webapp/app/form/templates/timeZoneField.html
- guacamole/src/main/webapp/app/login/directives/login.js
- guacamole/src/main/webapp/app/login/templates/login.html
Note: This is not specific to just password fields, but any field type in general.
> GUACAMOLE-302: Incorrect password field focus

- extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-cas/src/main/resources/translations/ja.json
- extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-duo/src/main/resources/translations/ja.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/ja.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-openid/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-openid/src/main/resources/translations/ja.json
- extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-quickconnect/src/main/resources/translations/ja.json
- extensions/guacamole-auth-radius/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-radius/src/main/resources/translations/ja.json
- extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-totp/src/main/resources/translations/ja.json
- guacamole/src/main/webapp/translations/ja.json
Added Japanese language support for guacamole-client.
> GUACAMOLE-821: Add Japanese translation

- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPConnectionService.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ObjectQueryService.java
I believe I've got the two resource leak issues resolved from the new LDAP code...
> GUACAMOLE-234: Fix resource leaks in new LDAP code.

- extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-cas/src/main/resources/translations/de.json
- extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-duo/src/main/resources/translations/de.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/de.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-openid/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-openid/src/main/resources/translations/de.json
- extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-quickconnect/src/main/resources/translations/de.json
- extensions/guacamole-auth-radius/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-radius/src/main/resources/translations/de.json
- extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-totp/src/main/resources/translations/de.json
- guacamole/src/main/webapp/translations/de.json
Updated the main german translation and added translations for the extensions.
I also switched the translation from a non-formal ("Du") to the formal ("Sie") expression.
Please note that i can't test the extension-translations, but checked them against a JSON-Validator.
Feel free to contact me through Jira for questions / clarifications (https://issues.apache.org/jira/browse/GUACAMOLE-699)
> GUACAMOLE-699: Update german translations

- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/ConfigurationService.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/LDAPGuacamoleProperties.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/MemberAttributeType.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/MemberAttributeTypeProperty.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/group/UserGroupService.java
This supersedes PR #422 
(NB it also supersedes long inactive #245 )
> GUACOMOLE-300: Support posixGroup in LDAP Authentication and Group-based Session Admission

- extensions/guacamole-auth-radius/src/main/java/org/apache/guacamole/auth/radius/RadiusConnectionService.java
Turns out Exception usually only has one x...
> GUACAMOLE-1001: Minor spelling correction.

- guacamole/src/main/webapp/translations/fr.json
Building upon PR #390 which seems abandoned, I made further improvements to the French translation by fixing typos, ensuring more consistency and adding any missing translations.
> GUACAMOLE-759: Update French translation

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCEnvironment.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
Realized as I was doing one final look through the previous set of changes that a few style issues needed correction and a couple of changes made didn't get reverted.  All very minor/cosmetic, but just wanted it to be as clean as possible.
> GUACAMOLE-708: Minor style corrections and code clean-up.

- extensions/guacamole-auth-saml/src/main/java/org/apache/guacamole/auth/saml/conf/ConfigurationService.java
Against the correct branch, this time!
> GUACAMOLE-103: Adjust checks for entity ID and ACS URL properties.

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLEnvironment.java
This PR fixes the properties returned for MySQL Client Certificate configuration
> GUACAMOLE-1136: Return correct MYSQL_SSL_CLIENT_

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/MySQLAuthenticationProviderModule.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLEnvironment.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLGuacamoleProperties.java
- guacamole-ext/src/main/java/org/apache/guacamole/properties/TimeZoneGuacamoleProperty.java
- guacamole-ext/src/test/java/org/apache/guacamole/properties/TimeZoneGuacamolePropertyTest.java
This adds support for the various JDBC modules for configuring the database server timezone.
> GUACAMOLE-760: Add support for configuring server timezone.

- guacamole-ext/src/test/java/org/apache/guacamole/token/TokenFilterTest.java
Oops...forgot about the JUnit tests...
> GUACAMOLE-1081: Fix JUnit tests for token modifiers.

- extensions/guacamole-auth-cas/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-cas/src/main/resources/translations/fr.json
- extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-duo/src/main/resources/translations/fr.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/fr.json
- extensions/guacamole-auth-openid/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-openid/src/main/resources/translations/fr.json
- extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-quickconnect/src/main/resources/translations/fr.json
- extensions/guacamole-auth-saml/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-saml/src/main/resources/translations/fr.json
- extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-totp/src/main/resources/translations/fr.json
- guacamole/src/main/webapp/translations/fr.json
Hi,
I have added/updated French translations for both the application and the extensions. I have used the English translation as the base.
The associated JIRA cards were already existing, so I referenced them.
Regards
> GUACAMOLE-1160 : Update French translations.

- guacamole-common-js/src/main/webapp/modules/AudioPlayer.js
- guacamole-common-js/src/main/webapp/modules/AudioRecorder.js
- guacamole-common-js/src/main/webapp/modules/BlobWriter.js
- guacamole-common-js/src/main/webapp/modules/Client.js
- guacamole-common-js/src/main/webapp/modules/Display.js
- guacamole-common-js/src/main/webapp/modules/JSONReader.js
- guacamole-common-js/src/main/webapp/modules/Keyboard.js
- guacamole-common-js/src/main/webapp/modules/Layer.js
- guacamole-common-js/src/main/webapp/modules/Mouse.js
- guacamole-common-js/src/main/webapp/modules/OnScreenKeyboard.js
- guacamole-common-js/src/main/webapp/modules/SessionRecording.js
- guacamole-common-js/src/main/webapp/modules/Status.js
- guacamole-common-js/src/main/webapp/modules/StringReader.js
- guacamole-common-js/src/main/webapp/modules/Tunnel.js
- guacamole-common-js/src/main/webapp/modules/VideoPlayer.js
Alternatively use a primitive type instead of nullable boxed type.
> GUACAMOLE-986: Add non-nullable modifier to return type of functions never returning null

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/es.json
- guacamole/src/main/webapp/translations/es.json
Adding Spanish translations for new options available from last versions. Also improved the translation for some of the existing text.
> GUACAMOLE-1339: Add missing Spanish translations for client 1.3.0

- guacamole/src/main/webapp/translations/cs.json
GUACAMOLE-781: Corrections and additions to Czech translation
> GUACAMOLE-781: Corrections and additions to Czech translation

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/ko.json
- guacamole/src/main/webapp/translations/ko.json
Lines that reference other lines on korean translation files have been added.
> GUACAMOLE-1355: Add missing korean translation that reference others.

- guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json
- guacamole/src/main/frontend/src/translations/en.json
See apache/guacamole-server#357.
> GUACAMOLE-478: Add parameter definition and translations for "normalize-clipboard".

- guacamole/src/main/java/org/apache/guacamole/extension/ExtensionClassLoader.java
This change corrects a resource leak introduced by #687.
As most of this change involves wrapping things in a try/catch, I recommend looking at this diff with whitespace changes ignored.
> GUACAMOLE-1508: Ensure extension JarFile is always properly closed.

- guacamole-common-js/src/main/webapp/modules/SessionRecording.js
This change migrates the internal, dynamically-generated keyframe storage of `Guacamole.SessionRecording` into `Blob` objects that the browser can page out to the disk if necessary, allowing larger recordings to be seeked through even if the number of keyframes required would otherwise exceed available memory.
> GUACAMOLE-896: Leverage Blobs for storage of recording keyframes.

- guacamole-docker/bin/start.sh
Sorry I renamed the branch and it closed the PR...
It's good now, the PR can be merged, PR name, commit message are ok
> GUACAMOLE-1322: fix SAML plugin loading

- guacamole/src/main/frontend/src/app/home/templates/home.html
Oops, this is a do-over of PR #719 because I messed up the Git history.  Sorry for the trouble, @mike-jumper !
> GUACAMOLE-1584: add CSS ids to section headers on home page

- extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/java/org/apache/guacamole/auth/saml/conf/ConfigurationService.java
https://issues.apache.org/jira/browse/GUACAMOLE-1372
> GUACAMOLE-1372: Support signing/encryption keys for SAML auth extension.

- extensions/guacamole-vault/modules/guacamole-vault-ksm/src/main/java/org/apache/guacamole/vault/ksm/secret/KsmSecretService.java
This is a fix for a bug introduced in https://github.com/apache/guacamole-client/pull/739.
In testing, I made the unfortunate assumption that once the loop hit the root connection group, the `getConnectionGroup()` call would return `null` since this is what happened with my setup.
In fact, there's nothing in the API that explicitly guarantees that there can't be cycles. Later testing determined that this can actually happen when using sharing profiles.
This change modifies the loop so that it keeps track of all iterated identifiers. If any identifier is ever seen twice, it knows that a cycle has been hit, and immediately exits.
I've verified that this change fixes the infinite recursion issue seen when using sharing profiles.
> GUACAMOLE-1629: Keep track of iterated identifiers when recursing connection group tree looking for KSM attribute to ensure no infinite loop.

- Dockerfile
- guacamole-docker/bin/start.sh
See https://issues.apache.org/jira/browse/GUACAMOLE-1005
Docs PR: https://github.com/apache/guacamole-manual/pull/130
> GUACAMOLE-1005: Docker, configure RemoteIPValve

- guacamole/src/main/frontend/src/app/auth/service/authenticationService.js
As discussed in [GUACAMOLE-1721](https://issues.apache.org/jira/browse/GUACAMOLE-1721), this change removes all auth response information except the auth token itself from local storage.
> GUACAMOLE-1721: Store only auth token from auth response in localStorage.

- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/ConnectedLDAPConfiguration.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/LDAPConnectionService.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/DefaultLDAPConfiguration.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/EnvironmentLDAPConfiguration.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/JacksonLDAPConfiguration.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/LDAPConfiguration.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/LDAPGuacamoleProperties.java
- extensions/guacamole-auth-ldap/src/main/java/org/apache/guacamole/auth/ldap/conf/LDAPSSLProtocol.java
Adds support for configuring the SSL protocol version to use when making a secure LDAP connection.
> GUACAMOLE-1488: Add support for configuring LDAP SSL protocol.

- extensions/guacamole-auth-ban/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-ban/src/main/resources/translations/pl.json
- extensions/guacamole-auth-duo/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-duo/src/main/resources/translations/pl.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/pl.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-quickconnect/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-quickconnect/src/main/resources/translations/pl.json
- extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/resources/translations/pl.json
- extensions/guacamole-auth-sso/modules/guacamole-auth-sso-cas/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-sso/modules/guacamole-auth-sso-openid/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-sso/modules/guacamole-auth-sso-saml/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-totp/src/main/resources/guac-manifest.json
- extensions/guacamole-auth-totp/src/main/resources/translations/pl.json
- extensions/guacamole-history-recording-storage/src/main/resources/guac-manifest.json
- extensions/guacamole-history-recording-storage/src/main/resources/translations/pl.json
- guacamole/src/main/frontend/src/translations/pl.json
> GUACAMOLE-1730: Add polish translation

- guacamole/src/main/frontend/src/translations/cs.json
GUACAMOLE-1758: Updated czech translation
> GUACAMOLE-1758: Updated czech translation

- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCEnvironment.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLEnvironment.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/org/apache/guacamole/auth/mysql/conf/MySQLGuacamoleProperties.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLEnvironment.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/apache/guacamole/auth/postgresql/conf/PostgreSQLGuacamoleProperties.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerEnvironment.java
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/java/org/apache/guacamole/auth/sqlserver/conf/SQLServerGuacamoleProperties.java
This change reapplies the same commits from #821 against `staging/1.5.2`.
> GUACAMOLE-1253: Update select all queries to process in batches.

- guacamole/src/main/frontend/src/translations/cs.json
Correction of some inaccurately translated words in the previous translation. Completion of the translation of the "import" section according to the English original.
> GUACAMOLE-1792: Updated czech translation

- guacamole-common-js/src/main/webapp/modules/Keyboard.js
Tested on firefox, chrome, and safari. Handling appears to work correctly on all with both left and right option.
> GUACAMOLE-1810: Fix meta handling on Mac Firefox.

- guacamole/src/main/frontend/src/translations/ca.json
In the interest of helping #930 along, this change combines the three commits from that PR into a single commit with an appropriate message. The set of changes themselves are otherwise identical.
> GUACAMOLE-1880: Correct and update Catalan translation.

- extensions/guacamole-auth-duo/src/main/resources/translations/it.json
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/it.json
- extensions/guacamole-auth-quickconnect/src/main/resources/translations/it.json
- extensions/guacamole-auth-sso/modules/guacamole-auth-sso-base/src/main/resources/translations/it.json
- extensions/guacamole-auth-totp/src/main/resources/translations/it.json
- extensions/guacamole-history-recording-storage/src/main/resources/translations/it.json
- guacamole/src/main/frontend/src/translations/it.json
Correct and improve existent italian translations, add new translations.
> GUACAMOLE-1612: Fix/Add italian translations

- guacamole/src/main/frontend/src/translations/fr.json
Correction/improvement of French translations.
Addition of missing translations.
> GUACAMOLE-1611: Improve FR translations and add missings ones

- extensions/guacamole-auth-sso/modules/guacamole-auth-sso-ssl/src/main/java/org/apache/guacamole/auth/ssl/conf/ConfigurationService.java
The current implementation assumes that the `Host` header will _only_ contain the host, but this is not the case. It may also contain the port, in which case a simple comparison against the expected hostname will fail.
This change modifies that comparison to ignore the port, if present.
> GUACAMOLE-839: Fix handling of non-standard HTTPS ports for SSL client auth.

- guacamole-common-js/src/main/webapp/modules/Touch.js
This addresses an issue where touch IDs on some browsers (iOS Safari) are _huge_ and very likely to be summarily dropped by implementations. These changes leverage an integer pool to normalize the IDs to predictable, sequential integers.
> GUACAMOLE-2080: Automatically map local touch IDs to predictable, sequential integer IDs.

- Dockerfile
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserGroupPermissionMapper.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/permission/UserPermissionMapper.xml
- extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/usergroup/UserGroupMapper.xml
* Update mysql jdbc driver 8.3.0 => 9.3.0
* Update postgresql jdbc driver 42.7.2 => 42.7.7
* Fix typos within sqlserver mybatis mapper files.
> GUACAMOLE-2099: Update jdbc drivers to latest.
